### ISSUE TITLE
Add --merge option to k3sup install

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#1]
## Description

Add --merge option to k3sup install

## Detail

This would take an existing kubeconfig file and merge the incoming configuration. By default this tends to switch the context.

Examples:

https://ahmet.im/blog/mastering-kubeconfig/

This can also be done via code with `kubectl`:

https://github.com/civo/cli/blob/0a5cd47484999fb61f5bd27c46c81209211b2bb4/lib/kubernetes.rb#L200

If we can avoid `vendoring` the Kubernetes clientset, then this will keep the binary quick to build and relatively lean. Perhaps using go/exec to run `kubectl`?

**Comment by alexellis** [comment]
If anyone should want to pick this up, I think the way the Civo Ruby CLI does this would work fine for the tool.

It should be a relatively simple case of "exec" to run "kubectl" and then flatten/merge the new kubeconfig and the old one (if it exists).

Example of go/exec -> https://golang.org/src/os/exec/example_test.go

**Comment by utsavanand2** [comment]
I've sent a pull request :)

**Comment by alexellis** [comment]
https://github.com/alexellis/k3sup/pull/4
