### ISSUE TITLE
Offer helm3 for "k3sup app install"

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#107]
## Expected Behaviour

Now that helm 3 is GA and projects are converting / updating their charts, it'd be great to offer it as a flag, or switch over to it where it makes sense instead of `helm template / kubectl apply`

## Current Behaviour

Helm 2 is used, but tiller is bypassed via `helm untar / helm template`

## Possible Solution

Either update a flag to pass in `--helm-ver` or see if one of the charts like openfaas can be converted. The code to download helm should also be updated or extended.

Example:

```
k3sup app install cert-manager --helm3
```

**Comment by alexellis** [comment]
Perhaps someone could try this with one or two of the apps and then report back? It should be a task that can be done in < 30 mins.

**Comment by utsavanand2** [comment]
I can try it on the next Sunday if it's not urgent

**Comment by alexellis** [comment]
Perhaps the `openfaas` app would be the best one to start with, with regards to: https://github.com/alexellis/k3sup/issues/107

**Comment by alexellis** [comment]
This issue shouldn't be closed until all work is complete.

**Comment by elmariofredo** [comment]
If I understand it correctly helm3 is backward compatible with helm2 so why not globally set helm to v3 and verify that all charts are working properly?

**Comment by alexellis** [comment]
@elmariofredo contributions are most welcome, please do feel free to send us a PR to enable the helm3 flag for each chart.

**Comment by elmariofredo** [comment]
What is your reasoning behind keeping helm2 support? I would rather replace helm2 with helm3 completely as helm3 is backward compatible.

**Comment by alexellis** [comment]
I appreciate that you have a different opinion, thank you for voicing that. At some point the support may be removed, but breaking changes like this cannot be made as knee-jerk reactions.

The helm2 code also offers templating, which is a different install approach to what we're doing in the `--helm3` flag.
