### ISSUE TITLE
[Feature Request] cert-manager 0.12.0 with ARM support

### ISSUE THREAD

**Issue by j0nl1** [alexellis/k3sup#109]
## Expected Behaviour

When I saw the pods was crashing I made some research and found the problem could be related with iptables and I used the workaround but still same issue.
```
sudo iptables -F
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
```

## Current Behaviour

![image](https://user-images.githubusercontent.com/40375118/69482042-d3944380-0e16-11ea-8afd-cfe2ead7201c.png)
`kubectl describe pod cert-manager-cainjector-576978ffc8-7m2mr -n cert-manager`
```Name:               cert-manager-cainjector-576978ffc8-7m2mr
Namespace:          cert-manager
Priority:           0
PriorityClassName:  <none>
Node:               k4s-node-1/192.168.1.11
Start Time:         Sat, 23 Nov 2019 16:48:28 +0100
Labels:             app=cainjector
                    app.kubernetes.io/instance=cert-manager
                    app.kubernetes.io/managed-by=Tiller
                    app.kubernetes.io/name=cainjector
                    helm.sh/chart=cainjector-v0.11.0
                    pod-template-hash=576978ffc8
Annotations:        <none>
Status:             Running
IP:                 10.42.1.6
Controlled By:      ReplicaSet/cert-manager-cainjector-576978ffc8
Containers:
  cainjector:
    Container ID:  containerd://898cf7e2556053e242b8a63229c49165d949e3502f05bb51a1f05373cab321c1
    Image:         quay.io/jetstack/cert-manager-cainjector:v0.11.0
    Image ID:      quay.io/jetstack/cert-manager-cainjector@sha256:cf77d14d1c825190a38ac6b593f591998e3b34464f626f24479eb3e21dd589b3
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=2
      --leader-election-namespace=kube-system
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 23 Nov 2019 17:27:08 +0100
      Finished:     Sat, 23 Nov 2019 17:27:08 +0100
    Ready:          False
    Restart Count:  16
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from cert-manager-cainjector-token-wt8f8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  cert-manager-cainjector-token-wt8f8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cert-manager-cainjector-token-wt8f8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason          Age                    From                 Message
  ----     ------          ----                   ----                 -------
  Normal   Scheduled       <unknown>              default-scheduler    Successfully assigned cert-manager/cert-manager-cainjector-576978ffc8-7m2mr to k4s-node-1
  Normal   Pulling         40m                    kubelet, k4s-node-1  Pulling image "quay.io/jetstack/cert-manager-cainjector:v0.11.0"
  Normal   Pulled          40m                    kubelet, k4s-node-1  Successfully pulled image "quay.io/jetstack/cert-manager-cainjector:v0.11.0"
  Normal   Pulled          38m (x4 over 39m)      kubelet, k4s-node-1  Container image "quay.io/jetstack/cert-manager-cainjector:v0.11.0" already present on machine
  Normal   Created         38m (x5 over 39m)      kubelet, k4s-node-1  Created container cainjector
  Normal   Started         38m (x5 over 39m)      kubelet, k4s-node-1  Started container cainjector
  Warning  BackOff         35m (x20 over 39m)     kubelet, k4s-node-1  Back-off restarting failed container
  Normal   SandboxChanged  29m                    kubelet, k4s-node-1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          27m (x4 over 29m)      kubelet, k4s-node-1  Container image "quay.io/jetstack/cert-manager-cainjector:v0.11.0" already present on machine
  Normal   Created         27m (x4 over 29m)      kubelet, k4s-node-1  Created container cainjector
  Normal   Started         27m (x4 over 29m)      kubelet, k4s-node-1  Started container cainjector
  Warning  BackOff         4m17s (x111 over 28m)  kubelet, k4s-node-1  Back-off restarting failed container
```

## Steps to Reproduce (for bugs)

1. Install k3sup
2. Configure 1 server and 2 nodes
3. k3s app install cert-manager
4.

## Context

I'm trying to get cert-manager working

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
 Master Node RPI3: 
Linux k3s-node-1 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Worker Node RPI4:
Linux k4s-node-1 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
Worker Node RPI3:
Linux k3s-master-node 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
* Operating System and version (e.g. Linux, Windows, MacOS):

**Comment by alexellis** [comment]
cert-manager isn't adversed as working with RPi. 

I will be updating to 0.12.0 which has multi-arch images when I can test it.

I actually do have this working fine on my RPi4 with Raspbian this is what I did - https://gist.github.com/alexellis/d0af490e9938423d4b7f686158e6d3b6

**Comment by alexellis** [comment]
/set title: [Feature Request] cert-manager 0.12.0 with ARM support

**Comment by alexellis** [comment]
By the way you'll need a public IP for cert-manager to work on RPi or to use port forwarding on 80,443 on your home router. The alternative is to use the inlets-operator with inlets-pro.

**Comment by j0nl1** [comment]
First of all, thanks for you response. I thought arm was supported in cert-manager.

I'm using no-ip hostname connected to my router throught dyndns configuration. I can see my deployments in my domain regarding inlets, would it need for cert-manager?

thanks again!

**Comment by alexellis** [comment]
If you're happy to expose your home IP to the world and only need one IP then you can continue with that approach without inlets.

Try my gist above and as I say cert-manager goes multi-arch with 0.12.0.

**Comment by j0nl1** [comment]
I'm trying to apply your config but I got an error.

```
~/.k3sup/bin/helm template cert-manager --name cert-manager --namespace cert-manager --output-dir /tmp/charts/cert-manager/rendered --values /tmp/charts/cert-manager/values.yaml --set image.repository=quay.io/jetstack/cert-manager-controller-arm --set webhook.image.repository=quay.io/jetstack/cert-manager-webhook-arm --set cainjector.image.repository=quay.io/jetstack/cert-manager-cainjector-arm
Error: stat cert-manager: no such file or directory
```
By the way I tried inlets and it is awesome, I didn't know there was such a thing.
I follow you guide and could make a deploy with nginx. I just have a question, I guess when you use expose deployment type loadbalancer create a new instance in digitalocean. Is there any possibility to use the same instance for multiple deploys?

Thanks again! 👍

**Comment by alexellis** [comment]
Error: stat cert-manager: no such file or directory

Run it in the temporary folder where the files were generated. By the "charts" folder.

**Comment by alexellis** [comment]
It looks like the change to 0.12.0 is a "no-harm" upgrade:

https://cert-manager.io/docs/installation/upgrading/upgrading-0.11.12/

https://hub.helm.sh/charts/jetstack/cert-manager

**Comment by j0nl1** [comment]
It would be a good idea to include extra params to specific which architecture you want to use and depending which one you selected it install their images.

I just updated manually which images to use.

**Comment by alexellis** [comment]
Yes it would be good but it's not required in 0.12.0 since they publish multi-arch images. I've released a new version now so will close this
