### ISSUE TITLE
[Feature] Add version to "k3sup version" through git metadata

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#11]
[Feature] Add version to "k3sup version" through git metadata

## Expected Behaviour

The following should print a version just like [inlets.dev](https://inlets.dev/) in its [Makefile](https://github.com/alexellis/inlets/blob/master/Makefile)

```
k3sup version
```

## Current Behaviour

Just prints a welcome message.

## Possible Solution

Follow the approach in the [Makefile](https://github.com/alexellis/inlets/blob/master/Makefile) of inlets.

## Steps to Reproduce (for bugs)

1. Run `make`
2. Run `./bin/k3sup version` (pick the right binary for your dev environment)

## Context

For helping with bug reports etc.

**Comment by alexellis** [comment]
Here's the PR that added it to inlets for some more context: https://github.com/alexellis/inlets/pull/17/files

How it works:
* the Makefile determines the version by running the `git` CLI
* `-ldflags` passes the value into the compiler for the Go binary
* the go code exposes a package-level variable to store the value
* the go "version" command reads that data back and prints it out

Any questions, just shout.

**Comment by angelbarrera92** [comment]
Ill do!
