### ISSUE TITLE
[App request] Add MuShop

### ISSUE THREAD

**Issue by stretchcloud** [alexellis/k3sup#112]
## Expected Behaviour
```
ks3up install mushop
```

## Possible Solution
MuShop is an Open Source Application that spans across various tier of OSS Tooling and K8S Components. Great for any Demo. Live app is hosted here -> https://mushop.ateam.cloud/ 

Use the OpenFaaS app as an example and install via:

https://github.com/oracle-quickstart/oci-cloudnative/blob/master/deploy/complete/helm-chart/

**Comment by alexellis** [comment]
I'll leave this here to gauge interest from the community. Thanks for the suggestion.

**Comment by alexellis** [comment]
I'm not seeing this as something requested, so I'd suggest we leave off for now. Thanks for the suggestion

**Comment by blaisep** [comment]
While I like the idea of a working implementation that people can use as a starting point, I think mushop has a few too many moving parts for my taste.
