### ISSUE TITLE
[App request] Add kubernetes-dashboard 

### ISSUE THREAD

**Issue by biels** [alexellis/k3sup#125]
I have been trying to install kubernetes-dashboard and it hasn't been an easy task. Since it is very useful especially in testing / sandbox environments.

I would like to be able make it accessible via http and without password and with all permssions on the cluster. Keep in mind that I am talking about development clusters and not production ones for this. 

Useful links:
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
https://github.com/kubernetes/dashboard

Using the yml files provided in those official sources I have not been able to successfully deploy and operate the dashboard. I got the token and used it but it didn't redirect to the UI, it was stuck at the login screen.

**Comment by Waterdrips** [comment]
Hi @biels I have raised a PR that should implement this, are you able to test it out? 

if you have a working golang build env you should be able to pull the branch, then run `go build && ./k3sup app install kubernetes-dashboard`
