### ISSUE TITLE
Feature: Hostname support in install/join

### ISSUE THREAD

**Issue by jamshid** [alexellis/k3sup#131]
## Expected Behaviour
Coming from docker / docker-machine and a little swarm, confused by the k3sup requirement that the servers are all accessed by ip. Why not allow names? Is there a fundamental reason maybe with kubernetes?
## Current Behaviour
```
k3sup install --ip $(dig +short mb1-6.tx.example.com) --user jamshid
k3sup join --ip $(dig +short mb1-7.tx.example.com) --server-ip $(dig +short mb1-6.example.com) --user jamshid
```
## Possible Solution
Would be nice if the commands worked without the ip lookup and if ip addresses change. In my case they're mostly static ips.

## Context

IT department created some machines for experimenting with k3s. We usually deal with machine names not ip's.

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
vmware on prem
* Operating System and version (e.g. Linux, Windows, MacOS):
centos 7.6

**Comment by alexellis** [comment]
I would consider this, but it's only had one upvote. Let's see if it's worth the time and investment?

**Comment by klmcwhirter** [comment]
accessing servers by ip address in general is an anti-pattern and should be discouraged

**Comment by alexellis** [comment]
Can you evidence that @klmcwhirter?
