### ISSUE TITLE
[Feature] "app info" command

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#133]
Add `app info NAME` command

## Expected Behaviour

`k3sup app info openfaas` should print the post-installation instructions and a link to the project homepage.

## Current Behaviour

Users like myself are tempted to read the go code, or install the app a second time (unnecessarily) in order or see the usage instructions.

## Possible Solution

Reference the post-install variable from the install command in a new `info` command.

Start off by providing:

* openfaas
* inlets-operator
* postgresql
* minio

Here's a good example to follow: https://github.com/alexellis/k3sup/pull/137

**Comment by alexellis** [comment]
Re-opening as this covers all commands.

**Comment by utsavanand2** [comment]
@alexellis I can help. I see it's pending for about a month now

**Comment by alexellis** [comment]
Yes please do. This should be available for each app.
