### ISSUE TITLE
[Feature] Install k3s v1.0.1 by default

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [alexellis/k3sup#134]
Now default deploy 1.0.0

**Comment by alexellis** [comment]
Great to hear 1.0.1 is out :+1:

**Comment by alexellis** [comment]
/set title: [Feature] Install k3s v1.0.1 by default

**Comment by alexellis** [comment]
Hi @Pomazan-Bogdan what specifically did you want from the v1.0.1 release? i'm looking at the release notes and it wasn't clear - https://github.com/rancher/k3s/releases/tag/v1.0.1

Alex
