### ISSUE TITLE
app install commands need to use StreamStdio

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#138]
The `app install` commands need to use the `StreamStdio` with `ExecTask`, this is due to go-execute changing its behaviour in 0.3.0. 

If this change is not made, then all the output from the commands is hidden / quiet. 

For example:

https://github.com/alexellis/k3sup/blob/4f2b04cb317ce6840c8151fed56e0114979129b8/pkg/cmd/kubernetes_exec.go#L31

https://github.com/alexellis/go-execute/blob/961405ea754427780f2151adff607fa740d377f7/pkg/v1/exec.go#L19

**Comment by karuppiah7890** [comment]
@alexellis If the `StreamStdio` option is used, we don't need to use the result at the end and print it again, right?

**Comment by alexellis** [comment]
Two options:

1) Add `StreamStdio` and don't print anything after
2) Keep `StreamStdio` as false and then after stdout if exit code is 0, and print stderr if exit code is not zero.

I actually prefer option 2 now that you've mentioned this.

**Comment by alexellis** [comment]
@karuppiah7890 you'd said on Slack that you wanted to work on this, are you still able to pick it up, or should I find someone else?

**Comment by karuppiah7890** [comment]
You can find someone else 😄

**Comment by alexellis** [comment]
Ok, sorry that you couldn't take this as planned.

**Comment by nitishkumar71** [comment]
> Two options:
> 
>     1. Add `StreamStdio` and don't print anything after
> 
>     2. Keep `StreamStdio` as false and then after stdout if exit code is 0, and print stderr if exit code is not zero.
> 
> 
> I actually prefer option 2 now that you've mentioned this.

@alexellis can you please explain option2 again. Also, I can give it a try.
