### ISSUE TITLE
Add figlet ASCII logo

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#14]
## Description

We could make the `version` / help message look better than this:

![](https://pbs.twimg.com/media/ECUKAhaW4AALnjg?format=jpg&name=medium)

By including a figlet ASCII logo as per [faas-cli](https://github.com/openfaas/faas-cli/blob/master/commands/version.go#L159)

To generate a logo you can use the `figlet` package available on most Linux package managers and in the OpenFaaS function store.

**Comment by alexellis** [comment]
To make this easier for people:

```sh
docker run -ti functions/figlet figlet k3sup
```

^ that will generate a logo.

The link I included above was to the code where it's implemented in the faas-cli -> https://github.com/openfaas/faas-cli/blob/master/commands/version.go#L159

This approach can be copied.

**Comment by alexellis** [comment]
Two of examples of how it should look:

<img width="1546" alt="Screenshot 2019-08-19 at 09 01 57" src="https://user-images.githubusercontent.com/6358735/63248796-03eca480-c260-11e9-8f38-b8705bc009f3.png">
<img width="1546" alt="Screenshot 2019-08-19 at 09 01 48" src="https://user-images.githubusercontent.com/6358735/63248797-03eca480-c260-11e9-9ce0-7b4b89452e8e.png">


Show in two circumstances (only):

1) `k3sup` with no parameters
2) `k3sup version`

Also test that it's not shown otherwise i.e. with `k3sup install`

**Comment by utsavanand2** [comment]
I'll do! :)

**Comment by alexellis** [comment]
Thank you @utsavanand2

**Comment by alexellis** [comment]
@utsavanand2 let me know when you have a PR ready?

**Comment by utsavanand2** [comment]
@alexellis Sure!
