### ISSUE TITLE
[Feature] Add custom string array --set parameter to openfaas app

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#140]
Add custom string array --set parameter to openfaas app

## Expected Behaviour

We should be able to pass in custom overrides such as `--set gateway.image=myname/gateway:mydevversion`

## Current Behaviour

Just the hard-coded flags are supported

## Possible Solution

Add the string array cobra flag to the openfaas app code, then pass the custom set / overrides through to the deployment command. Give the `--set` overrides top priority.

https://github.com/alexellis/k3sup/blob/master/pkg/cmd/openfaas_app.go

https://github.com/alexellis/k3sup/blob/master/pkg/cmd/openfaas_app.go#L143

**Comment by prateekgogia** [comment]
I can take it, feel free to assign me this.

**Comment by alexellis** [comment]
No need to assign it, how many days do you think you'll need?

**Comment by prateekgogia** [comment]
Hi, Please let me know if what I have in the linked PR was to be done for this issue, feedback welcome.
