### ISSUE TITLE
[Feature] Maesh app

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#147]
## Task

Add app for maesh, which is a service mesh

https://github.com/containous/maesh#install-helm-v2-only

Docs:

https://docs.mae.sh

**Comment by utsavanand2** [comment]
Derek assign: me

**Comment by alexellis** [comment]
As per comment on #146, I've pinged @emilevauge about this one over email to see if we can collaborate with containous on the app.

**Comment by alexellis** [comment]
Closing due to lack of interest from community.
