### ISSUE TITLE
[Feature] Add Crossplane app

### ISSUE THREAD

**Issue by hasheddan** [alexellis/k3sup#156]
It would be great to be able to install [Crossplane](https://github.com/crossplaneio/crossplane) with `k3sup install app crossplane`. 

https://github.com/crossplaneio/crossplane/tree/master/cluster/charts/crossplane

Happy to do this work if approved by maintainers!

/cc @alexellis

**Comment by alexellis** [comment]
I think it could be a good addition if you want to start your PR, would you be able to reference the k3sup app installation method from the crossplane docs?

**Comment by hasheddan** [comment]
Likely so, I'll check to make sure.
