### ISSUE TITLE
[Feature Request] Add support for Docker instead of Containerd

### ISSUE THREAD

**Issue by farfeduc** [alexellis/k3sup#16]
## Current Behaviour
Currently there is no flag available in the install command to use Docker instead of Containerd.

## Possible Solution
Could we add an environment variable or a flag in the install command to support this feature ? Technically we might just need to add a `--docker` flag to the install command here if the user wants to use Docker: [install.go](https://github.com/alexellis/k3sup/blob/master/pkg/cmd/install.go#L69)

I would greatly appreciate this feature. I can try a Pull Request if you want.

Thanks

**Comment by alexellis** [comment]
Is that a feature in k3s, to use docker instead of containerd?

**Comment by farfeduc** [comment]
> Is that a feature in k3s, to use docker instead of containerd?

Yes, K3S proposes during installation to use Docker instead of containerd with the `--docker` flag which is available for both the server and the agents.

Check here for more information : [Official Doc Website](https://rancher.com/docs/k3s/latest/en/installation/#server-options)

**Comment by alexellis** [comment]
I would be happy to accept a patch for this 👍 

Do you want to work on it?

Alex

**Comment by farfeduc** [comment]
I do not know if I have done things properly but here is a Pull-Request : #19
