### ISSUE TITLE
[Documentation] Upgrading k3s master and workers to newer versions of k3s

### ISSUE THREAD

**Issue by onedr0p** [alexellis/k3sup#161]
Rancher has provided documentation on upgrading k3s, does k3sup allow for this? And if so, could it be documented in the README?

https://rancher.com/docs/k3s/latest/en/upgrades/

Thanks!

**Comment by xMordax** [comment]
Closing since its a duplicate: https://github.com/alexellis/k3sup/issues/161

**Comment by alexellis** [comment]
I can't really see any differences there between upgrade and running the install for second time. Can you help me out @onedr0p ?

**Comment by onedr0p** [comment]
@alexellis that is all that is required, I tried it out on the last k3s update. Maybe mention that link, or provide some literature in the README on upgrading?

**Comment by kyounger** [comment]
Yeah, can confirm, just re-running the same commands that you used to install will "upgrade". 

e.g., this is mine:

```
k3sup install --ip 10.10.9.4 --user pi
k3sup join --user pi --ip 10.10.9.3 --server-user pi --server-ip 10.10.9.4
k3sup join --user pi --ip 10.10.9.6 --server-user pi --server-ip 10.10.9.4
k3sup join --user pi --ip 10.10.9.9 --server-user pi --server-ip 10.10.9.4
```

I just run that once in a while. That will upgrade the master node first, and then each worker node. If you needed to be careful with how you cycle nodes (for application uptime purposes), you just need to handle that between each `join` command.

**Comment by kevinelliott** [comment]
Running this I notice we're still on v1.17.* ... how do we use this to get to v1.18, v1.19, or v1.20?

**Comment by isavcic** [comment]
@kevinelliott https://github.com/alexellis/k3sup#-setup-a-kubernetes-server-with-k3sup there is the version option, does that work?
