### ISSUE TITLE
Offer to download kubectl / faas-cli in 

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#163]
Just like we can download helm, for ofc-bootstrap and for k3sup users, it would be ideal to get a pinned, CPU and OS-specific version of kubectl and faas-cli via a package.

Example:

https://github.com/alexellis/k3sup/tree/master/pkg/helm

Given kubectl and faas-cli don't fit in the helm package, let's call it tools?

**Comment by alexellis** [comment]
We could use the same approach for downloading helm here, except these two tools don't need an untar at present.

**Comment by alexellis** [comment]
Please add helm2 and helm3 as download commands.

How should this look as a command?

```
k3sup download kubectl
k3sup download faas-cli
k3sup download helm
```

Etc?

**Comment by Waterdrips** [comment]
I went with `k3sup tool download [helm2,helm3,kubectl,faas-cli]`

Can be changed v easily to suit.

Im almost there with this code.

**Comment by alexellis** [comment]
This has moved over to arkade, which now has 1-2 dozen Kubernetes-type CLIs via `arkade get`

https://github.com/alexellis/arkade
