### ISSUE TITLE
[Feature] Install k3s v1.17.2+k3s1 by default

### ISSUE THREAD

**Issue by elmariofredo** [alexellis/k3sup#167]
Install k3s [v1.17.2+k3s1](https://github.com/rancher/k3s/releases/tag/v1.17.2%2Bk3s1) by default instead of v1.0.1 to resolve https://github.com/rancher/k3s/issues/1115#issuecomment-569509474

**Comment by alexellis** [comment]
Hi @elmariofredo, can we say that this version fixes the multi-master dqlite issue logged with Rancher for Raspberry Pi? cc @davidnuzik

**Comment by davidnuzik** [comment]
Hello @alexellis we are going to execute some tests after some current high priority items we have on our plate (see https://github.com/rancher/k3s/issues/1115#issuecomment-580885131) to see if its fixed. Note, DQLite is still experimental we will try to look into as soon as we are able to do so.

**Comment by elmariofredo** [comment]
Actually I was able to build cluster without error, but after some time it broke down and since then I'm unable to build it in HA mode again. Seems that on init master node is trying to reach other nodes which are wiped even after running uninstall script.

@davidnuzik let me know if I can help you with this issue.
