### ISSUE TITLE
Not able to install mongodb via k3sup

### ISSUE THREAD

**Issue by Mobilpadde** [alexellis/k3sup#170]
## Expected Behaviour

Should install mongodb

## Current Behaviour

Fails with current output

```
k3sup app install mongodb
Using kubeconfig: ./kubeconfig
x86_64
Linux
Client: "x86_64", "Linux"
2020/01/28 21:48:06 User dir established as: /home/avl/.k3sup/
"stable" has been added to your repositories
VALUES values.yaml
Command: /home/avl/.k3sup/bin/helm3/helm [upgrade --install mongodb stable/mongodb --namespace default --values /tmp/charts/mongodb/values.yaml]
W0128 21:48:09.849548    5735 loader.go:223] Config not found: ./kubeconfig
Error: UPGRADE FAILED: query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/default/secrets?labelSelector=name%3Dmongodb%2Cowner%3Dhelm%2Cstatus%3Ddeployed: dial tcp [::1]:8080: connect: connection refused
Error: unable to mongodb chart with helm exit code 1, stderr: W0128 21:48:09.849548    5735 loader.go:223] Config not found: ./kubeconfig
Error: UPGRADE FAILED: query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/default/secrets?labelSelector=name%3Dmongodb%2Cowner%3Dhelm%2Cstatus%3Ddeployed: dial tcp [::1]:8080: connect: connection refused
```

## Steps to Reproduce (for bugs)

1.  k3sup app install mongodb

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
Using k3s on an Ubuntu 18.04 hosted by [contabo.com](https://contabo.com/?show=configurator&vserver_id=221)

* Operating System and version (e.g. Linux, Windows, MacOS):
My local OS is Manjaro Linux using k3sup v. 0.8.0

**Comment by burtonr** [comment]
Could you please provide some more information?

What is the output?

What do you see or experience that you think you are "not able to install"?

What version of k3sup are you using?

Where is the destination server hosted? Spare PC, AWS, GCP, etc...?

**Comment by Mobilpadde** [comment]
> Could you please provide some more information?
> 
> What is the output?
> 
> What do you see or experience that you think you are "not able to install"?
> 
> What version of k3sup are you using?
> 
> Where is the destination server hosted? Spare PC, AWS, GCP, etc...?

Whoops, sorry!  Please checkout the updated question.

**Comment by alexellis** [comment]
I think it's to do with your KUBECONFIG env-var, or some other override you're setting.

```
Using kubeconfig: ./kubeconfig
```

**Comment by alexellis** [comment]
Maybe your kubeconfig isn't set up right?

Does this work?

```
kubectl get node
```


What about this instead?
```
export KUBECONFIG=`pwd`
```

**Comment by Mobilpadde** [comment]
> Maybe your kubeconfig isn't set up right?
> 
> Does this work?
> 
> ```
> kubectl get node
> ```
> 
> What about this instead?
> 
> ```
> export KUBECONFIG=`pwd`
> ```

Yes, I'm able to use `kubectl get node` :/

**Comment by alexellis** [comment]
Try the second command I gave you and run the k3sup command again.

It would be nice to have complete steps as I've been using k3sup today with KinD without issue.

Here's the same with k3d:

```
k3d create
INFO[0000] Created cluster network with ID 7f2a15fdef32cc912efe3454f7b3573cfb00e568014b8ce0f77f51bd516aaf89 
INFO[0000] Created docker volume  k3d-k3s-default-images 
INFO[0000] Creating cluster [k3s-default]               
INFO[0000] Creating server using docker.io/rancher/k3s:v1.0.1... 
INFO[0000] SUCCESS: created cluster [k3s-default]       
INFO[0000] You can now use the cluster with:

export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
kubectl cluster-info 

[alex@nuc ~]$ export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"

[alex@nuc ~]$ curl -sSLf https://get.k3sup.dev | sudo sh
x86_64
Downloading package https://github.com/alexellis/k3sup/releases/download/0.8.0/k3sup as /tmp/k3sup
Download complete.

Running with sufficient permissions to attempt to move k3sup to /usr/local/bin
New version of k3sup installed to /usr/local/bin
 _    _____                 
| | _|___ / ___ _   _ _ __  
| |/ / |_ \/ __| | | | '_ \ 
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/ 
                     |_|    
Version: 0.8.0
Git Commit: 074ecf9ca249c3f2b130ab01191e69f105aa13ff
[alex@nuc ~]$ k3sup app install mongodb
Using kubeconfig: /home/alex/.config/k3d/k3s-default/kubeconfig.yaml
x86_64
Linux
Client: "x86_64", "Linux"
2020/01/28 21:23:17 User dir established as: /home/alex/.k3sup/
"stable" has been added to your repositories
VALUES values.yaml
Command: /home/alex/.k3sup/bin/helm3/helm [upgrade --install mongodb stable/mongodb --namespace default --values /tmp/charts/mongodb/values.yaml]
Release "mongodb" does not exist. Installing it now.
NAME: mongodb
LAST DEPLOYED: Tue Jan 28 21:23:26 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

MongoDB can be accessed via port 27017 on the following DNS name from within your cluster:

    mongodb.default.svc.cluster.local

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/mongodb 27017:27017 &
    mongo --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD
=======================================================================
=                  MongoDB has been installed.                        =
=======================================================================

Thanks for using k3sup!
```

**Comment by Mobilpadde** [comment]
> Try the second command I gave you and run the k3sup command again. I think your KUBECONFIG is set wrong, it needs to be a complete path, that's why I suggested using `pwd`.
> 
> It would be nice to have complete steps as I've been using k3sup today with KinD without issue.
> 
> Here's the same with k3d:
> 
> ```
> k3d create
> INFO[0000] Created cluster network with ID 7f2a15fdef32cc912efe3454f7b3573cfb00e568014b8ce0f77f51bd516aaf89 
> INFO[0000] Created docker volume  k3d-k3s-default-images 
> INFO[0000] Creating cluster [k3s-default]               
> INFO[0000] Creating server using docker.io/rancher/k3s:v1.0.1... 
> INFO[0000] SUCCESS: created cluster [k3s-default]       
> INFO[0000] You can now use the cluster with:
> 
> export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
> kubectl cluster-info 
> 
> [alex@nuc ~]$ export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
> 
> [alex@nuc ~]$ curl -sSLf https://get.k3sup.dev | sudo sh
> x86_64
> Downloading package https://github.com/alexellis/k3sup/releases/download/0.8.0/k3sup as /tmp/k3sup
> Download complete.
> 
> Running with sufficient permissions to attempt to move k3sup to /usr/local/bin
> New version of k3sup installed to /usr/local/bin
>  _    _____                 
> | | _|___ / ___ _   _ _ __  
> | |/ / |_ \/ __| | | | '_ \ 
> |   < ___) \__ \ |_| | |_) |
> |_|\_\____/|___/\__,_| .__/ 
>                      |_|    
> Version: 0.8.0
> Git Commit: 074ecf9ca249c3f2b130ab01191e69f105aa13ff
> [alex@nuc ~]$ k3sup app install mongodb
> Using kubeconfig: /home/alex/.config/k3d/k3s-default/kubeconfig.yaml
> x86_64
> Linux
> Client: "x86_64", "Linux"
> 2020/01/28 21:23:17 User dir established as: /home/alex/.k3sup/
> "stable" has been added to your repositories
> VALUES values.yaml
> Command: /home/alex/.k3sup/bin/helm3/helm [upgrade --install mongodb stable/mongodb --namespace default --values /tmp/charts/mongodb/values.yaml]
> Release "mongodb" does not exist. Installing it now.
> NAME: mongodb
> LAST DEPLOYED: Tue Jan 28 21:23:26 2020
> NAMESPACE: default
> STATUS: deployed
> REVISION: 1
> TEST SUITE: None
> NOTES:
> ** Please be patient while the chart is being deployed **
> 
> MongoDB can be accessed via port 27017 on the following DNS name from within your cluster:
> 
>     mongodb.default.svc.cluster.local
> 
> To get the root password run:
> 
>     export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
> 
> To connect to your database run the following command:
> 
>     kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
> 
> To connect to your database from outside the cluster execute the following commands:
> 
>     kubectl port-forward --namespace default svc/mongodb 27017:27017 &
>     mongo --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD
> =======================================================================
> =                  MongoDB has been installed.                        =
> =======================================================================
> 
> Thanks for using k3sup!
> ```

Thanks a lot! Seems to work by setting the absolute path, not the relative, is working!

**Comment by alexellis** [comment]
You should always use the whole path for KUBECONFIG. helm runs in a different folder which is why it didn't work.

**Comment by alexellis** [comment]
/set title: Support request for KUBECONFIG path
