### ISSUE TITLE
Potential issue with --ipsec flag

### ISSUE THREAD

**Issue by eleaner** [alexellis/k3sup#183]
running k3sup 
Version: 0.8.2
Git Commit: 6de447c5bfec9231bd773998fed0976237cc02a3
on mac

`k3sup install 
  --ipsec 
  --cluster 
  --user $USER 
  --sudo 
  --ssh-port 22222 
  --ip xxx.xxx.xxx.xxx`

it is parsed to
`ssh: curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server --cluster-init --tls-san xxx.xxx.xxx.xxx '--flannel-backend ipsec'' INSTALL_K3S_VERSION='v1.17.2+k3s1' sh -`

as you can see the part `--flannel-backend ipsec` is outside of inverted commas 

which results in 
`/usr/sbin/ipsec: unknown IPsec command `INSTALL_K3S_VERSION=v1.17.2+k3s1' (`ipsec --help' for list)
curl: (23) Failed writing body (2233 != 2759)
Error: Error received processing command: Process exited with status 2`

## Expected Behaviour
installs k3s

## Current Behaviour
does not install k3s

**Comment by alexellis** [comment]
Interesting, do you want to send a fix / PR? Is this in k3s or in k3sup?
