### ISSUE TITLE
Bug - validate that --project-id is given for Packet or GCE/GCP

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#186]
There was a bug that was found by Duffie @mauilion, we need to validate that --project-id is given for Packet or GCE/GCP.

## Expected Behaviour

If giving `--provider` for a provisioner that requires a project-id, we should throw an error if it's not provided.

## Current Behaviour

We don't and it installs then gives empty logs when reconciling.

## Workaround

`kubectl edit deploy/inlets-operator` and set it manually via a command-line flag

**Comment by utsavanand2** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I've sent a PR for this, but @utsavanand2 can you add a few unit tests please?

**Comment by utsavanand2** [comment]
@alexellis Sure I can add some unit tests here in k3sup for validation. I apologize for not being able to help you out early enough. Just got back!

**Comment by alexellis** [comment]
No problem. This seemed like it needed sorting out before it left a bad impression on the project.

**Comment by alexellis** [comment]
I know you're looking at other things too.

**Comment by utsavanand2** [comment]
PR #214 should close this issue 
cc @alexellis
