### ISSUE TITLE
Issue running k3sup for inlets-operator with EC2 provider

### ISSUE THREAD

**Issue by retgits** [alexellis/k3sup#194]
## Current Behaviour

I tried installing the `inlets-operator` using k3sup with EC2 being the provider for it. The command I ran was 

```bash
k3sup app install inlets-operator \
 --helm3 \
 --provider ec2 \
 --region us-west-2 \
 --zone us-west-2a \
 --license $LICENSE \
 --token-file /Users/lstigter/.aws/credentials \
 --set=access-key=$AWS_ACCESS_KEY_ID secret-key=$AWS_SECRET_KEY
```

The issue is that k3sup asks for a Token File and doesn't seem to accept the access-key and secret-key.

## Possible Solution

I think adding `inletsOperator.Flags().String()` for both access-key and secret-key, and adding ec2 as a provider in `getInletsOperatorOverrides()` would solve this. Based on [this](https://github.com/inlets/inlets-operator/issues/54) it might also require an update in the inlets-operator Helm chart.

**Comment by alexellis** [comment]
This will be fixed in #211 cc @Waterdrips
