### ISSUE TITLE
Can not find tiller during app install of nginx-ingress

### ISSUE THREAD

**Issue by pisymbol** [alexellis/k3sup#195]
## Expected Behavior
Install of ingress-nginx

## Current Behaviour
$ k3sup app install nginx-ingress
Using kubeconfig: /home/pi/.kube/config
Using helm3
Client: armv7l, Linux
2020/02/14 08:13:02 User dir established as: /home/pi/.k3sup/
"stable" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
armNode architecture: "arm"
Chart path:  /tmp/charts
VALUES values.yaml
Command: /home/pi/.k3sup/bin/helm3/helm [upgrade --install nginx-ingress stable/nginx-ingress --namespace default --values /tmp/charts/nginx-ingress/values.yaml --set defaultBackend.enabled=false --set controller.image.repository=quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm]
Error: could not find tiller
Error: exit code 1, stderr: Error: could not find tiller

## Steps to Reproduce (for bugs)
1. k3sup install nginx-ingress

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

1.17.2

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/arm"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by alexellis** [comment]
This is odd because we don't even use tiller :-)

Btw if you're using RPi you can try K3d which comes with Traefik. 

@Waterdrips can you help please?

You might want to try the --helm3 flag too or rm -rf $HOME/.k3sup

**Comment by pisymbol** [comment]
```$ k3sup app install nginx-ingress --helm3
Using kubeconfig: /home/pi/.kube/config
Using helm3
Client: armv7l, Linux
2020/02/14 08:35:50 User dir established as: /home/pi/.k3sup/
https://get.helm.sh/helm-v2.16.0-linux-arm.tar.gz
/home/pi/.k3sup/bin/helm3/linux-arm linux-arm/
/home/pi/.k3sup/bin/helm3/README.md linux-arm/README.md
/home/pi/.k3sup/bin/helm3/helm linux-arm/helm
/home/pi/.k3sup/bin/helm3/LICENSE linux-arm/LICENSE
/home/pi/.k3sup/bin/helm3/tiller linux-arm/tiller
2020/02/14 08:37:56 extracted tarball into /home/pi/.k3sup/bin/helm3: 4 files, 0 dirs (2m5.181341117s)
Error: Couldn't load repositories file (/home/pi/.k3sup/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: exit code 1```

**Comment by Waterdrips** [comment]
Whats the output of `~/.k3sup/bin/helm3/helm version` - I wonder if it downloaded the wrong version into that folder, and now it's cached it wont re-download

**Comment by pisymbol** [comment]
> Whats the output of `~/.k3sup/bin/helm3/helm version` - I wonder if it downloaded the wrong version into that folder, and now it's cached it wont re-download

That is exactly the problem:

$ /home/pi/.k3sup/bin/helm3/helm version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Error: could not find tiller

**Comment by Waterdrips** [comment]
ok - delete that folder (.k3sup/bin/helm3) and try again?

**Comment by pisymbol** [comment]
k3sup has a bug:

$ k3sup app install nginx-ingress --helm3
Using kubeconfig: /home/pi/.kube/config
Using helm3
Client: armv7l, Linux
2020/02/14 08:45:56 User dir established as: /home/pi/.k3sup/
**https://get.helm.sh/helm-v2.16.0-linux-arm.tar.gz**
/home/pi/.k3sup/bin/helm3/linux-arm linux-arm/
/home/pi/.k3sup/bin/helm3/README.md linux-arm/README.md
/home/pi/.k3sup/bin/helm3/helm linux-arm/helm
/home/pi/.k3sup/bin/helm3/LICENSE linux-arm/LICENSE
/home/pi/.k3sup/bin/helm3/tiller linux-arm/tiller

**Comment by pisymbol** [comment]
Let me know when you have a fix! :-)

**Comment by alexellis** [comment]
Alistair saw something similar with an app he wrote the other day. There's an environment variable we should be setting or something like that. In any case tiller is never used, we have no code that can use it.

You can try removing that folder and running --helm3=false

**Comment by Waterdrips** [comment]
as a workaround you could set the env var "HELM_VERSION" to "v3.0.2"

**Comment by pisymbol** [comment]
```
func DownloadHelm(userPath, clientArch, clientOS, subdir string) error {
	useHelmVersion := helmVersion
	if val, ok := os.LookupEnv("HELM_VERSION"); ok && len(val) > 0 {
		useHelmVersion = val
	}
```

helmVersion is statically set.

**Comment by pisymbol** [comment]
Trying that now @Waterdrips

**Comment by pisymbol** [comment]
```
$ HELM_VERSION="v3.0.2" k3sup app install nginx-ingress --helm3
Using kubeconfig: /home/pi/.kube/config
Using helm3
Client: armv7l, Linux
2020/02/14 08:52:19 User dir established as: /home/pi/.k3sup/
https://get.helm.sh/helm-v3.0.2-linux-arm.tar.gz
/home/pi/.k3sup/bin/helm3/linux-arm linux-arm/
/home/pi/.k3sup/bin/helm3/README.md linux-arm/README.md
/home/pi/.k3sup/bin/helm3/LICENSE linux-arm/LICENSE
/home/pi/.k3sup/bin/helm3/helm linux-arm/helm
...
```

That works at least getting it to download helm3. You need to fix the --helm3 parameter to actually set the helmVersion me thinks.

**Comment by pisymbol** [comment]
Success. Though I kinda like it in nginx-ingress namespace. Does k3sup support that?

**Comment by Waterdrips** [comment]
hmm not at the moment

```

if namespace != "default" {
	return fmt.Errorf(`to override the "default", install via tiller`)
}

```

**Comment by pisymbol** [comment]
That should also be added since I think it would be fairly trivial to support. Just a suggestion.

**Comment by pisymbol** [comment]
Btw, never got a Slack invite which is why I'm here!

**Comment by Waterdrips** [comment]
> That should also be added since I think it would be fairly trivial to support. Just a suggestion.

If you are interested in this can you raise a new issue for it?

**Comment by pisymbol** [comment]
#197 filed.
