### ISSUE TITLE
[Feature] Add non-ssh option for cloud-init/local use 

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#2]
The output to STDIO will be captured in the `cloudinit` logs if used when provisioning a new VM.

Add an option to go "quiet" and to run local commands instead of `ssh` for this use case.

The user would then connect from his or her laptop using the `--skip-install` command to bring back a local kubeconfig file.

**Comment by alexellis** [comment]
Here is an example of where the manual steps I needed for `cloudinit` can be replaced by a "local" execution instead of `ssh` to achieve the same thing.

https://github.com/openfaas-incubator/workshop-vscode/blob/master/cloudinit.txt

**Comment by utsavanand2** [comment]
derek assign: me

**Comment by utsavanand2** [comment]
@alexellis can you provide some more detail please? I'm willing to assist.
Do we want to install k3s with cloud-init?

**Comment by alexellis** [comment]
Hi @utsavanand2 

The idea would be that cloud-init allows a user to run some arbitrary commands at start-up.

Instead of running `ssh` to a remote host, using cloudinit would run the command as a local install.

It would be like replacing the `ssh` step for a simple `exec`, when we know we're running on cloudinit and not on a laptop.

**Comment by utsavanand2** [comment]
@alexellis I would like to take this on. Could you please assign me to fix this issue?

**Comment by utsavanand2** [comment]
Derek assign: me

**Comment by blaise-sumo** [comment]
I wonder if this would help me because when I try to join my home server to
my K3s cluster on DO, all I get back from k3sup is the server token.
I thought it might be because the name of my admin account and ssh key is
different but I tried all the permutations.

When I don't have the correct K3s server creds, I get an error message
immediately.
When I use the correct K3s creds, I eventually get a server token and the
end of K3sup.

**Comment by alexellis** [comment]
If you want to connect RPi + a host on the Internet, that's a different matter, you'll need to create a VPN for it.

This issue is about running k3sup locally instead of via ssh.

**Comment by alexellis** [comment]
@OmegaSquad82 you may have a good idea there, but first of all let's get local install working w/o `ssh` for the single-node/testing scenario?
