### ISSUE TITLE
[Feature] ability to pass k3s install options

### ISSUE THREAD

**Issue by billimek** [alexellis/k3sup#21]
## Expected Behaviour
As a user of k3sup,
I want to be able to specify additional k3s install options (such as `--no-deploy`, `--node-taint`, etc),
So that I can continue to leverage k3sup but have some control over the way k3s is installed or joined

## Current Behaviour
Currently k3sup only has [one hard-coded way](https://github.com/alexellis/k3sup/blob/ac059b635fafc7e03ee8eab6e8bfcb450b5ec0ac/pkg/cmd/install.go#L86) (except IP address) to install ([or join](https://github.com/alexellis/k3sup/blob/ac059b635fafc7e03ee8eab6e8bfcb450b5ec0ac/pkg/cmd/join.go#L139)) k3s

## Possible Solution
Allow for passing various 'k3s' install options from the k3sup install/join CLI

## Context
See [k3s install configuration options](https://rancher.com/docs/k3s/latest/en/configuration/)

**Comment by alexellis** [comment]
At this stage, I'm in favour of the less is more mindset and convention over configuration.

We could include all options, but I don't think that we should until each one is requested and contributed by actual users.

Which specific options do you want? I can see that `--docker` has a PR here for instance: #19

**Comment by billimek** [comment]
Hi @alexellis, in the spirit of keeping `k3sup` simplified (which is a good idea IMO),

How about an implementation that allows for an _k3s extra options_ environment variable or additional flag to `k3sup`?  Maybe something like this:

**environment variable approach:**

```shell
export K3S_EXTRA_ARGS="--no-deploy <some thing> --docker <some thing>, etc"
export IP="<some IP>"
k3sup install --ip $IP --user ubuntu
```

In this scenario, we simply pass along whatever is populated in `$K3S_EXTRA_ARGS` to the k3s curl command

---

**extra k3sup argument approach:**

```shell
export IP="<some IP>"
k3sup install --ip $IP --user ubuntu --k3s-extra-args="--no-deploy <some thing> --docker <some thing>, etc"
```

Either approach keeps the number of arguments for `k3sup` small and simple but still gives users the _option_ to include additional flags for k3s in a more dynamic fashion, especially when k3s iterates to include additional installation options.  This would also solve for #19.

If this approach is something you're willing to accept, I'm very happy to PR something to do this.

**Comment by alexellis** [comment]
I am not keen on the loosely-typed approach, I think I would prefer to mirror the flags of `k3s` on a case-by-case basis.

Which do you absolutely need?

That said, I am still thinking about your suggestion.

**Comment by alexellis** [comment]
I've gone ahead with the merge and I've released a new binary to unblock you, but I'd like to explore the UX a bit more and think about adding strongly typed flags for the most common options like `--docker`.

You're also welcome on Slack https://slack.openfaas.io/ k3sup is discussed in #teamserverless-dev and #general
