### ISSUE TITLE
Grafana App with cluster metrics scraping

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/k3sup#210]
We could add an app that install grafana and scraped cluster metrics (etc) 

It depends on Prometheus being deployed, so we might want a user to pass in some of the info about the Prometheus installation?

Something like this could be used: https://grafana.com/grafana/dashboards/315

We might optionally want grafana-ingress setup, if the dashboard can be configured with decent authentication.

## Expected Behaviour

A dashboard, and optionally ingress 
## Current Behaviour

no app
## Possible Solution

https://grafana.com/grafana/dashboards/315
https://grafana.com/grafana/plugins/grafana-kubernetes-app
https://medium.com/@chris_linguine/how-to-monitor-your-kubernetes-cluster-with-prometheus-and-grafana-2d5704187fc8

**Comment by alexellis** [comment]
Closed by https://github.com/alexellis/arkade/issues/6
