### ISSUE TITLE
How to uninstall k3s?

### ISSUE THREAD

**Issue by avarf** [alexellis/k3sup#215]
Hi, I set up a K8s cluster using k3sup and everything is good and working. Now I need to remove it but I couldn't find any command to delete/tear down the cluster. How I can tear down the cluster? Shall I use the commnads for the [normal K8s](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tear-down)?

**Comment by alexellis** [comment]
Please use Slack for technical support #k3sup channel

https://slack.openfaas.io
