### ISSUE TITLE
Broken Installer

### ISSUE THREAD

**Issue by tomingoglia** [alexellis/k3sup#218]
On the latest release you are using grep Location to get the version. I think it needs to be grep location...lower case.

version=$(curl -sI https://github.com/$OWNER/$REPO/releases/latest | grep **Location** | awk -F"/" '{ printf "%s", $NF }' | tr -d '\r')

version=$(curl -sI https://github.com/$OWNER/$REPO/releases/latest | grep **location** | awk -F"/" '{ printf "%s", $NF }' | tr -d '\r')

I think this is the same problem in the ark project too.

**Comment by Waterdrips** [comment]
/close

Hi @tomingoglia, Thanks for reporting, I have been through all of the repos and updated to a case insensitive grep. 
 :tada: Let us know if you have any other issues

**Comment by alexellis** [comment]
That was very fast @Waterdrips, thank you 👍
