### ISSUE TITLE
k3sup assumes and switches to the pulled kubeconfig which has the default context

### ISSUE THREAD

**Issue by utsavanand2** [alexellis/k3sup#22]
## Expected Behaviour
The switching of contexts should be something that should be left upon the user to decide?
It should not be automatic and be changed everytime the user creates a new k3s cluster.
Your thoughts?

## Current Behaviour
As discussed [here](https://github.com/alexellis/k3sup/pull/4#discussion_r316584999) with @alexellis the latest commit assumes that the pulled config has the 'default' context. But this switching of contexts can cause kubectl to have two default contexts (if there is an existing default context)

## Possible Solution
Omit the code section that switches the context to 'default'.

**Comment by alexellis** [comment]
Have you got an ETA so that I can coordinate a release?

**Comment by utsavanand2** [comment]
@alexellis I can do it in an hour. Just wanted to make sure with you if we want to completely remove the context switching feature?

**Comment by alexellis** [comment]
Yes to prevent surprises, then let's review it properly after.
