### ISSUE TITLE
k3s is now on version v1.17.3+k3s1

### ISSUE THREAD

**Issue by utf18** [alexellis/k3sup#222]
k3s updated its version v1.17.3+k3s1 from v1.17.2+k3s1

## Context

i installed k3s earlier and noticed a new version came out, i would have send a PR with the updated config.go file, but i am unsure about your tests for newer version of k3s.
https://github.com/alexellis/k3sup/blob/master/pkg/config/config.go#L10

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?
k3sup is in version 0.9.1
Git Commit: 6645e9b9f489be239b38f3478761115533420360

**Comment by orefalo** [comment]
I used the version flag to force it.

**Comment by alexellis** [comment]
That's why we have the version flag, is it clear enough in the README do we feel?

I'd be happy to take a PR, if someone can confirm the new version is fully working on RPi.

**Comment by orefalo** [comment]
So far so good, but it needs more testing.

**Comment by utf18** [comment]
Do you want to keep this issue open for tracking? otherwise feel free to close it 👍 
Thank you all for your work 🦄

**Comment by alexellis** [comment]
I'd like to see someone test it out on an RPi cluster with:

1 server
1 server, multiple agents
> 1 server & multiple agents

That would be enough I think to merge.

**Comment by moritz31** [comment]
There are now release channels: https://rancher.com/docs/k3s/latest/en/upgrades/basic/
I think this would be a cool addition to just default to the stable release channel and additionally you can specify a version which then overwrites the channel

**Comment by alexellis** [comment]
Happy to take a PR to be able to substitute `INSTALL_K3S_VERSION` with `INSTALL_K3S_CHANNEL`.
