### ISSUE TITLE
installing linkerd: no clock skew detected

### ISSUE THREAD

**Issue by orefalo** [alexellis/k3sup#223]
So I don't think the issue is directly related to k3sup, but a small change can definitely help.

I setup my cluster on Hetzner, installed openfaas and Linkerd.

Linkerd typically runs a pre-check which fails with this error:
_"no clock skew detected"_ , seems to be a clock sync issue.

To fix it, I typically ssh into the node, run **timedatectl set-ntp true**, and reboot the machine.

upon reboot, the precheck passes

Now, if this command could be run prior to installing k3s, I am pretty sure the problem would be gone.

**Comment by alexellis** [comment]
"k3sup app install" has moved to arkade -> https://get-arkade.dev/ - feel free to raise an issue over there if there's ongoing issues.
