### ISSUE TITLE
Duplicate Hostnames

### ISSUE THREAD

**Issue by BChip** [alexellis/k3sup#233]
When installing raspbian lite, the default hostname is raspberrypi. When building up a multi-node raspberry pi kubernetes cluster, this is an issue. If you install one pi as the server and join another pi with the same hostname, you will not see that joined pi when running `kubectl get node`.

## Expected Behaviour

```
bchip@DESKTOP-2F6P54M:~$ kubectl get node -o wide
NAME                STATUS   ROLES    AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
raspberrypislave3   Ready    <none>   10m   v1.17.2+k3s1   192.168.50.64    <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7+      containerd://1.3.3-k3s1
raspberrypi         Ready    master   28m   v1.17.2+k3s1   192.168.50.162   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7l+     containerd://1.3.3-k3s1
raspberrypislave2   Ready    <none>   22m   v1.17.2+k3s1   192.168.50.93    <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7+      containerd://1.3.3-k3s1
raspberrypislave1   Ready    <none>   25m   v1.17.2+k3s1   192.168.50.134   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7+      containerd://1.3.3-k3s1
```

## Current Behaviour

```
bchip@DESKTOP-2F6P54M:~$ kubectl get node -o wide
NAME                STATUS   ROLES    AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION   CONTAINER-RUNTIME
raspberrypi         Ready    master   28m   v1.17.2+k3s1   192.168.50.162   <none>        Raspbian GNU/Linux 10 (buster)   4.19.97-v7l+     containerd://1.3.3-k3s1
```

## Possible Solution

Easy solution: Some where in the README, add a note stating the hostname on each device cannot be the same. 

Cool solution: When performing a join on a node, could you check the hostname of the server and the agent joining and make sure it doesn't match? It could warn the user, fail the install, or etc...

## Steps to Reproduce (for bugs)

1. Grab 2 Pis
2. Install Raspbian Lite on each
3. `k3sup install --ip $PI1 --user pi`
4. `k3sup join --ip $PI2 --server-ip $PI1 --user pi`
5. `kubectl get node -o wide`

## Context

I followed the readme to get my pi cluster up and running. I had the hostname the same on all the pi's. Went through the process and noticed kubectl said there was only one node up and ready.

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:07:30Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/arm"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Ubuntu 18
```

**Comment by alexellis** [comment]
I don't think that setting hostnames is part of the remit for k3sup. When I build clusters, I set the hostname of each node when preparing its SD card or after first boot, with Ubuntu you can even use cloud-init to do this. Setting hostnames is a reasonable expectation for setting up nodes, closing the issue.
