### ISSUE TITLE
Hardening node

### ISSUE THREAD

**Issue by orefalo** [alexellis/k3sup#234]
Based on https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/

k3sup install should:

file /etc/sysctl.d/90-kubelet.conf:
```
vm.overcommit_memory=1
vm.panic_on_oom=0
kernel.panic=10
kernel.panic_on_oops=1
kernel.keys.root_maxbytes=25000000
```

then run `sysctl -p /etc/sysctl.d/90-kubelet.conf` to activate the setting.

The rest of the documents, if more of a post install checklist

**Comment by alexellis** [comment]
k3sup is a k3s installer, so this seems out of scope for k3sup. I do think it may be useful however, so I would ask you to raise an issue with the Rancher folks on the k3s repo. Ask them to make it part of the installer, then we can reference that via an additional flag.

**Comment by alexellis** [comment]
k3s repo -> https://github.com/rancher/k3s/issues

**Comment by alexellis** [comment]
/set title: Feature request to apply Rancher's Hardening Guide
