### ISSUE TITLE
Support INSTALL_K3S_CHANNEL as a flag

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#237]
`INSTALL_K3S_CHANNEL` can now be used to specify a tag instead 
of a specific version. Some users may want this behaviour.

https://rancher.com/docs/k3s/latest/en/upgrades/basic/

## Expected Behaviour

```
k3sup install --channel=stable
k3sup install --channel=latest
```

## Current Behaviour

Only a specific version can be given, or the default

## Possible Solution

Add a new flag for `--channel` which should have validation and be 
mutually exclusive with the version flag. Do not supply a default for 
channel, but show the options in the `--help` message.

**Comment by kateGlebova** [comment]
I'd like to take this on if that's alright

**Comment by moritz31** [comment]
Hey alexellis, i thought it would be more convenient to default to --channel stable instead of a version

**Comment by moritz31** [comment]
Hey @alexellis did you look over my pr? If you want me to change the behaviour like you described, feel free to ask me to change this.

**Comment by alexellis** [comment]
Thanks for the PR, it's on my list.
