### ISSUE TITLE
Support request for Traefik2

### ISSUE THREAD

**Issue by chriskinsman** [alexellis/k3sup#243]
## Expected Behaviour
Expect that all IngressRoute CRDs would be installed

## Current Behaviour
Not installed

## Possible Solution
Install and update ClusterRole to have access

## Steps to Reproduce (for bugs)
1. Base k3sup install
2.
3.
4.

## Context
Trying to setup IngressRouteTCP but have to install the CRDs and update the roles to get there

## Your Environment
Raspbian Buster Pi 3B+

* What Kubernetes distribution are you using (for `k3sup app`)?
???  Tells me to run arkade app which gives an error

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:07:30Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/arm"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Raspbian Buster on Pi 3B+

**Comment by alexellis** [comment]
Hi,

Thanks for using arkade.

Can you give the full output please? :-)

and `kubectl get crd` too

Alex

**Comment by alexellis** [comment]
@Waterdrips do you have time to try this out and verify if the CRDs are installed? And whether the Traefik team changed how their chart worked?

**Comment by chriskinsman** [comment]
I have manually installed the CRDs at this point in an attempt to get this working.  Going to read through the code to see how you are installing the charts.

Are the CRDs a Traefik2 thing instead of 1.7?  Not super familiar with traffic but trying to figure out how to route TCP requests in bound and looks like I need IngressRouteTCP which isn't in place with the k3sup install I did.

**Comment by alexellis** [comment]
So if you had an error, and you're using k3s, then that's because k3s ships with Traefik 1 built-in. Delete your cluster and install it again with `k3sup install --no-extras` or just pass the argument to disable Traefik 1.

We do have this documented.

**Comment by alexellis** [comment]
Fairly sure we have found the source of the problem here so I'll close out, but please feel free to join Slack and get technical support there from the community. If we have a confirmed issue with arkade, I'll re-open the issue and we'll look into a fix.

**Comment by alexellis** [comment]
See how @Waterdrips uses `--no-extras` in this blog post -> https://www.openfaas.com/blog/cloud-native-tools-webinar/

**Comment by alexellis** [comment]
Also, this appears to be in the wrong repo - any issues about arkade apps like traefik2 should be directed there. I'll move the issue across.

https://slack.openfaas.io/
