### ISSUE TITLE
Certain combinations of flags need to be escaped

### ISSUE THREAD

**Issue by oskapt** [alexellis/k3sup#245]
I reinstalled a k3s cluster built with `--no-extras` and added `--k3s-extra-args="--flannel-backend=host-gw". The cluster failed to start.

I logged in and saw that the output of `ps` showed the following:
```
14760 ?        Ssl    0:40 /usr/local/bin/k3s server --cluster-init --tls-san 10.68.0.63 --flannel-backend=host-gw--no-deploy servicelb --no-deploy traefik
```

Note that there is no space between `host-gw` and `--no-deploy` for `servicelb`.

Full command to reproduce:

```
k3sup install --ip=10.68.0.63 --user=ubuntu --cluster --no-extras --k3s-extra-args="--flannel-backend=host-gw"
```

k3sup version: 0.9.2
k3s version: v1.17.2+k3s1

I resolved it by using `--no-deploy` options for traefik and servicelb instead of `--no-extras`.

**Comment by alexellis** [comment]
Hi @oskapt thanks for raising this issue.

Can you share the SSH command that is executed from the below?

```
k3sup install --ip=10.68.0.63 --user=ubuntu --cluster --no-extras --k3s-extra-args="--flannel-backend=host-gw"
```

I suspect this may need some additional embedded quotes in the string that is sent over SSH.

Alex

**Comment by alexellis** [comment]
/set title: Certain combinations of flags need to be escaped

**Comment by tetrash** [comment]
Hi 👋, I'd like to pick it up

**Comment by alexellis** [comment]
Please feel free to help us test out #272

**Comment by houshym** [comment]
I ran following command  and I got error  "Error: unknown flag: --no-extras"
k3sup join \
  --server \
  --ip $NODE_2 \
  --user $USER \
  --server-user $USER \
  --server-ip $NODE_1 \
  --no-extras
