### ISSUE TITLE
Customising the URL for fetching k3s

### ISSUE THREAD

**Issue by bahorn** [alexellis/k3sup#247]
When setting up several VMs on the same network, using a local mirror can massively speedup the setup time, which can be achieved by allowing a custom script to be used for installing k3s.

This relates to #231, but allows some more customization. 

## Expected Behaviour

An extra optional command line flag for specifying where to find the install script, so user customization can be made. (i.e changing the GITHUB_URL to a local mirror)

## Current Behaviour

Currently, the URL for the install script (`https://get.k3s.io/`) is hardcoded in various commands in `cmd/install.go` and `cmd/join.go`, which results in each node downloading their own copy from the internet.

## Possible Solution

I have a example implementation [here](https://github.com/bahorn/k3sup/commit/96bddb7376448098a1404bf14f57823fc0748775) where I added an command line option to specify it.

Otherwise it would be possible to send the script over the SSH session, but does involve added complexity.

Possibly worth supporting a checksum if people are going to curl from non-https resources.

## Context

I was setting up multiple nodes and each one had to download a copy of k3s from GitHub, which is currently 50MB, so even on a good connection it can slow down the install. By making slight modifications to the install script, I was able to point it to a local mirror and gain a massive speed boost.

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

Ubuntu 20.04 (cloud image), hosted locally with KVM.

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux yebes 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by alexellis** [comment]
How many machines are you provisioning, and how limited is your bandwidth that 50MB per node is noticeable?

**Comment by alexellis** [comment]
I think we need to look at the way Rancher suggest air-gapping, and perhaps give that as the solution?

**Comment by bahorn** [comment]
I was provisioning 4 machines on a 50Mbps connection. It's not crazy long, but I'm using it mostly a test cluster where I've been recreating a few times.

But looking into, the airgap install process would definitely be the better solution to this.

**Comment by Waterdrips** [comment]
Could SCPing the files from the provisioning machine be an option? (as part of k3sup, behind a flag)

**Comment by bahorn** [comment]
@Waterdrips 
That'd be how I'd do it. Main concern is it'd need an extra dependency for SCP, and I'm not sure which libraries are mature.

**Comment by alexellis** [comment]
I'm not sure this is a main-stream request, but am happy to monitor the thread for demand and reconsider the request in the future.

**Comment by aymond** [comment]
Such a feature would really help me out. 

There seems to be an issue in Germany with some ISPs having throttled or limited bandwidth for downloads from AWS S3 US Endpoints with pre-signed URLs. A download of the k3s binary may take 30-45 minutes, a pain if setting up a few machines in a cluster, or if something goes wrong and need to start over.

Example from browser based download below:

```
k3s-armhf
https://github-production-release-asset-2e65be.s3.amazonaws.com ...
35.7 KB/s - 31.9 MB of 49.4 MB, 8 mins left
```

**Comment by MrSimonEmms** [comment]
Posting here in effort to be helpful. You can always set envvars that cURL listens to. Officially cURL supports `http_proxy`, `HTTPS_PROXY` and `NO_PROXY` (see [docs](https://curl.se/docs/manual.html#environment-variables)). No idea why one is lowercase and other is uppercase, but I always set the upper and lower case values for safety.

I've got this script for my app (it uses Terraform to retrieve the proxy values)

```bash
ssh-keyscan "${SSH_ADDRESS}" >> ~/.ssh/known_hosts

# Remove old proxy settings
ssh "${USER}@${SSH_ADDRESS}" "sudo sed -i '/http_proxy=/d' /etc/environment"
ssh "${USER}@${SSH_ADDRESS}" "sudo sed -i '/HTTP_PROXY=/d' /etc/environment"
ssh "${USER}@${SSH_ADDRESS}" "sudo sed -i '/https_proxy=/d' /etc/environment"
ssh "${USER}@${SSH_ADDRESS}" "sudo sed -i '/HTTPS_PROXY=/d' /etc/environment"
ssh "${USER}@${SSH_ADDRESS}" "sudo sed -i '/NO_PROXY=/d' /etc/environment"

# Add new proxy settings
http_proxy="$(terraform output -json proxy_settings | jq -r '.http_proxy')"
if [ "${http_proxy}" != "null" ]; then
  ssh "${USER}@${SSH_ADDRESS}" "echo 'http_proxy=\"${http_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
  ssh "${USER}@${SSH_ADDRESS}" "echo 'HTTP_PROXY=\"${http_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
fi

https_proxy="$(terraform output -json proxy_settings | jq -r '.https_proxy')"
if [ "${https_proxy}" != "null" ]; then
  ssh "${USER}@${SSH_ADDRESS}" "echo 'https_proxy=\"${https_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
  ssh "${USER}@${SSH_ADDRESS}" "echo 'HTTPS_PROXY=\"${https_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
elif [ "${http_proxy}" != "null" ]; then
  ssh "${USER}@${SSH_ADDRESS}" "echo 'https_proxy=\"${http_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
  ssh "${USER}@${SSH_ADDRESS}" "echo 'HTTPS_PROXY=\"${http_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
fi

no_proxy="$(terraform output -json proxy_settings | jq -r '.no_proxy')"
if [ "${no_proxy}" != "null" ]; then
  ssh "${USER}@${SSH_ADDRESS}" "echo 'no_proxy=\"${no_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
  ssh "${USER}@${SSH_ADDRESS}" "echo 'NO_PROXY=\"${no_proxy}\"' | sudo tee -a /etc/environment > /dev/null"
fi
```

With these settings, I'm able to get k3sup running on a fully airgapped environment routed through a proxy server

**Comment by alexellis** [comment]
To use a HTTP proxy I would have just expected to have seen something much simpler like:

```bash
export HTTP_PROXY=http://127.0.0.1:3128
export HTTPS_PROXY=http://127.0.0.1:3128

k3sup install
```

But this doesn't necessarily help @aymond 

What would help him? Does somewhere in Europe mirror all of S3?

> I was setting up multiple nodes and each one had to download a copy of k3s from GitHub, which is currently 50MB, so even on a good connection it can slow down the install. By making slight modifications to the install script, I was able to point it to a local mirror and gain a massive speed boost.

I don't think it's worth the effort to mirror the K3s binary to save a few seconds or even a minute or two.

This seems more like it belongs to the roadmap for airgapping in K3sup Pro.
