### ISSUE TITLE
Feature request: Support for k3sup install against systems without bash

### ISSUE THREAD

**Issue by xnutsive** [alexellis/k3sup#258]
I was trying k3sup the other day, and ended up picking rancher/k3s-ansible. K3sup didn't work because of the way fish shell handles command substitutions. 

It's probably and easy fix, and I'd be down implementing it, if you think it's a good idea? WDYT @alexellis?

## Expected Behaviour
When someone is using fish and running k3sup, it should just work out of the box without any extra settings just for the sake of a different shell. 

## Current Behaviour
```
nate-mbp17:~ k3sup install --user pi --ip 192.168.86.116 --ssh-key ~/.ssh/id_rsa_2020
Running: k3sup install
Public IP: 192.168.86.116
ssh -i /Users/xnutsive/.ssh/id_rsa_2020 -p 22 pi@192.168.86.116
ssh: curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server  --tls-san 192.168.86.116 ' INSTALL_K3S_VERSION='v1.17.2+k3s1' sh -

fish: Unsupported use of '='. To run 'INSTALL_K3S_VERSION='v1.17.2+k3s1'' with a modified environment, please use 'env INSTALL_K3S_EXEC=server  --tls-san 192.168.86.116  INSTALL_K3S_VERSION='v1.17.2+k3s1'...'
curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server  --tls-san 192.168.86.116 ' INSTALL_K3S_VERSION='v1.17.2+k3s1' sh -
                               ^
Error: error received processing command: Process exited with status 127
nate-mbp17:~
```

## Possible Solution
K3sup could detect fish shell, and run a valid fish command with`env` instead: 

`env INSTALL_K3S_EXEC='server  --tls-san 192.168.86.116 ' INSTALL_K3S_VERSION='v1.17.2+k3s1' sh - ...`

## Your Environment

Mac OS 10.16 dev beta 2, fish shell.

Raspberry P4 4gb and 8gb  in the cluster, running May release of Rasbian OS 32bit, not that it's relevant to the issue.

**Comment by alexellis** [comment]
Hi are you saying that you installed fish shell for your user on your RPi?

**Comment by xnutsive** [comment]
/me looks around, embarassed

Yes.

I mean, another dummy-proof way of fixing this would be to `/usr/bin/bash -c "actual command"` — again, I'm down to look into it ;)

**Comment by alexellis** [comment]
This seems like an edge-case to me, if you'd told me k3sup wasn't working with Fish on your Mac or WSL2 client, I think it may be different, but generally RPis are throw-away when used with Kubernetes, since it's likely that they will need to be re-flashed. Users shouldn't really be logging in and making them into "pets" with lots of customisations.

If you want to try out passing `/usr/bin/bash -c` as a prefixed command in a fork, I don't mind, but don't see this as something that many users will run into (at the moment)

**Comment by alexellis** [comment]
/set title: Support for k3sup install against systems without bash

**Comment by alexellis** [comment]
/set title: Feature request: Support for k3sup install against systems without bash
