### ISSUE TITLE
[Feature Request] Air Gap support

### ISSUE THREAD

**Issue by ibuildthecloud** [alexellis/k3sup#26]
To run k3sup I need an internet connection to run the install script and download the k3s binary. I'd like to be able to run k3sup on a secure network not connected to the internet.

I'd like to be able to point k3sup to a mirror for the install script and binary.  There is a good chance the upstream k3s install script needs to change to support this.

Optionally if k3sup could run as a webserver or just scp the files that would be nice.

**Comment by alexellis** [comment]
Hi @ibuildthecloud this sounds useful for edge use within banking etc.

How much additional config is needed for k3s to run air-gapped? I assume the images that are pulled to run the control-plane would also need to be deployed to a private registry somewhere?

Alex

**Comment by xiaods** [comment]
i suggest provide some config to install airgap image through ssh way.

**Comment by alexellis** [comment]
Closing due to lack of interest from community and lack of input from original poster.

**Comment by ebartz** [comment]
I am currently running into this. The air gapped installation is quite simple and described here:

https://rancher.com/docs/k3s/latest/en/installation/airgap/

In such an environment I would like to hand over a link to an internal url, where it can download the k3s-airgap-images-$ARCH.tar.

**Comment by rhd** [comment]
I'd love to see airgap support as well!

**Comment by natanbs** [comment]
Following my discussion with @alexellis, the airgap feature would need to be sponsored in order to be completed.
If anyone needing the airgap solution for k3sup and is capable to help is more than welcomed ;-)

**Comment by alexellis** [comment]
@natanbs can you say more about your needs here?

**Comment by natanbs** [comment]
I am preparing an installation kit of a k3s cluster of three nodes with a private registry with no access to the internet.

I was trying to implement the k3s solution in k3sup but without success:

https://rancher.com/docs/k3s/latest/en/installation/airgap/?__hstc=45365755.73bd3bee6fa385653ecd7c9674ba06f0.1583366400106.1583366400107.1583366400108.1&__hssc=45365755.1.1583366400109&__hsfp=3969305255

I have copied the k3s airgap tar file to
/var/lib/rancher/k3s/agent/images/

Then tried to run the k3sup with the variables as documented in the link above:
INSTALL_K3S_SKIP_DOWNLOAD=true
K3S_URL=https://myserver:6443
K3S_TOKEN=mynodetoken

however it seems to ignore it and still downloads the k3s.
Couldn't find any suitable --k3s-extra-args parameters to use.

Would it be difficult to implement the k3s solution to k3sup?

**Comment by alexellis** [comment]
@natanbs The value for `K3S_URL` is probably hardcoded. Why don't you try changing that line in the code and see if it helps you?

**Comment by natanbs** [comment]
Oh, long time... thanks, but I have implemented my own method with Ansible.

**Comment by alexellis** [comment]
No problems.

If someone wants to fund my work on airgapped K3sup, they know how to reach me. My email's public :smile:
