### ISSUE TITLE
Feature Request: command to return version of k3s supported

### ISSUE THREAD

**Issue by anuaimi** [alexellis/k3sup#263]
I use k3sup to create k3s clusters.  These clusters are long living so they need to be upgraded periodically.  While it is easy to query a cluster to see what version it is based on, there is no easy way to know when k3sup supports a new version of k3s. It would be great to have a command that returns what version of k3s it installs.  It might be as simple as adding the k3s version to the output of `k3sup version`

## Expected Behaviour

k3sup version

 _    _____
| | _|___ / ___ _   _ _ __
| |/ / |_ \/ __| | | | '_ \
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/
                     |_|
Version: 0.9.6
Git Commit: b94b83b4b3fda86ac88c736f0d98218bfa3cb37b
k3s version: 1.18

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm creating a tool that sits on top of k3sup.  It will create the VMs (on a number of popular public clouds), run k3sup on each node.  It will also update k3sup and see if there is a new version of k3s.  If so, it will upgrade each of the clusters (using a rolling update).  

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
DO

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

```
uname -a

cat /etc/os-release
```

**Comment by alexellis** [comment]
Hi @anuaimi thank you for your interest in the project.

Have you thought about running `kubectl version` to see what version your cluster is running at?

How would you see your solution working? I noticed you didn't fill out "Possible Solution", would you mind doing so?

Alex
