### ISSUE TITLE
Feature Request: publish k3sup to home-brew

### ISSUE THREAD

**Issue by anuaimi** [alexellis/k3sup#264]
There is no easy way for code to know if there is a new version of k3sup.  If k3sup was installed with a package manager rather than using curl, it would be easy to see if there was a new version and get it.  

## Expected Behaviour

the only way to do keep k3sup up to date on a machine is to re-install it periodically and then check the version.   This is not very efficient.   It would be better to use something like brew (on Mac) as it would be easy to see if there was a new version

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

**Comment by amalkh5** [comment]
@anuaimi k3sup is now available in homebrew, check https://github.com/alexellis/homebrew-alexellis

**Comment by anuaimi** [comment]
awsome
