### ISSUE TITLE
have k3sup dynamically get latest version of k3s

### ISSUE THREAD

**Issue by anuaimi** [alexellis/k3sup#266]
rather than hard-coding the k3s version, k3sup should use the github api to query the k3s repo to get the latest version. it should then install that version. 
Also, it would be great to have a command to list the versions of k3s that are available to be installed. 
There is already a way for a user to specify the version they want so that doesn't need to change

The main benefit of this are 
a) uses don't have to re-download k3sup each time there is a new version of k3s
b) there will be no delay in access to the new version of k3s once it is released.

Note, I'm willing to code this up

## Expected Behaviour

only user facing change is that there will be a new command to list the k3s version. the rest will all be under the hood

k3sup list-versions

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I normally want my k3s cluster to be the most recent version.  but there is always a delay in having k3sup updated.

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

**Comment by alexellis** [comment]
Installing the "latest" version of k3s is equivalent to using the :latest tag with Docker images, which is widely accepted as an anti-pattern. Why do we feel that this anti-pattern is acceptable with k3s, but not with container images I would welcome constructive thoughts around this.

k3s is used with many tutorials, and sometimes features will be deprecated in Kubernetes and k3s, so just "installing latest" is unfortunately short-sighted and will result in breakages, in the same way that using `:latest` Docker image tags does. See also: #270 where `--no-deploy` is expected to be removed from k3s, using the `:latest` version would result in a crash when that flag is removed from k3s.

The pinned version of k3s recently changed 1.18, but I am open to users specifically opting into using a release channel, which should also help with your request.

See #237 for more on the release channels work.
