### ISSUE TITLE
WSL2 - Segmentation Fault

### ISSUE THREAD

**Issue by adrianmace** [alexellis/k3sup#267]
## Expected Behaviour

`k3sup --help` should give the help contents.

## Current Behaviour

`k3sup --help` causes a Segmentation Fault

## Possible Solution

Have to switch to the PowerShell and run it with Windows installation instructions. Downside is that my SSH keys are in my WSL2 Ubuntu installation.

## Steps to Reproduce (for bugs)

1. WSL2 using Ubuntu 20.04 LTS (x64 host machine)
2. Follow the steps outlined in the README.md to install k3sup
3. Observe Segmentation Fault

## Context

Since I have swapped my default terminal over to WSL2 on Windows 10, and since that is a full Ubuntu 20.04 install running on a virtualized linux kernel, I figured there'd be no issues running the linux installation steps for `k3sup`. It seems that I am wrong.

## Your Environment

Windows 10 v2004 with WSL2 running Ubuntu 20.04 'guest'.

**Comment by adrianmace** [comment]
A picture is worth 1000 words..
![image](https://user-images.githubusercontent.com/5071859/94526197-870c6680-0278-11eb-8c27-439fdd064e02.png)

**Comment by adrianmace** [comment]
Closed. Running the following steps fixed this issue (note the omission of `sudo` where I thought I was smart in the first attempt)
```
curl -sLS https://get.k3sup.dev | sh
sudo cp k3sup /usr/local/bin/k3sup
k3sup --help
```

**Comment by alexellis** [comment]
I'm not sure why you ran sudo install? The bash script already does that. You only need the first instruction, which appeared to work when k3sup printed its version.

What's the issue and how did you solve it?
