### ISSUE TITLE
Parameter Concatenation is busted!

### ISSUE THREAD

**Issue by jontg** [alexellis/k3sup#268]
Trying to spin up an HA cluster with `--datastore` and `--k3s-extra-args` results in an invalid k3s service config.

## Expected Behaviour
Try starting up a node
```bash
k3sup install --ip 10.0.1.1 --user pi --ssh-key ~/.ssh/personal_network --datastore="${DATASTORE}" --k3s-extra-args '--no-deploy servicelb'
```
and experience the joy of a service that came up successfully.
```bash
$ cat /etc/systemd/system/k3s.service
<snip>
ExecStart=/usr/local/bin/k3s \
    server \
	'--tls-san' \
	'10.0.1.1' \
	'--no-deploy' \
	'servicelb' \
	'--datastore-endpoint' \
	'mysql://<REDACTED>/kubernetes' \
```

## Current Behaviour
Try starting up a node
```bash
k3sup install --ip 10.0.1.1 --user pi --ssh-key ~/.ssh/personal_network --datastore="${DATASTORE}" --k3s-extra-args '--no-deploy servicelb'
```
and weep the tears of an administrator whose service failed to come up successfully.
```bash
$ cat /etc/systemd/system/k3s.service
<snip>
ExecStart=/usr/local/bin/k3s \
    server \
	'--tls-san' \
	'10.0.1.1' \
	'--no-deploy' \
	'servicelb--datastore-endpoint' \
	'mysql://<REDACTED>/kubernetes' \
```

## Steps to Reproduce (for bugs)
1. Try to start up a node
```bash
k3sup install --ip 10.0.1.1 --user pi --ssh-key ~/.ssh/personal_network --datastore="${DATASTORE}" --k3s-extra-args '--no-deploy servicelb'
```
2. Cry

## Context
I want an HA system that doesn't require carefully putting in a trailing space to the `--k3s-extra-args` parameter!  I'm spinning up a small k3s Raspberry Pi environment for a home lab set-up...

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

**Comment by Waterdrips** [comment]
Hi @jontg . Thanks for the good writeup of the issue. 

Would you like to try and fix the problem or should we put it on the list of things to fix?

Thanks,

Alistair

**Comment by alexellis** [comment]
Hi @jontg thanks for your report.

I actually had this working without error, as per the README, can you see how I did it there and try that?

We've had one or two issues with concatenation in the past which I expected to be fixed now, but as @Waterdrips says, we are open to pull requests from users.

Alex

**Comment by alexellis** [comment]
See also: [Create a multi-master (HA) setup with external SQL](https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-external-sql)

I wonder if you could try this without your additional `--k3s-extra-args` flags to check that it works for you?

**Comment by alexellis** [comment]
Would you mind running the command again with the `--print-version` flag?

**Comment by jontg** [comment]
Hey, sorry for the lack of response — github notifications don't appear to be sending.  It looks like I might be on an old release as that command fails?   I see that we released a new version 
```bash
$ k3sup install --ip 10.0.0.1 --user pi --ssh-key ~/.ssh/personal_network --datastore="${DATASTORE}" --k3s-extra-args '--no-deploy servicelb' --print-version
Error: unknown flag: --print-version
$ k3sup  --print-version
Error: unknown flag: --print-version
$ k3sup version
 _    _____
| | _|___ / ___ _   _ _ __
| |/ / |_ \/ __| | | | '_ \
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/
                     |_|
Version: 0.9.6
Git Commit: b94b83b4b3fda86ac88c736f0d98218bfa3cb37b
```

And thanks for the fix!

**Comment by alexellis** [comment]
Yes you definitely need to upgrade to get fixes. Can you run your scenario with the latest version? See the example in the oil request.

**Comment by alexellis** [comment]
Also it's --print-command - typo there on my behalf
