### ISSUE TITLE
Unable to resolve get.k3s.io

### ISSUE THREAD

**Issue by mcuix** [alexellis/k3sup#269]
k3sup install --ip 192.168.1.93 --user myuser
Running: k3sup install
Public IP: 192.168.1.93
curl: (6) Could not resolve host: get.k3s.io
Result:  curl: (6) Could not resolve host: get.k3s.io

## Expected Behaviour
Create node on Raspberry Pi

## Current Behaviour
Cannot resolve get.k3s.io

## Your Environment

* k3sup 

Linux

**Comment by alexellis** [comment]
Thank you for your interest but I'm going to be closing this as a technical support request. There's no issue with k3sup here.

Your next action is to check your DNS and network configuration on the Raspberry Pi. You'll find help on the Raspberry Pi forums for this. 

Once you fix your RPi, k3sup will function as expected.
