### ISSUE TITLE
Feature Request: Pass an optional url instead of server ip address to join nodes

### ISSUE THREAD

**Issue by ImIOImI** [alexellis/k3sup#271]
I'm building out a k3s cluster in AWS with Terraform and using ip addresses to bootstrap the cluster is not optimal. I'd rather create internal load balancers and/or internal Route53 addresses to point to auto scaling instances (especially for the server ip for the join command).

Given the current options, the best solution I've found is to use a cloud-init to provision an agent node to look up the current private ip address of a server in the server autoscaling group, and then use that ip on startup. I'm worried that this configuration might break if the server gets terminated. 

This arrangement could be simplified considerably by abstracting the ip address,

Thanks!

**Comment by alexellis** [comment]
Hi @ImIOImI thank you for your interest in k3sup.

It'd be appreciated if you could go ahead and [use the issue template](https://raw.githubusercontent.com/alexellis/k3sup/master/.github/ISSUE_TEMPLATE.md) (like everyone else does).

Also can you share some of your specific Terraform code? @Waterdrips has been doing a lot with Terraform of late and will probably have some ideas.

**Comment by alexellis** [comment]
When filling out the issue template you can provide everything we require including: a possible solution and how you expect it to work for you.

**Comment by ImIOImI** [comment]
Sorry about that, I didn't look closely enough at the alternate guidance for feature requests.

Urls are portable abstractions for ip addresses. Ip addresses change based on auto scaling instances changing, servers being upgraded and replaced, etc.

## Expected Behaviour
I'd like to make passing an ip address optional and having urls be an option as well.

## Current Behaviour
Passing ip addresses to the ip flag results in a parsing error

## Possible Solution
Allow an alternate flag for passing a url 

## Context
I want an HA Rancher cluster to control multiple k8s clusters across several cloud providers and accounts. Everything needs to be saved in Terraform. 

## Your Environment

* What Kubernetes distribution are you using (for `k3sup app`)?
```
k3sup version
Version: 0.9.6
Git Commit: b94b83b4b3fda86ac88c736f0d98218bfa3cb37b

kubectl version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 192.168.203.252:6443: i/o timeout
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Hosted in AWS Node info as follows:
```
uname -a
Linux ip-192-168-198-3 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Host OS is Windows WSL:

```
uname -a
Linux OKC-TKNAPP 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by alexellis** [comment]
Thank you for using the template. 

Can you edit and give a concrete example of the proposed join command with real values?

**Comment by ImIOImI** [comment]
Got it. Hope that helps.

**Comment by ImIOImI** [comment]
My current cloud init looks like this. I ended up pulling the server out of an autoscaling group so I could grab it's private IP address. That works... it's just not as fault tolerant as I want it to be.

```
#cloud-config
write_files:
  - path: /root/configure.sh
    content: |
      #!/usr/bin/env bash
      DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y
      sudo apt-get upgrade -y
      sudo apt-get install -y unzip
      
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      curl -sLS https://get.k3sup.dev | sh
      sudo install k3sup /usr/local/bin/
  - path: /root/k3sup-configure.sh
    content: |
      #!/bin/bash
      ssh_key="/root/.ssh/aws.pem"
      data_con="${data_con}"
      role=${role}
      server_ip=${server_ip}
      ip=$(hostname -I)

      if [ $role = "server" ]
      then
        #set up a server
        k3sup install --ip $ip --ssh-key $ssh_key --user ubuntu --context k3s --merge --datastore "$data_con"
      else
        #set up an agent
        k3sup join --user ubuntu --server-ip $server_ip --ip $ip --datastore \"$data_con\"
      fi 
  - path: /root/.ssh/aws.pem
    content: |
      ${private-ssh-key}
    permissions: '0644'
    owner: root:root
runcmd:
  - bash /root/configure.sh
  - sleep 1
  - bash /root/k3sup-configure.sh
```

**Comment by alexellis** [comment]
I'm looking into this myself, of providing more than one TLS San value, one for the LB and one for the IP of the node. 

There's a chicken and egg problem in that you can't SSH to the server IP since it's an LB with multiple IPs behind it. You can use its IP and configure the server's TLS San using the LB IP

**Comment by ImIOImI** [comment]
Right, this is why it's my plan to just run k3sup on each machine as it's booting up for the first time... so no ssh connection required. So that kills the need to know the agent nodes, but I still need to know how to get back to the server.

**Comment by alexellis** [comment]
Isn't your LoadBalancer just an IP? Or are you saying that it's an ALB which only has a static DNS entry?

**Comment by ImIOImI** [comment]
I use a mix between ALBs and ELBs depending on how pricing plays out... Regardless, you end up getting back a shared ip address that's used by a lot of accounts in the availability zone the lb is registered in.

**Comment by ImIOImI** [comment]
I went ahead and pulled out my repo from my current project and uploaded it. It's not pretty (yet), but it can show where I'm going and what I'm doing to code around this.

You can see in /config/cloud-init.yaml that I added this query to get the server ip:
```
server_ip=$(aws ec2 describe-instances --filters Name=tag:Name,Values=k3s-server Name=instance-state-name,Values=running --query "Reservations[*].Instances[*].NetworkInterfaces[*].PrivateIpAddress[]" --output text)
```

So, (unlike the method I stated above) I am using a tag on the instance called "k3s-server" and using the awscli to describe my ec2 instances that are running and have that tag. This is adequate since no ip address of a server is hardcoded into the bootstrapping process... but it just seems like an unnecessary complication to me.

**Comment by alexellis** [comment]
Thoughts on #272 ? Does this resolve the issue by giving you a `--tls-san`?

**Comment by ImIOImI** [comment]
Sorry for neglecting this. I've been able to get a working k3s cluster up on AWS (I'll be updating my terraform repo, shortly), now with k3s and I've got a bit more bandwidth to test this and improve what I built, now. How do you think I should modify the install/join commands to take advantage of the fix for concatenated strings? If you want to talk to me like I've only, actually, used k3s for 2 weeks... feel free.

**Comment by spqa** [comment]
I use this command and it work well
```
k3sup join --ip $IP \
        --server-ip <whatever ip here> \
        --user $USER \
        --ssh-key /tmp/private_key \
        --k3s-extra-args "--server https://master-load-balancer-dns:6443" \
        --k3s-version ${K3S_VERSION}
```
It generate systemd service like this so i guess it working fine:
```
ExecStart=/usr/local/bin/k3s \
    agent \
        '--server' \
        'https://master-load-balancer-dns:6443' \
```
It would be nice if we have a better flag though.
