### ISSUE TITLE
Pass K3s Channel for install

### ISSUE THREAD

**Issue by clemenko** [alexellis/k3sup#273]
From : https://rancher.com/docs/k3s/latest/en/installation/install-options/

Have the ability to add `INSTALL_K3S_CHANNEL=latest` through k3sup when installing. 
This will give the ability to choose either `stable` or `latest` when installing. This is helpful when testing out versions of k3s with other applications. 

## Expected Behaviour
Adding `--k3s-channel`
```
  k3sup install --ip $server --user $user --k3s-extra-args '--no-deploy traefik' --cluster --k3s-channel=latest --local-path ~/.kube/config
```

## Current Behaviour
`--k3s-channel` not found

## Possible Solution
Add it. :D The k3s installer itself can take the environment variable of `INSTALL_K3S_CHANNEL` for this function.

## Context
This will be used for testing of the latest k3s without having to find the exact version that is out. Pinning to a version is not ideal since it will require editing of scripts to keep up with the version. Here is my script that I use to deploy my demo stack. 
https://github.com/clemenko/rancher/blob/master/k3s.sh

## Your Environment
See demo stack : https://github.com/clemenko/rancher/blob/master/k3s.sh
k3sup 0.9.6
ubuntu 20.04
containerd
k3s v1.18.6+k3s1

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes

**Comment by alexellis** [comment]
Hi @clemenko we have already had this request from other users and have been working on it for some time. Feel free to search past issues. 

Your testing is welcome on #272 

Alex
