### ISSUE TITLE
support flatcar as a target OS

### ISSUE THREAD

**Issue by vbatts** [alexellis/k3sup#274]
(inspired by your [tweet](https://twitter.com/alexellisuk/status/1318236599277203462/photo/1))

currently k3s runs like a champ on Flatcar, but the installer (get.k3s.io) needs the environment variables of `INSTALL_K3S_BIN_DIR=/opt/bin` and `INSTALL_K3S_SELINUX_WARN=true`.

## Expected Behaviour
a running k3s instance

## Current Behaviour
```shell
vbatts@melisma:~$ k3sup install --ip 18.213.151.135 --user core --ssh-key ~/vbatts-test.pem --merge --merge --local-path ~/.kube/config --context k3s-t4g 
Running: k3sup install
Public IP: 18.213.151.135
[INFO]  Finding release for channel v1.18
[INFO]  Using v1.18.10+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.10+k3s1/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.18.10+k3s1/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
mv: inter-device move failed: '/tmp/k3s-install.xnjXyqhR08/k3s.bin' to '/usr/local/bin/k3s'; unable to remove target: Read-only file system
Error: error received processing command: Process exited with status 1
```

## Possible Solution
I began down the path of making the `operator.Execute()` allow for a `env []string` arg, so that `os.Environ()` could just get passed, but that doesn't work with the ssh operator.
Maybe checking for the supported vars, and then wrapping the `command` with `sh -c "$env $command"`?
not sure

## Steps to Reproduce (for bugs)

1. k3sup install --ip 18.213.151.135 --user core --ssh-key ~/vbatts-test.pem --merge --merge --local-path ~/.kube/config --context k3s-t4g
2.
3.
4.

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

AWS t4g.medium

* Operating System and version (e.g. Linux, Windows, MacOS):

```
core@ip-172-31-64-204 ~ $ cat /etc/os-release 
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2661.0.0
VERSION_ID=2661.0.0
BUILD_ID=2020-10-15-1534
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2661.0.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="arm64-usr"
core@ip-172-31-64-204 ~ $ uname -a
Linux ip-172-31-64-204.ec2.internal 5.8.14-flatcar #1 SMP PREEMPT Thu Oct 15 15:04:38 -00 2020 aarch64 GNU/Linux

```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes

**Comment by alexellis** [comment]
Thanks for the issue @vbatts 👋 

Part of the UX of k3sup is to abstract away verbose flags and environment variables, for instance `--k3s-channel` and `--no-extras`.

Given that these two values are required for Flatcar, I would be open to some sort of first-class flag to support it.

```bash
k3sup install --flatcar --ip $IP --user $USER
```

In additional to that feature, I also wonder if the `--k3s-extra-args` would take the `INSTALL_K3S_SELINUX_WARN` and `INSTALL_K3S_BIN_DIR` variables? If it's not going to write the flags into the correct place, we could do similar to what you suggested with `--k3s-env` - `--k3s-env INSTALL_K3S_SELINUX_WARN=false`

The tests here would be a good place to start development and validating an idea: https://github.com/alexellis/k3sup/blob/80383dde517ddaa1db7e56543955143aa99d24bf/cmd/install_test.go#L250

**Comment by alexellis** [comment]
How does that sound @vbatts?

**Comment by vbatts** [comment]
I don't think a `--flatcar` flag is ideal, as it ought not be considered a snowflake deployment, and wouldn't scale well as it obscures away choices, do you think?

Fully get wanting to make flags for things that the k3s installer takes in as env variables. The big one is `INSTALL_K3S_BIN_DIR=` and `INSTALL_K3S_SELINUX_WARN=`. perhaps `--k3s-env` is a better choice, as that doesn't bind `k3sup` to a potentially changing installer.

**Comment by alexellis** [comment]
Can you suggest some options for the UX of the CLI below? And which you like best? (both for the install + join commands)

**Comment by alexellis** [comment]
@vbatts I can't even imagine how busy you are. How do we get this moved forward? What about my comment above?

**Comment by alexellis** [comment]
If https://github.com/rancher/k3s/pull/2551 is merged, it looks like we may not need to change k3sup.

the `--k3sup-env` is something we could have, could be useful. We could do that now and have nobody use it (nobody else has asked for it) or wait until someone asks and then add it. K3sup remains maintainable by keeping things options lean.

**Comment by vbatts** [comment]
*`--k3s-env` :wink:

**Comment by vbatts** [comment]
Upstream merged!

**Comment by vbatts** [comment]
this Just Works:tm: now.

```shell
curl -sLS https://get.k3sup.dev | sh
sudo cp k3sup /opt/bin/
ssh-keygen
cat .ssh/id_rsa.pub >> .ssh/authorized_keys
k3sup install --user core
sudo kubectl get -A po
```
