### ISSUE TITLE
Add support for different agent user and agent ssh-key

### ISSUE THREAD

**Issue by bbhenry** [alexellis/k3sup#275]
When creating a k3s cluster using k3sup, it currently assumes the server and agent are using the same ssh-key and same ssh user. When creating cluster with different distros of Linux on AWS, the default ssh users are different. 

## Current Behaviour
- server is centos in AWS with default user `ec2-user`. 
- agent is ubuntu in AWS with default user `ubuntu`. 
- server and agent each has its own ssh key.

With the existing option, we can't choose to use different ssh user and or key when we run the `join` command. 
```
k3sup install --ip 192.168.0.1 --user ec2-user --ssh-key centos-key
k3sup join --ip 192.168.0.2 --server-ip 192.168.0.1 --user  ec2-user --ssh-key centos-key
```

## Possible Solution
If we can add additional parameter in the join command to allow separate user and key for the agent node such as
- `--agent-user`
- `--agent-ssh-key`

```
k3sup install --ip 192.168.0.1 --user ec2-user --ssh-key centos-key
k3sup join --ip 192.168.0.2 --agent-user ubuntu --agent-ssh-key ubuntu-key --server-ip 192.168.0.1 --user  ec2-user --ssh-key centos-key
```

## Context
It's impossible to use k3sup when I have nodes that is configured with different ssh user and ssh keys.

## Your Environment
I am running k3sup from MacOS

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

No, I am not familiar with golang to make the pull request.

**Comment by bbhenry** [comment]
I just found out there's a `--server-user` parameter when using the `join` command. This is suffice for now.

**Comment by alexellis** [comment]
* server is centos in AWS with default user ec2-user.
* agent is ubuntu in AWS with default user ubuntu.

My main question is: why?

And secondly, this can be fixed easily in your cloudinit script.

https://cloudinit.readthedocs.io/en/latest/topics/examples.html
