### ISSUE TITLE
Add Table of Contents for easy navigation of topics

### ISSUE THREAD

**Issue by yankeexe** [alexellis/k3sup#277]
## Expected Behaviour

Table of contents on top of `README.md` with respective hyperlinks to the headings. Will enable: 

1. easy overview of all features 
2. easy navigation to desired feature.

## Current Behaviour

No Table of Contents, have to scroll through the whole page to get to the desired topic. 

## Possible Solution

Adding Table of Contents. 

## Context

have to scroll through the whole page to get to the desired topic. 

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes/No

**Comment by alexellis** [comment]
Feel free to contribute this. I think the idea is fine 👍

**Comment by yankeexe** [comment]
@alexellis sure
