### ISSUE TITLE
Convert CI to GitHub Actions

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#279]
## Task 

Convert CI to GitHub Actions

## Context

Travis is removing its free tier for OSS projects, so this should be built with GitHub Actions instead, which is not going to add additional cost.

I would expect this to be one of the easier projects to convert given that Docker isn't used in the build.

See also:

https://github.com/mvdan/github-actions-golang
https://github.com/actions/create-release
https://github.com/actions/upload-release-asset

https://github.com/alexellis/arkade/issues/263

**Comment by isabellaliu77** [comment]
can I try this?

**Comment by alexellis** [comment]
Hi @isabellaliu77 we have a couple of things you can follow here, but I'd suggest [you take up the inletsctl PR](https://github.com/inlets/inletsctl/issues/81) instead as @Waterdrips has volunteered to take this one and we need it done as soon as possible.

All three should be very similar.

https://github.com/alexellis/k3sup/pull/280
Plus

https://github.com/alexellis/k3sup/commit/79720da83b694735d6415f3f3d01f02a1f809da8

Regards,

Alex

**Comment by isabellaliu77** [comment]
Thanks for your feedback. I'll take the inletsctl PR
