### ISSUE TITLE
k3s channels failing to work

### ISSUE THREAD

**Issue by yankeexe** [alexellis/k3sup#284]
K3s now follows a different version naming scheme. Along with `semver` it has now added a postfix in the form of `+k3s<number>`. 
More details can be found [here](https://github.com/rancher/k3s#release-cadence).

## Expected Behaviour

The default versioning of `k3s` to work i.e. `v1.18` with the install command. 

```bash 
$ k3sup install --ip <ip> --user <username>
```

## Current Behaviour

Throws an error; the pages with old versioning does not exist. (404)
![image](https://user-images.githubusercontent.com/13623913/99148998-5f9c1c80-26b3-11eb-9985-b0e41071683c.png)

## Possible Solution

Update the default value of `--k3s-channel` flag to the new version naming scheme i.e. `v1.19.3+k3s3` or use `stable`. 

## Steps to Reproduce (for bugs)

1. Launch a multipass instance
2. try installing k3s : `k3sup install --ip <ip> --user <username>`
3. Will try fetching k3s assets using old version naming scheme. 
4. Fails the install.

## Context

Doesn't allow the installation of `k3s` with minimal set of commands. Need to specify the `--k3s-channel "stable"` flag to get it working.

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
`multipass 1.14.0`

* Operating System and version (e.g. Linux, Windows, MacOS):
`Windows `

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?
`Yes`

**Comment by alexellis** [comment]
Can you find confirmation about this please?

Any release notes? It seems bizarre to make a breaking change like this rather than phasing it out

**Comment by alexellis** [comment]
Might be related to this https://github.com/rancher/k3s/issues/2531

**Comment by alexellis** [comment]
/set title: k3s channels failing to work

**Comment by yankeexe** [comment]
> Might be related to this [rancher/k3s#2531](https://github.com/rancher/k3s/issues/2531)

Yes, looks like it.

**Comment by yankeexe** [comment]
@alexellis the channel is working now.
