### ISSUE TITLE
k3sup join results in unable to get join-token from server

### ISSUE THREAD

**Issue by therealburningman** [alexellis/k3sup#287]
Early exit due to "unable to get join-token from server" error when joining a k3s agent.

## Expected Behaviour
I expect k3sup to succesfully join a k3s cluster (agent)

## Current Behaviour
```
Running: k3sup join
Server IP: 192.168.1.14
cat: /var/lib/rancher/k3s/server/node-token: No such file or directory
Error: unable to get join-token from server: Process exited with status 1
```

## Possible Solution
I've research the k3sup Go source code and conclude I am doing the right thing. The actual node-token is retrieved using a sudo command because `useSudo` is set to true (default value). This sudo command when ssh logged in with the specified user (install instruction) works. 

## Steps to Reproduce (for bugs)
```
k3sup install --ip 192.168.1.12 --no-extras true --user pi --ssh-key ~/.ssh/id_ed25519
k3sup join --ip 192.168.1.12 --server-ip 192.168.1.14 --user pi --ssh-key ~/.ssh/id_ed25519
```
## Context
Trying to build a 3 node cluster using k3sup.

## Your Environment
3 x Raspberry Pi 3Bs in 64bit mode.

* What Kubernetes distribution are you using? 
**v1.18.12+k3s1**

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`): 
Raspbian GNU/Linux 10 (buster)

* Operating System and version (e.g. Linux, Windows, MacOS):
**Linux**
```
uname -a

cat /etc/os-release
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?
**Yes**

**Comment by therealburningman** [comment]
I've mixed up the --ip and --server-ip addresses.

**Comment by alexellis** [comment]
No worries Hans. Glad you figured it out!
