### ISSUE TITLE
k3sup install --k3s-extra-args '--no-traefik' doesn't skip installing traefik on k3s

### ISSUE THREAD

**Issue by therealburningman** [alexellis/k3sup#288]
## Expected Behaviour
Don't install traefik.

## Current Behaviour
installs traefik

## Steps to Reproduce (for bugs)
1. `k3sup install --k3s-extra-args '--no-deploy traefik' --ip 192.168.1.12 --user pi --cluster --k3s-version v1.19.1+k3s1 --ssh-key ~/.ssh/id_ed25519`

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+k3s1", GitCommit:"b66760fccdddfc98fa107ec38c86c5e2814e559d", GitTreeState:"clean", BuildDate:"2020-09-17T17:16:55Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/arm64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
**Raspberry Pi 3B (3x)**

* Operating System and version (e.g. Linux, Windows, MacOS):
**Linux**
```
uname -a
Linux k3s-master 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

## "Workaround"
1. `kubectl delete deploy/traefik -n kube-system`

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

**No, not in this case**

**Comment by alexellis** [comment]
I'm a bit confused with this bug report. I thought you said on slack that you used `--no-extras` and that it still installed Traefik?

That's not what you've reported here. Help me understand.

**Comment by alexellis** [comment]
I think you wanted `'--no-deploy traefik'` so I'm going to close this, but am happy to re-open if you run into a different issue.

From the README:
> --k3s-extra-args - Optional extra arguments to pass to k3s installer, wrapped in quotes, i.e. --k3s-extra-args '--no-deploy traefik' or --k3s-extra-args '--docker'. For multiple args combine then within single quotes --k3s-extra-args '--no-deploy traefik --docker'.

**Comment by alexellis** [comment]
```bash
$ k3sup install --k3s-extra-args '--no-deploy traefik' --ip 192.168.64.5 --user ubuntu --print-command
Running: k3sup install
Public IP: 192.168.64.5
ssh: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --tls-san 192.168.64.5 --no-deploy traefik' INSTALL_K3S_CHANNEL='v1.18' sh -
```

No Traefik:

```
$ export KUBECONFIG=/Users/alex/kubeconfig
$ kubectl get deploy -n kube-system
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
coredns                  0/1     0            0           9s
local-path-provisioner   0/1     0            0           9s
metrics-server           0/1     0            0           8s
$ 
```

**Comment by alexellis** [comment]
`--no-extras` seems to work as expected too:

```
$ k3sup install --no-extras --ip 192.168.64.5 --user ubuntu --print-command
Running: k3sup install
Public IP: 192.168.64.5
ssh: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --tls-san 192.168.64.5 --no-deploy servicelb --no-deploy traefik' INSTALL_K3S_CHANNEL='v1.18' sh -

[INFO]  Finding release for channel v1.18

...


$ export KUBECONFIG=/Users/alex/kubeconfig
$ kubectl get deploy -n kube-system
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
local-path-provisioner   1/1     1            1           92s
metrics-server           1/1     1            1           91s
coredns                  1/1     1            1           92s
space-mini:~ alex$ 
```

**Comment by therealburningman** [comment]
Could the exception be that I used the `--cluster` argument? Because I get traefik installed with both `--no-extras` and `--k3s-extra-args '--no-deploy traefik'`.
