### ISSUE TITLE
unable to join ec2 instances together

### ISSUE THREAD

**Issue by si458** [alexellis/k3sup#297]
i am unable to join 2 ec2 instances together, both being master, but not sure if im doing something wrong maybe?
i have opened in my security group the port `6443` from my home ip only

## Expected Behaviour
the second instance to join the cluster on the first?

## Current Behaviour
the second instance never joins the first master

## Possible Solution
let end user specify the internal address k3s should connect to instead of the external address

## Steps to Reproduce (for bugs)

1. create master on first node 
`k3sup install --host ec2-18-130-xxx-xxx.eu-west-2.compute.amazonaws.com --ssh-key ~/Developer/MyKey.pem --user ubuntu --cluster`
2. try joining on second node
`k3sup join --host ec2-18-130-xxx-xxx.eu-west-2.compute.amazonaws.com --server --server-host ec2-18-130-xxx-xxx.eu-west-2.compute.amazonaws.com --server-user ubuntu --ssh-key ~/Developer/MyKey.pem --user ubuntu`

## Context
error found on second instance
```
Jan 17 12:55:59 ip-172-31-10-254 k3s[3308]: time="2021-01-17T12:55:59Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
Jan 17 12:55:59 ip-172-31-10-254 k3s[3308]: time="2021-01-17T12:55:59Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/30740d1d67da51fe92b10367ecce4d580e552c634ad4a6c4dd13297ffd1f3edd"
Jan 17 12:56:01 ip-172-31-10-254 k3s[3308]: time="2021-01-17T12:56:01.876134307Z" level=info msg="Starting k3s v1.19.7+k3s1 (5a00e38d)"
Jan 17 12:56:41 ip-172-31-10-254 k3s[3308]: time="2021-01-17T12:56:41.877791821Z" level=fatal msg="starting kubernetes: preparing server: failed to get CA certs: Get \"https://ec2-18-130-xxx-xxx.eu-west-2
.compute.amazonaws.com:6443/cacerts\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Jan 17 12:56:41 ip-172-31-10-254 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
```

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+k3s1", GitCommit:"5a00e38db4c198fb0725a6b709380aed8053d637", GitTreeState:"clean", BuildDate:"2021-01-14T23:09:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux ip-172-31-10-254 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:01:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes/No

**Comment by alexellis** [comment]
Sorry that you've having networking issues. This is not a problem with k3sup, but we may be able to make some suggestions for you.

You can read how K3s networking works and what is required in your security group in the K3s docs: https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#networking

There is no known issue or bug with `k3sup join`, so I'll close this issue.
