### ISSUE TITLE
Question - how can I use k3sup when sudo requires a password

### ISSUE THREAD

**Issue by snoopy82481** [alexellis/k3sup#298]
When running the command k3sup install --ip 192.168.1.182 --user stephen --cluster --ssh-key ~/.ssh/kube-master-1 get the following error: 
  sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
  Error: error received processing command: Process exited with status 1

## Expected Behaviour
Should operate as intended in documentation

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Multiple VM's on a Proxmox 6.3-3 host

* What Kubernetes distribution are you using?

```
kubectl version:

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+k3s1", GitCommit:"5a00e38db4c198fb0725a6b709380aed8053d637", GitTreeState:"clean", BuildDate:"2021-01-14T23:09:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Ubuntu 20.04
* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a:
Linux kube-master-1 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release:
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes

**Comment by ncodee** [comment]
Facing the same issue here, but on Ubuntu 20.10.

**Comment by smcue** [comment]
Can vouch the same issue for me here.

**Comment by gilsdav** [comment]
Your user has to be configured to be able to exacute sudo commands without password:
```
sudo visudo
stephen ALL=(ALL) NOPASSWD:ALL
```

**Comment by gnoejuan** [comment]
> 
> 
> Your user has to be configured to be able to execute sudo commands without password:
> 
> ```
> sudo visudo
> stephen ALL=(ALL) NOPASSWD:ALL
> ```

I would request this information is added to the README

**Comment by alexellis** [comment]
/set title: Question - how can I use k3sup when sudo requires a password

**Comment by heytcass** [comment]
> Your user has to be configured to be able to execute sudo commands without password:
> 
> ```
> sudo visudo
> stephen ALL=(ALL) NOPASSWD:ALL
> ```

Did this, still getting the same error as the original comment. On Ubuntu 20.10 as well.

**Comment by xaocon** [comment]
> Did this, still getting the same error as the original comment. On Ubuntu 20.10 as well.

@heytcass, did you do exactly that? if your user isn't stephen then that's not going to work. Check the output from `sudo -l` to start diagnosing the problem.

**Comment by adamphetamine** [comment]
For people with this issue, you need to add 'passwordless sudo' to your user.
On Ubuntu,

`sudo visudo`

Go to the bottom of the file and add
`your_username ALL=(ALL:ALL) NOPASSWD:ALL`

Save & exit

Now try the install command again, if it didn't work, make sure you appended the sudoers file at the bottom, I tried first putting the line where I thought it should go- and paid the price.

Alex got around this in the example by using root, I'm hoping in the future there is a more elegant solution as I'm not knowledgeable enough to be 100% confident this is a good way to fix the issue...

**Comment by alexellis** [comment]
K3sup requires password `sudo`. Happy for someone to make a suggestion on how to handle this differently, but I'm going to close this as "wontfix" because I don't have a solution for you.

All I can suggest is:

* Edit sudoers so that you don't need a password for sudo over SSH
* Use the root user for ssh, and use `--sudo=false`

Maybe the Ansible or Terraform community have an answer for this? They also have similar issues.

**Comment by airtonix** [comment]
If you don't have a solution, then closing and labeling wontfix isn't the way to handle these tickets dude,

**Comment by adamphetamine** [comment]
@airtonix it's his project, he can do whatever he wants with it.
Instead of complaining that someone didn't give you an easy fix, why not have a look at the reasons behind the decision?

The logic is sound, and adding 'won't fix' and closing it is about all that can be done unless you can suggest something?

**Comment by airtonix** [comment]
@adamphetamine yeah you're right. lets not fix this.

**Comment by alexellis** [comment]
You’re both welcome to become sponsors and to support my time on k3sup

The suggestion is to edit your sudoers file and enable passwordless sudo
