### ISSUE TITLE
Support RKE2

### ISSUE THREAD

**Issue by ams0** [alexellis/k3sup#299]
## Expected Behaviour
RKE2 seems quite similar to k3s in how it starts and manages the nodes, probably won't be too difficult to adapt k3sup to use it

## Current Behaviour
k3sup works with k3s only

## Possible Solution
Haven't look into the code yet

**Comment by alexellis** [comment]
Thank you for taking an interest in k3sup. I don't have any budget or scope to add RKE (k3sup is free and open-source), but if Rancher Labs wanted to fund this, I would consider it..
