### ISSUE TITLE
Provision the slaves after the master is running

### ISSUE THREAD

**Issue by alejandrojnm** [alexellis/k3sup#3]
Add a parameter that can be something like `--slave` and pass a list of ip like `[192.168.1.3,192.168.1.2]` or `"192.168.1.3, 192.168.1.2"`, I think it would be great

**Comment by alexellis** [comment]
I like this. So we would do something like:

`k3sup join` ?

**Comment by alejandrojnm** [comment]
It seems good to me. what I see more, as something you use while creating the master to be done in parallel, but you prefer create like something apart?

**Comment by alexellis** [comment]
Yes as a second command that first connects to the master to get the token, then adds it to each agent node

**Comment by geekdave** [comment]
This would be amazing for making clusters disposable and easy to recreate automatically.  Note that k3s uses `server` / `agent` and not `master` / `slave`.

**Comment by alexellis** [comment]
I'm aware of the terminology in k3s, however k3s creates Kubernetes which uses other terminology. 

Thanks for your interest in the feature. I think I'll have a go at it.

**Comment by alexellis** [comment]
Please try this out in the latest version 0.2.0

Thank you again for the idea :100:
