### ISSUE TITLE
[Question] How to deploy 

### ISSUE THREAD

**Issue by scheung38** [alexellis/k3sup#300]
How to deploy a full stack frontend + backend + PostgresQL after launching it ? Any nice articles please?

This is assuming these three images are already in hub.docker.com

 Much appreciated

**Comment by alexellis** [comment]
Yes absolutely. I have a step-by-step workshop available in my sponsors portal - any OpenFaaS sponsor can get access.

https://faasd.exit.openfaas.pro/function/trove/

You'd probably also enjoy the new book on faasd which walks you through Postgresql and consuming it from a Node.js backend API.

https://gumroad.com/l/serverless-for-everyone-else

Thanks for the question.
