### ISSUE TITLE
[PROPOSAL] Air-gapped support 

### ISSUE THREAD

**Issue by developer-guy** [alexellis/k3sup#301]
K3s has an air-gapped installation method, maybe we can add this to k3sup.

https://rancher.com/docs/k3s/latest/en/installation/airgap/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes/No

**Comment by alexellis** [comment]
I would welcome suggestion here for approaches and designs

**Comment by YAMLcase** [comment]
@bdun1013 will this have scp support as well?  I'm deploying to hosts in a secure environment and its hit or miss on if sftp works.

**Comment by alexellis** [comment]
Duplicate of #26
