### ISSUE TITLE
Dead link in README.md RE: Security line 441

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [alexellis/k3sup#302]
> ## Caveats on security
> 
> If you are using public cloud, then make sure you see the notes from the Rancher team on setting up a Firewall or Security Group.
> 
> k3s docs: [k3s configuration / open ports](https://rancher.com/docs/k3s/latest/en/configuration/#open-ports-network-security)
> 

_**### The link above does not pertain to setting up a firewall.**_

## Possible Solution

A summary of the information that was contained there would be there, I tried finding a copy but couldn't

Thanks!

**Comment by alexellis** [comment]
Thanks for your interest in k3sup. Feel free to send a PR with where Rancher moved the page to. I'm guessing the networking section of their docs site

**Comment by F1r3Hydr4nt** [comment]
I was about to do that but the 'firewall' section I found in their [docs](https://rancher.com/docs/rancher/v2.x/en/installation/resources/advanced/firewall/) leads with:

> ### Opening Ports with firewalld
> We recommend disabling firewalld. For Kubernetes 1.19, firewalld must be turned off.

Which obviously means that there's some other way of securing a k8s cluster with a firewall or perhaps not as it does not come up in ['101-more-kubernetes-security-best-practices'](https://rancher.com/blog/2019/2019-01-17-101-more-kubernetes-security-best-practices/)

Maybe the ['Hardening Guide'](https://rancher.com/docs/rancher/v2.x/en/security/#rancher-hardening-guide) fits? But it's certainly not for beginners

**Comment by alexellis** [comment]
This is repo is for k3sup, not openfaas, so I'm not sure how that's relevant.

The link I meant was this one. I'll sort it out myself, no worries.

Thanks for reporting the link breakage by Rancher

**Comment by F1r3Hydr4nt** [comment]
Sorry I thought they might make use of the same security protocols. Thanks!

**Comment by alexellis** [comment]
You can get help on OpenFaaS from the docs on the production page, or via support https://openfaas.com/support/

Thanks for the question.
