### ISSUE TITLE
Documentation: add a note to the Usage section about enabling cgroups on raspbian

### ISSUE THREAD

**Issue by ohnotnow** [alexellis/k3sup#308]
Spent a bit of time the other day running k3sup against a pi4 with raspbian on it.  Eventually after a bit of googling about realised I had to enable cgroups via the `/boot/cmdline.txt` file by adding `cgroup_memory=1 cgroup_enable=memory` to it.  Then k3sup worked perfectly.

## Expected Behaviour
k3sup as documented in the usage section should work on a pi _if_ you've read a note mentioning the above.

## Current Behaviour
k3sup fails.

## Possible Solution
Add a little note for raspbian/pi users.

## Steps to Reproduce (for bugs)
Run k3sup as per the usage section against a plain install of raspbian.

## Context
As above.

## Your Environment
Rpi v4 running raspbian 10.

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes

**Comment by alexellis** [comment]
Hi @ohnotnow - this is actually covered in my tutorials on RPi and K3s, but I don't mind repeating it here, it seems like a useful suggestion.

Thanks for using k3sup, do consider becoming a GitHub Sponsor to support this project's continued development and maintenance.

**Comment by alexellis** [comment]
You may also like:

https://blog.alexellis.io/test-drive-k3s-on-raspberry-pi/
https://alexellisuk.medium.com/walk-through-install-kubernetes-to-your-raspberry-pi-in-15-minutes-84a8492dc95a

And to support the project, feel free to checkout one of the following:
* https://github.com/sponsors/alexellis
* https://github.com/sponsors/openfaas
