### ISSUE TITLE
README says HA multi-master with embedded etcd is experimental

### ISSUE THREAD

**Issue by Simbaclaws** [alexellis/k3sup#309]
Hi there,

I just got told by a community member that a HA multi-master with embedded etcd is experimental.
It's been stable since 1.19, am I right to assume this should be changed in the documentation?

**Comment by alexellis** [comment]
Hi, what would you like us to do for you?

**Comment by alexellis** [comment]
Do you mind editing this issue and filling in a little context?

**Comment by alexellis** [comment]
OK I looked up the Rancher docs and it seems like they just released 1.19.5 (note the revision) and changed their advice on etcd from it being experimental, to not. The README has been updated.

We would welcome Rancher to participate in the community upstream, and send PRs. Also happy for community members to help out there.
