### ISSUE TITLE
[Feature Request] Support ssh-agent

### ISSUE THREAD

**Issue by Madic-** [alexellis/k3sup#31]
Instead of relying on an ssh-key also support ssh-agent for retrieving / using a private ssh key. Normaly I've no key on my hard drive. It's just loaded via ssh-agent

**Comment by Madic-** [comment]
Or maybe do not require an ssh key because by default ssh tries to authenticate with the help of an ssh agent

**Comment by alexellis** [comment]
I believe that we added support for this in #8 ?

**Comment by alexellis** [comment]
There's an issue template for a reason, please could you edit your issue to fill it out properly?

https://raw.githubusercontent.com/alexellis/k3sup/master/.github/ISSUE_TEMPLATE.md

It will help me, to help you. :man_shrugging: 

Thanks :+1:

**Comment by alexellis** [comment]
@Madic- would be great if you could provide everything needed in the issue template. I'll give it a week then close out the issue if I don't hear back.

Alex

**Comment by Madic-** [comment]
The ticket can be closed. Have missed the part in the readme regarding password protected ssh keys. Thank you
