### ISSUE TITLE
Support multiple key arguments for join command

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [alexellis/k3sup#310]
I am building a multicluster with 4 pis to learn, so please excuse my lack of knowledge/understanding of best practises...
I have setup each pi with alpine linux 10.0.5 and managed to use k3sup to install k3s on each however when I try add an agent to the cluster I cannot:
```bash
k3sup join --user pi0 --server-ip $PI0 --ip $PI1 --ssh-key ~/.ssh/pi0_ed25519 
Running: k3sup join
Server IP: 192.168.1.225
K106e8e857a85ac5d608a4b1147999214429a5339fe56e30e0e4d820d43daae18de::server:a56f78b55f18f22aef0daf690c75a512
Error: unable to connect to 192.168.1.203:22 over ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
## Possible Solution
Allow for the specification of an `--agent-ssh-key` ?

Of course, I could just use the same key on each host but that would introduce a single point of failure ("Oh no not my pies!")

## "Be part of the solution"
Yes, I have not programmed in Go however

*I guess it'd need a --agent-user switch too
I'm gonna take a look at implementing this later today.

**Comment by F1r3Hydr4nt** [comment]
Whoops, already supported `--server-user --server-ssh-key` etc

**Comment by sithon512** [comment]
Related to this issue, I'm attempting to join a node and without `--server-ssh-key` I get the error:
```
$ k3sup.exe join --user pi --server-ip $SERVER_IP --ip $IP --ssh-key $KEYPATH
--sudo true
Running: k3sup join
Server IP: 192.168.4.99
Error: unable to connect to (server) 192.168.4.99:22 over ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
But when I specify the `--server-ssh-key` flag, I get:
```
$ k3sup.exe join --user pi --server-ip $SERVER_IP --ip $IP --ssh-key $KEYPATH --sudo true --server-ssh-key $SERVER_KEYPATH
Error: unknown flag: --server-ssh-key
```

I'm not certain exactly where to go with this error.

**Comment by NikodemWrona** [comment]
I'm having same error (`Error: unknown flag: --server-ssh-key`), any upates ?

**Comment by NikodemWrona** [comment]
> --server-ssh-key

are you sure

**Comment by sithon512** [comment]
@NikodemWrona I ended up finding a different way to accomplish this following this article: https://jussiroine.com/2021/06/building-a-kubernetes-cluster-using-raspberry-pi-4/
