### ISSUE TITLE
Add support for Smart Cards/pre-configured agents.

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/k3sup#311]
## Expected Behaviour
`k3sup` is usable for users who do not use files for private key auth. Smart cards for example.

## Current Behaviour

Tool fails due to no private key file existing on the filesystem.

## Possible Solution

Silently attempt to establish the SSH connection before falling back to the existing file based auth. This allows users with smart cards, or who have pre-configured ssh-agents to work. If not using a smart card the end user will see no change to existing behaviour.

Fixes #255 

## Steps to Reproduce (for bugs)

1. Yubikey with no private key file on disk
2. Use install command
3. Fails with `unable to load the ssh key with path...`

## Context

Had tried using `k3sup` to setup k3s as a replacement for my old k8s cluster, doesn't support my use of a Yubikey for SSH auth.

## Your Environment

* What Kubernetes distribution are you using?

n/a

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

Ubuntu 20.04 on a NUC.

* Operating System and version (e.g. Linux, Windows, MacOS):

```
OSX 10.15.7
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes, I have it working on a fork already.

**Comment by johnmccabe** [comment]
Will raise a PR if you're interested

**Comment by alexellis** [comment]
Hi @johnmccabe, good to hear from you 😄 

A small number of people have asked for Yubikey support, and @jsiebens has solved this problem in his [hashi-up](https://github.com/jsiebens/hashi-up) tool, forked from k3sup to install Hashicorp tooling on hosts over SSH.

I have to confess, that most of the VMs I create are ephemeral and only for testing and I don't mind using an RSA or ecdsa key. When I do have production-grade VMs, I am unlikely to SSH into them, i.e. a managed K8s cluster. From that perspective I'm unlikely to use this change any time soon. I do own a couple of Yubikeys that I use for logging into GitHub etc, so I could potentially help with initial testing.

Subject to this approach being approved, and merged, would you be happy to maintain the changes and support users who need to use a Yubikey for their SSH key?

You mentioned attempting to not use a key, followed by reconnecting and attempting to use a key after. That sounds like it might degrade the experience for users who store a private key in `$HOME/.ssh`?

What method/design would you propose for making the Yubikey work?

**Comment by johnmccabe** [comment]
* I can test on OSX and Windows
* The implementation falls through transparently to the existing behavior. ie. it tries to connect using an already configured agent, and if it fails it uses the supplied/default private key. I've made minimal changes to the existing ssh implementation, to keep the change discrete.
* As for supporting/maintaining, thats the bit that gives me pause, I can't guarantee I'll have time/energy to do so...

I'll push up my PR shortly.
