### ISSUE TITLE
How can I change public IP

### ISSUE THREAD

**Issue by mind-mind** [alexellis/k3sup#313]
Hi,

If I have another public IP which isn't eth0, how can I config it to be k8s public IP?

For example, I would like appbrmig2 to be my public IP, but I think it has default eth0

Thank you.
<img width="576" alt="Screen Shot 2021-03-03 at 12 01 46 PM" src="https://user-images.githubusercontent.com/68138683/109755392-80fc2680-7c18-11eb-941a-06d7d8a48524.png">

**Comment by alexellis** [comment]
Closing this issue as this is one for the k3s repo instead. Feel free to mention to them that you also use k3sup when you raise your issue.

In future, do fill out issues templates as they are not optional.
