### ISSUE TITLE
k3sup --cluster directs to use 'set-context' instead of 'use-context'

### ISSUE THREAD

**Issue by thejimnicholson** [alexellis/k3sup#314]
During post-installation of a cluster primary node as follows:

```shell
k3sup install --host primary --user ubuntu --cluster --local-path ~/.kube/config --merge --context newcluster
``` 
the information message directs the user to issue `kubectl config set-context newcluster`. This 
should be `kubectl config use-context newcluster`, otherwise the context actually isn't switched, and the results will 
not be as expected.  

## Expected Behaviour
kubectl commands are directed to the newly merged context.

## Current Behaviour
kubectl commands are directed to the current context, which probably isn't pointing at the new cluster. 

## Possible Solution
* What Kubernetes distribution are you using?

k3s 1.20.x+k3s1

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

Local VM cluster (proxmox-hosted)

* Operating System and version (e.g. Linux, Windows, MacOS):

ubuntu 20.04

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

I've done it already. Just submitting issue to track it before sending the PR.

**Comment by thejimnicholson** [comment]
I've got a PR ready to submit, but the checklists are a bit much for changing 3 chars in a help message.

**Comment by alexellis** [comment]
Go ahead @thejimnicholson - if you feel that you can't fill out the PR template, then let us know and someone else will answer the 3-5 questions about the contribution.

Alex
