### ISSUE TITLE
[Question] Enable to authenticate?

### ISSUE THREAD

**Issue by scheung38** [alexellis/k3sup#315]
Created a local VM via multipass:

Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-54-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Mar 10 13:33:16 GMT 2021

  System load:  0.34              Processes:               137
  Usage of /:   68.1% of 4.67GB   Users logged in:         0
  Memory usage: 75%               IPv4 address for cni0:   10.42.0.1
  Swap usage:   0%                IPv4 address for enp0s2: 192.168.64.29

but

k3sup install --ip 192.168.64.29 --user root --ssh-key ~/.ssh/id_rsa

Error: unable to connect to 192.168.64.29:22 over ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by alexellis** [comment]
You should use multipass exec bash

Then paste .ssh/id_rsa.pub from your host into .ssh/authorized_keys on your VM.

🙂

You're welcome

**Comment by scheung38** [comment]
Also changed in localhost:

chmod 700 ~/.ssh
chmod 644 ~/.ssh/.pub
chmod 600 ~/.ssh/private

ssh-copy-id -i $HOME/.ssh/id_ed25519_k3sup.pub root@192.168.64.29
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "$HOME/.ssh/id_ed25519_k3sup.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@192.168.64.29: Permission denied (publickey).

**Comment by alexellis** [comment]
You need to use the proper username. It's usually ubuntu.

I can't offer you personal technical support, but you're free to go and chat with the Canonical Community if you need help using multipass beyond what I've told you.

It works as expected (I've tried it) and know of others that have done too.

**Comment by pletnes** [comment]
I will just leave this command here, in case someone wants to script this.

```bash
cat ~/.ssh/id_ed25519.pub | multipass exec vm_name_here -- tee -a .ssh/authorized_keys
```

This assumes that the `~/.ssh` directory exists, which it does on the VMs I've created with multipass.

**Comment by m-gris** [comment]
alternatively, this also does the job:

`multipass transfer ~/.ssh/<KEY> <VM-NAME>:/home/ubuntu/.ssh/`

**Comment by BertCatsburg** [comment]
> alternatively, this also does the job:
> 
> `multipass transfer ~/.ssh/<KEY> <VM-NAME>:/home/ubuntu/.ssh/`

Multipass already has an authorized_key. Don't overwrite this. 
The "tee -a" option is the best one.
