### ISSUE TITLE
merge options failed with 'Unable to connect to the server: x509: certificate signed by unknown authority'

### ISSUE THREAD

**Issue by zzswang** [alexellis/k3sup#316]
Follow the steps:

1. create a cluster with 3 master nodes in etcd mode, follow instruction on the [README.md](https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-embedded-etcd)

with merge option

```
    --local-path ~/.kube/config --merge \
```

2. reset all virtual machines

3. run step 1 again

## Expected Behaviour

`kubectl get node` should work

## Current Behaviour

but get

```
unable to connect to the server: x509: certificate signed by unknown authority
```

## Possible Solution

It seems with merge option, the certs in config are not updated.

## Your Environment

- local: OSX catalina
- vms: ubuntu 18.04

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8+k3s1", GitCommit:"95fc76b206b1455db7d50e23fb45c98d6ea97dde", GitTreeState:"clean", BuildDate:"2021-02-22T19:46:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
# uname -a

Linux master-002 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by alexellis** [comment]
I'm not sure how we can help you with this one. It sounds like a problem with your K3s cluster or setup. I'm going to close, but let us know if you A) have a repro B) can prove it's k3sup and not k3s itself.

**Comment by zzswang** [comment]
Hey, I'm not familiar with go, but I found maybe we have wrong order in this line.

https://github.com/alexellis/k3sup/blob/2b1a3914605faadd3a1c43436cf4634510bd553c/cmd/install.go#L372

I have quick test with `kubectl config view --merge --flatten`, it turns out that the cert in first config file will be kept after merged.

so I guess this line should be:

```
appendKubeConfigENV := fmt.Sprintf("KUBECONFIG=%s:%s", file.Name(), localKubeconfigPath)
```

**Comment by zzswang** [comment]
## new config should put before the old one in `kubeconfigEnv`

Here are the reproduce steps 

```
cat config.old | yq '.clusters | .[0].cluster.server'
```

"https://old.server.io:6443"


```
cat config.new | yq '.clusters | .[0].cluster.server'
```

"https://new.server.io:6443"


```
KUBECONFIG=~/.kube/tmp/config.new:~/.kube/tmp/config.old kubectl config view --flatten > config.merge
cat config.merge | yq '.clusters | .[0].cluster.server' 
```

"https://new.server.io:6443"

**Comment by zzswang** [comment]
the test configs

[config.zip](https://github.com/alexellis/k3sup/files/6161253/config.zip)

**Comment by alexellis** [comment]
Is this is all unrelated to your original error?

**Comment by zzswang** [comment]
We can reproduce it by these steps:

1. setup 3 nodes, or just one node
2. k3sup install
3. destroy these nodes
4. re-setup 3 nodes
5.  k3sup install with --merge option, same cluster name with step 2.

The bug is:

in step 2, a kube config was generated, then in step 5, a new kube config was generated and merged the old one, but in wrong order. At last the merged config holds certs generated in step 2.

**Comment by alexellis** [comment]
This doesn't seem like an ordering issue to me. It seems like a lack of hygiene. You should be deleting clusters from your kubeconfig file if you delete them, not overwriting and expecting everything to be fine.

I still don't understand how a merge can have a "wrong order"?

**Comment by zzswang** [comment]
It happened while you reinstall the cluster with same context name. ( To me, we have a nolocalhost dev cluster, which will be reinstalled every night by ansible scripts)

Yes, This doesn't happen often. But just put it in the "right order", it will benefit this case. Why not? 😄 

The right order means, the context in old config should be replaced with the new one. 

Currently, it will keep part of the old config, break things.

**Comment by zzswang** [comment]
Let me have a try, while install multi master k3s with '--merge' option.

**Comment by zzswang** [comment]
Following steps show another failed case:

1. install first master

```
k3sup install \
    --ip 192.168.102.11 \
    --user root \
    --context some_cluster \
    --local-path ~/.kube/config --merge \
    --k3s-extra-args '--tls-san {{ k8s_lb }} --node-label svccontroller.k3s.cattle.io/enablelb=true' \
    --cluster
```

2. install anther masters

```
k3sup join \
    --ip "{{ ansible_host }}" \
    --user "{{ ansible_user }}" \
    --server-user "{{ ansible_user }}" \
    --server-ip 192.168.102.11 \
    --k3s-extra-args '--tls-san {{ k8s_lb }} --node-label svccontroller.k3s.cattle.io/enablelb=true' \
    --server
```

3. update config file with load-balance

```
k3sup install --skip-install \
    --ip "{{ k8s_lb }}" \
    --user root \
    --context some_cluster \
     --local-path ~/.kube/config --merge \
    --k3s-extra-args '--tls-san {{ k8s_lb }} --node-label svccontroller.k3s.cattle.io/enablelb=true' \
    --cluster
```

After step 3, cluster server in ~/.kube/config is wrong

```
server: https://192.168.102.11:6443
```

Expected

```
server: https://{{ k8s_lb }}:6443
```

**Comment by zzswang** [comment]
The merge order is explained here:

https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files

```
The first file to set a particular value or map key wins.
```

**Comment by vcubells** [comment]
Hi

I had the same error and I found a simple solution.

1. Edit your ~/.kube/config file and delete every section referencing your k3s context. (Note, kubectx -d <context> isn't deleting all the lines relate to it)

2. After that, execute again:
```
k3sup install --skip-install \
  --ip $SERVER_IP \
  --user pi \
  --merge \
  --local-path $HOME/.kube/config \
  --context my-k3s
```

3. Set your context
```
export KUBECONFIG=~/.kube/config
kubectl config set-context my-k3s
```

4. Get your nodes

`kubectl get node -o wide`

That's all.

I hope this helps anyone with the same problem.
