### ISSUE TITLE
[Feature Request] Krypton support

### ISSUE THREAD

**Issue by parsec** [alexellis/k3sup#318]
Anyone using Krypton to store their SSH private key on their phone for 2FA is currently unable to use `k3sup` with that private key, because somehow the SSH implementation in `k3sup` bypasses the way Krypton reroutes SSH calls. 

## Expected Behaviour

Usually when I use SSH with Krypton and the `kr` CLI utility it's seamless. It redirects any calls to the OpenSSH client over to `krssh`, where it requests approval from the Krypton app on my phone to use the private key. It accomplishes this by adding the following to the `~/.ssh/config` file:

```
# Added by Krypton
Host *
	IdentityAgent ~/.kr/krd-agent.sock
	ProxyCommand /usr/local/bin/krssh %h %p
	IdentityFile ~/.ssh/id_krypton
	IdentityFile ~/.ssh/id_ed25519
	IdentityFile ~/.ssh/id_rsa
	IdentityFile ~/.ssh/id_ecdsa
	IdentityFile ~/.ssh/id_dsa%
```
What is supposed to happen is something similar to the following.
```

❯ ssh me.krypt.co
Krypton ▶ Requesting SSH authentication from phone
Krypton ▶ Phone approval required. Respond using the Krypton app
Krypton ▶ Success. Request Allowed ✔


                ''....''
          '.-:/++++++++++/:-.'
       '-/++++++++++++++++++++/-'
     ':+++++++++++++++++++++++++/:'
     :++++++++++/:----:/++++++++++:
     :+++++++/-'        '-/+++++++:     _                               _
     :++++++/   -/++++\-  '/++++++:    | | __   _ __   _   _    _ __   | |_       ___    ___
     :+++++/   /++++++++\  '/+++++:    | |/ /  | '__| | | | |  | '_ \  | __|     / __|  / _ \
     :+++++:  :++++++++++:  :+++++:    |   <   | |    | |_| |  | |_) | | |_   _ | (__  | (_) |
     :+++++/  \++++++++++/  /+++++:    |_|\_\  |_|     \__, |  | .__/   \__| (_) \___|  \___/
     :++++++-   \++++++/   -++++++:                    |___/   |_|
     :+++++++:   '----'   :+++++++:
     .+++++++++/-......-/+++++++++.
      ./++++++++++++++++++++++++/.
       ':/++++++++++++++++++++/:'
         '-:/++++++++++++++/:-'
             .-://++++//:-.
                  '..'


Hello $user!

You have successfully authenticated to the KryptCo test server!
Add your key to GitHub by typing 'kr github'. Type 'kr' to see all available commands.

Connection to me.krypt.co closed.
```
Though, in this case it would be an open SSH connection to the host and then `k3sup` would do whatever it needs to and close the connection.

## Current Behaviour

Currently, however, this does not happen. Instead, k3sup returns the following error:

```
❯ k3sup install --ip $ip --local-path ~/.kube/config --print-config --user $user
Running: k3sup install
2021/03/25 01:36:45 $ip
Public IP: $ip
Error: unable to load the ssh key with path "/Users/$user/.ssh/id_rsa": unable to parse private key: ssh: no key found

### NOTE: I scrubbed the output, so the path to my SSH key isn't actually trying to use $user
```

I'm not entirely sure why, but for some reason when `k3sup` calls the SSH agent, it's not getting redirected via the SSH configuration setup by Krypton. This may be that it's directly calling `ssh-agent` instead of just invoking the `ssh` command from the OS (have not tried to confirm this, but it seems plausible).

## Possible Solution

I'm not entirely sure at this point, but it seems possible that whatever Go module `k3sup` uses to call SSH is calling `ssh-agent` directly and not the OS' `ssh` command, which seems to bypass the `~/.ssh/config` file.

## Steps to Reproduce (for bugs)

1. Setup Krypton w/ Developer mode (https://krypt.co/)
2. Install the `kr` CLI util (instruction also on https://krypt.co/)
3. Pair device with `kr`
4. Run `kr sshconfig` to make sure Krypton is intercepting SSH calls
    * You'll want to make sure you don't have any private keys setup, by the way. Krypton is designed to function without needing any private keys on the local machine at all.
5. Attempt to run `k3sup install` on a remote host
6. You'll get the `Error: unable to load the ssh key with path "/Users/p4rsec/.ssh/id_rsa": unable to parse private key: ssh: no key found`

## Context

I use Krypton to keep my SSH private key secured on my phone. This lets me have 2FA on my SSH key for things like Github, and also makes my SSH key portable since it's stored on my phone (I tend to switch around hosts somewhat randomly so being able to just pair the `kr`utility to my Krypton app is quite a pleasant experience).

It's not an absolute deal breaker if this isn't something worth dedicating time to, but it's extremely strange that it's having trouble. 

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```
**v1.20.4+k3s1**

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
    **Ubuntu 20.04 LTS on a Hades Canyon NUC (Intel i7 8809-G, 16GB RAM)**

* Operating System and version (e.g. Linux, Windows, MacOS):
    Host: **Ubuntu 20.04 LTS**
    Dev/control machine: **macOS 11.2**

```
uname -a

cat /etc/os-release
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes

**Comment by parsec** [comment]
It does look like the following issues reference similar/almost identical configurations:

#311, #304, #255

As well as this WIP PR:

#312

I can close this if need be but will leave open for now so it's clear what all might be solved by PR #312

**Comment by alexellis** [comment]
Thanks for your interest in k3sup. It looks like using the SSH agent may help you. Do you want to try the open PR by @johnmccabe?

**Comment by johnmccabe** [comment]
I'll be able to get back to the PR Saturday for the outstanding join update/testing.

**Comment by parsec** [comment]
> Thanks for your interest in k3sup. It looks like using the SSH agent may help you. Do you want to try the open PR by @johnmccabe?

yeah I can try making the modification this evening and building a test version to see if that also resolves the issue. It sounds like it's the same thing others were experiencing with smart cards and other alternative auth methods so will probably work. will provide feedback when I've had a chance to try it

**Comment by parsec** [comment]
I just had the chance to check this out. I cloned @johnmccabe's repo and checked out his branch for the #311 fix and built the binary.

Now when I run `k3sup install` there's a slight pause and then it again complains about no i`d_rsa` file existing. It may be that Krypton is even slightly different from how things like the Yubikey handle the `ssh-agent`.

**Comment by parsec** [comment]
Perhaps a solution would be to write a function (or modify the current call to `ssh-agent`) that will check for and, if found, ingest the SSH config file at the default location `~/.ssh/config`

I might play with this later. Not sure if it's better to wait until John finishes his PR and that gets merged or what, though. Any thoughts?

**Comment by johnmccabe** [comment]
As an FYI, it looks like Krypton is dead (no updates in a very long time). It's being replaced by Akamai MFA which will have a community version.

https://github.com/kryptco/kr/issues/321#issuecomment-803499487

**Comment by parsec** [comment]
I hadn't even noticed that to be honest. That's sad to hear. Hopefully Akamai does a good job with it. Is there any point in leaving this issue open then? Or do y'all think this might benefit from a PR that does the above possible fix (which might end up being preliminary maintenance for things like this in the future)? 

I haven't looked too much into the go package k3sup uses to call SSH. I need to sit down and actually take a look to understand better what k3sup is using to make sure I'm understanding things correctly so I can actually help contribute instead if just throwing out ideas :)

**Comment by johnmccabe** [comment]
Can you try using my branch again (no need to pull in the recent changes, they're just for join), set this envvar before running `k3sup`:

    export SSH_AUTH_SOCK=~/.kr/krd-agent.sock

If that works it would be possible to tweak the sshAgentOnly() function in my PR to also check for the `~/.ssh/config` file (which may not exist) for a configured identity agent - and use that if the SSH_AUTH_SOCK is not explicitly set.

**Comment by johnmccabe** [comment]
Just tested this and it does work with Krypton. I can tweak the PR as I described above, or leave that for you to raise a PR for it once the agent PR is merged.

**Comment by parsec** [comment]
sorry for not responding sooner. work has been crazy this week, haven't really had the energy to mess with it. lots of free time this weekend though.

i'm fine with either honestly. more than happy to contribute :) however you want to do it, I'm not particularly partial either way. definitely willing to submit a PR to handle an `~/.ssh/config` feature.

**Comment by parsec** [comment]
it looks like the latest release may have resolved this. I'll test it this evening, and if not I'll start working on a PR for it.

**Comment by parsec** [comment]
looks like it still doesn't work... need to sit down and see what else I can try to get it working.

`parsec@nostromo:/mnt/c/Users/Forer$ k3sup install --ip 10.0.0.226 --user parsec --k3s-extra-args '--no-deploy traefik'
Running: k3sup install
2021/05/28 13:15:12 10.0.0.226
Public IP: 10.0.0.226
Error: unable to load the ssh key with path "/home/parsec/.ssh/id_rsa": unable to read file: /home/parsec/.ssh/id_rsa, open /home/parsec/.ssh/id_rsa: no such file or directory
parsec@nostromo:/mnt/c/Users/Forer$ k3sup version
 _    _____
| | _|___ / ___ _   _ _ __
| |/ / |_ \/ __| | | | '_ \
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/
                     |_|
Version: 0.11.0
Git Commit: fd9dfea

Give your support to k3sup via GitHub Sponsors:

https://github.com/sponsors/alexellis
parsec@nostromo:/mnt/c/Users/Forer$`

**Comment by alexellis** [comment]
From @johnmccabe "Just tested this and it does work with Krypton."

Closing as resolved.
