### ISSUE TITLE
Cannot join a second master server for a HA cluster

### ISSUE THREAD

**Issue by ywiyogo** [alexellis/k3sup#320]
I followed this instruction https://blog.alexellis.io/multi-master-ha-kubernetes-in-5-minutes/. However, I cannot add the second and the third master server.
The first server cluster can be created successfully.

## Expected Behaviour

Running the join server 
```
k3sup join \
  --server \
  --ip $NODE_2 \
  --user $USER \
  --server-user $USER \
  --server-ip $NODE_1
```
shall finished.

[INFO]  systemd: Enabling k3s unit
[INFO]  systemd: Starting k3s
 Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.

## Current Behaviour

[INFO]  systemd: Enabling k3s unit
[INFO]  systemd: Starting k3s

After the above log, the process hangs and the new line created symlink doesn't show.

## Steps to Reproduce (for bugs)

1. Create a first cluster server
2. Join the second server

## Context

If I try to join  the two server as the node agents it works without any hangs or issue.

## Your Environment

* What Kubernetes distribution are you using? k3s
The three target servers has Debian 10 OS

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9+k3s1", GitCommit:"bead080d5e564206c23dcfbea3e6cf6f316e7f6c", GitTreeState:"clean", BuildDate:"2021-03-31T05:51:05Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`): cluster has 3 Debian 10, my host PC has PopOS(Ubuntu 20)

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux master1 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux x86_64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes

## Are you a GitHub Sponsor (Yes/No?)

No

https://github.com/sponsors/alexellis

**Comment by alexellis** [comment]
Hi, there are no changes in k3sup or k3s that I'm aware of and this feature has been tested extensively.

If you're having issues, then you may be better off trying the tutorial as specified with Ubuntu, instead of customising the OS from the beginning.

FYI to debug what's going wrong, run `sudo systemctl status k3s` on your node. Use `g` and `G` to skip between the top and bottom of the logs.

K3sup only installs K3s, which is proven to still be working as expected, so we cannot help individuals debug K3s, but you can ask Rancher in their Slack forums or GitHub issue tracker for help.

https://slack.rancher.io/
https://github.com/k3s-io/k3s

Alex

**Comment by ywiyogo** [comment]
@alexellis thanks for your reply and the links.
After creating an external mysql DB it works now. The join server with the embedded etcd doesn't work for my Debian 10 server.

**Comment by ccesare** [comment]
In my case, there was a firewall issue (the second node could not reach the etcd service on the first). After explicitly allowing that traffic and restarting k3s on the second node, it joined the cluster. The third node joined without a hitch.

**Comment by omidraha** [comment]
https://docs.k3s.io/installation/requirements#inbound-rules-for-k3s-server-nodes
