### ISSUE TITLE
Honour the --skip-install flag with --local

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#321]
## Expected Behaviour

The `--local` flag for `k3sup install` doesn't honour `--skip-install`. 

## Current Behaviour

`--skip-install` should allow the user to get the correct kubeconfig, without doing an installation

## Possible Solution

Add an if statement

## Steps to Reproduce (for bugs)

1. `k3sup install --local --skip-install`
2. See that it still installs

**Comment by alexellis** [comment]
/add label: good first issue, help wanted

**Comment by alexellis** [comment]
Hey @Jasstkn, would you be interested in taking this on? I think it'd be a quick win for you.

**Comment by Jasstkn** [comment]
> Hey @Jasstkn, would you be interested in taking this on? I think it'd be a quick win for you.

Hey! Yes, I would like to try :)

**Comment by Jasstkn** [comment]
@alexellis @Shikachuu hey. I started looking into the issue and want to reproduce it. I created a VM in GCP and trying to install k8s cluster via command:
```
export IP=12.34.56.78
./k3sup install --host-ip $IP --user mariarti --ssh-key ~/.ssh/general.pub
Error: trying to get ip value of flag of type string
```

But it fails with unexpected result. I'm trying to debug it but nothing useful so far. Maybe you have some suggestions where to look?

**Comment by alexellis** [comment]
This may be an unintentional regression.  Can you check my previous commit?

**Comment by alexellis** [comment]
@Jasstkn if `k3sup install --local --skip-install` is actually skipping the installation of k3sup now, then I'd say we can close this issue.

Nobody's comment on #389 yet to say that they've started working on it. There are two parts to it with the second being more involved (as per the screenshot).
