### ISSUE TITLE
Error: unknown flag: --no-extras

### ISSUE THREAD

**Issue by houshym** [alexellis/k3sup#322]
I run following command and I am getting error  "Error: unknown flag: --no-extras"
k3sup join \
  --server \
  --ip $NODE_2 \
  --user $USER \
  --server-user $USER \
  --server-ip $NODE_1 \
  --no-extras

**Comment by houshym** [comment]
--no-extras glag is for k3sup install and not for k3sup join

**Comment by alexellis** [comment]
Correct 🙂

Glad that you are enjoying k3sup. Please think about becoming a sponsor to support the project

**Comment by houshym** [comment]
Sure I will do my best. at least I can share my experience. the following
code deploy traefik and does not work as I expect
k3sup install \
--cluster \
--k3s-extra-args '--no-deploy servicelb traefik' \
--context skyline-k3s \
--user $USER \
--ip $NODE_1 \
