### ISSUE TITLE
Naming of assets

### ISSUE THREAD

**Issue by drzero42** [alexellis/k3sup#323]
There is a really nice tool to install single-binary releases from Github with a single command, and keep them updated. It is called [bin](https://github.com/marcosnils/bin). It will automatically figure out the Arch for the machine it is running on, and download the correct asset from the latest release.

The releases for k3sup contains assets for multiple arches, which are indicated in their names. However, the asset for 64-bit Linux is just named `k3sup`.

This may be convenient for downloading with `curl`/`wget`, as 64-bit Linux users do not need to rename the file after downloading, and the majority of users are very likely to be 64-bit Linux users.

It unfortunately also makes it impossible for an automated tool like `bin` to figure out which asset to download (as discussed [here](https://github.com/marcosnils/bin/issues/96)), for users on 64-bit Linux. Would you consider adding the arch to the name of the asset in future releases?

**Comment by alexellis** [comment]
Thanks for your interest, but we already have support for this in arkade and brew. The release names are automated across k3sup, arkade, inlets/pro, openfaas and other projects maintained by the openfaas community, so we're unlikely to change this given those two reasons.

> There is a really nice tool to install single-binary releases from Github with a single command, and keep them updated. It is called bin. It will automatically figure out the Arch for the machine it is running on, and download the correct asset from the latest release.

That's exactly what arkade does, and arkade supports k3sup too.

Not only are k3sup and arkade available on arkade, but brew too.

https://github.com/alexellis/homebrew-alexellis
https://github.com/alexellis/arkade

Example:

```bash
arkade get k3sup
```

Arkade specifically has the ability to set Go templates for each app, and does not require maintainers to change the names of their binaries which is a breaking change for consumers.
