### ISSUE TITLE
--k3s-extra-args "--no-deploy servicelb traefik"  does not work as expected

### ISSUE THREAD

**Issue by houshym** [alexellis/k3sup#324]
why the following script installs traefik and servicelb. I checked with '--k3s-extra-args "--no-deploy servicelb traefik' too.

k3sup install \
  --cluster \
  --k3s-extra-args "--no-deploy servicelb traefik" \
  --context skyline-k3s \
  --user $USER \
  --ip $NODE_1 \
  

echo "wait for master cluster is up and running"
sleep 60
# The second node joins
k3sup join \
  --server \
  --k3s-extra-args "--no-deploy servicelb traefik" \
  --ip $NODE_2 \
  --user $USER \
  --server-user $USER \
  --server-ip $NODE_1 \

**Comment by houshym** [comment]
I tried with --k3s-extra-args '--disable servicelb traefik' and I got same problem. it installs traefik and servicelb

**Comment by dvmrry** [comment]
I see this is kind of late at this point and hope you've already figured it out, but using `--k3s-extra-args "--no-deploy servicelb --no-deploy traefik` will likely resolve this for you.

**Comment by trallnag** [comment]
You can also use the following option

```
--no-extras               Disable "servicelb" and "traefik"
```

**Comment by trallnag** [comment]
@dvmrry, the flag `--no-deploy` is deprecated.

>To disable it, start each server with the --disable traefik option.

**Comment by alexellis** [comment]
@trallnag thanks for the comment. What version was that removed in?

k3sup can install any k3s version, so "deprecated" means different things to different versions

**Comment by alexellis** [comment]
@houshym I've just noticed that you haven't used the issue template, so I'm going to close this one.

If someone wants to open a better issue and fill out all the fields, I'm sure someone would be willing to help.

**Comment by thiscantbeserious** [comment]
I you use --disable traefik with k3sup it actually puts --disable and traefik on a new line without an whitespace character inbetween for the related systemd service exec params:

````
    server \
        '--cluster-init' \
        '--tls-san' \
        '192.168.10.10' \
        '--disable' \
        'traefik' \

````


So that's actually a bug with k3sup I'd guess.
