### ISSUE TITLE
Provide some documentation on the README about lack of ssh config support

### ISSUE THREAD

**Issue by xaocon** [alexellis/k3sup#329]
Currently k3sup doesn't use any information from the ssh config. This looks like it won't be trivial to enable and I suspect will be implemented soon. I think it would be helpful to note this in the README and give some workaround details.

## Expected Behaviour
Any host you can ssh to you can k3sup to

## Current Behaviour
Hosts that require ssh config information to be reachable fail

## Possible Solution
Long term it would be nice if k3sup simply worked with the ssh config like users kind of expect but it looks like a lot of work and would probably have edge cases that would be even more work.

Short term, and the recommendation for this issue, is just to make users aware of the gotcha up front and provide some guidance on working around the problem. As long as there aren't a number of problems with `--local` installs should be a much better experience for many users with minimal effort.

## Context
There are a number of open issues tracking problems related to this #304, #306, #318. 

So, I don't know golang but it looks like k3sup uses a fairly low level ssh lib which doesn't support parsing the ssh config. There is a lib [here](https://github.com/mikkeloscar/sshconfig) that parses but it doesn't seem to support everything and doesn't seem to set up crypto/ssh in any way. I suspect this won't be super easy to implement. It may be worthwhile to simply add something to the README about ssh config not working and noting any differences when installing locally. That way people could simply copy the bin over and run it over ssh with `--local` instead.

I'm not aware of any gotchas with using `--local` but if there are any it would be worth nothing them as well. My first thoughts are maybe users would need to manage the token for clusters or something but IDK. Either way, knowing about any limitations will allow users to help themselves.

## Your Environment
I don't think any of this really applies to this issue but i'll add anyways
* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-dispatcher", GitCommit:"a39a896b5018d0c800124a36757433c660fd0880", GitTreeState:"clean", BuildDate:"2021-01-28T22:06:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Ubuntu 20.04 TLS images hosted in GCP. Trying to get [multi master with embedded etcd working](https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-embedded-etcd)
* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes, happy to take a first crack at it. Would appreciate any thoughts about problems users could run into using `--local`

## Are you a GitHub Sponsor (Yes/No?)

https://github.com/sponsors/alexellis
No, thank you for your work though.

**Comment by alexellis** [comment]
Hi, what specific information is in your config file that k3sup cannot support today?

Thanks,

Alex

**Comment by xaocon** [comment]
Well, I may not be right about all these but it would seem that some important ones that don't seem to be supported are `Host`, `HostName`, `HostKeyAlias`, `ProxyCommand`, and I'm guessing `IdentityFile`, `UserKnownHostsFile`,  and `IdentitiesOnly` as well.

Some of these can be worked around using flags available in k3sup but, as far as I know, there isn't a good way around `ProxyCommand` which is a pretty important one.

I was able get things to work by ssh'ing to a node, doing a local install, then ssh'ing to each other node, adding their own ssh key to their own auth and then performing the install on 127.0.0.1. Seems to be working ok but haven't done a lot of testing.

It would have been helpful to have seen in the docs about the ssh limitations (or whatever secret sauce is needed to get them to work as expected) and maybe have it pointed out that `--local` didn't exist for `join` and that you'd need to plan to have the system ssh to itself.

**Comment by xaocon** [comment]
As I said, I'm happy to make a PR for this. Just want to get feedback from you first on if you agree with my assessment of the situation and you'd accept such a PR.

**Comment by alexellis** [comment]
Nobody else has reported this problem in the history of k3sup, so I am not sure how important it is. What I'm going to do is to close as #wontfix and leave this issue unlocked, so if we start to see a lot of demand, we can reconsider prioritising it.

The hostname is supported via `--host`. an identity file is already supported also.

The proxy command is not, but I wonder if the new changes merged in 0.11.0 to use an ssh-agent can resolve all of this anyway?

**Comment by xaocon** [comment]
It's up to you of course but I was really only hoping there'd be some
documentation so it would be easier for others to figure out how to install
in unusual situations. Something as simple mentioning ProxyCommand doesn't
work in the FAQ would have worked for me.

It would have saved me a lot of time coming up with the right way to use
the tool in my situation if I didn't have to dig through issues and code to
figure out why it wasn't working for me.

Either way, I really appreciate all the work you do and if you decide you
want a PR for it in the future feel free to ping me here.

**Comment by bayeslearner** [comment]
Just want to confirm k3sup do not use ssh config file as   I'm a bit confused about the conclusion of this conversation.  I'm moving from k3d to k3sup due to performance, stability, and persistent storage issues of k3d.   Planning to use vagrant to setup k3s nodes and they need special ssh configs to connect from host instead of IPs+ports.

**Comment by xaocon** [comment]
This conversation was only about documenting the fact that ssh config isn't used.

**Comment by airtonix** [comment]
confused why this was marked as `#wontfix` seems to be a way to discourage people from discussing it or bothering to turn up with a `+1`.

my use case is to make provisioning even easier by wrapping k3sup behind a cli that only requires a valid ssh connection string.

imagine:

```sh
provision () {
  requires "$1" "Must provide either master|slave"
  requires "$2" "Missing ssh connection"

  case "$1" in
    "master")
      k3sup install "$2"
    ;;
    "slave")
      k3sup join "$2"
    ;;
  esac
}
```

I want: 

```sh
mytool provision master user@hostname
```

or 


```sh
mytool provision master alias_found_in_home_ssh_config
```


But right now I have to make the user provide all those values, and like @xaocon says... if making an ssh connection to the host requires more than your individual arguments support, then... we're out of luck.


I haven't dived in the guts of k3sup yet, but is this because you're using some kind of golang based re-implementation of ssh rather than some kind of os.exec approach ?

**Comment by alexellis** [comment]
All supported configuration is via flags or SSH agent. If you want to ask for support and features, become a sponsor

**Comment by alexellis** [comment]
/set title: What SSH features are supported?
