### ISSUE TITLE
[Documentation] Please clarify possible architecture

### ISSUE THREAD

**Issue by tcurdt** [alexellis/k3sup#33]
From the README it sounds like I could run a k3s server on a RPi at home and then have an EC2 instance and some other VPS join as agents. Basically spanning a kubernetes cluster across multiple networks around the world. Is that what you are trying to say?

## Expected Behaviour

It would be nice if the examples could be a more explicit on the details. Especially the networking part.

## Current Behaviour

> Conceptual architecture, showing k3sup running locally against any VM such as AWS EC2 or a VPS such as DigitalOcean

## Possible Solution

> In the demo I install Kubernetes (k3s) onto two separate machines and get my kubeconfig downloaded to my laptop each time in around one minute.

It would be great to have a little visualization here.

Note: It's obvious that running the master a laptop is no production deployment - but it sure is interesting to experiment with the effect of the master going away.

## Steps to Reproduce (for bugs)

NA

## Context

NA

## Your Environment

NA

# Additional note

Great project :)

**Comment by alexellis** [comment]
Thank you for your feedback and for using `k3sup` 😄 

> It would be great to have a little visualization here.

This is the video.

> From the README it sounds like I could run a k3s server on a RPi at home and then have an EC2 instance and some other VPS join as agents. Basically spanning a kubernetes cluster across multiple networks around the world. Is that what you are trying to say?

If you have a VPN, then sure, but no, it just means you can use multiple different kind of devices as targets.

If you have additional thoughts, please join Slack and `#inlets`

**Comment by tcurdt** [comment]
Would you be open to a PR for the README?
Thanks for the slack link. See you there!
