### ISSUE TITLE
Support HA control-plane IP/address

### ISSUE THREAD

**Issue by msnelling** [alexellis/k3sup#332]
When creating a multi-master HA install, the created `kubeconfig` file has the IP address of the primary master (the node where the `--cluster` flag was used in installing the agent).

## Expected Behaviour
Provide an option to override the IP or FQDN of the load balanced contol-plane API that is written to the `kubeconfig` file.

## Current Behaviour
When installing in cluster mode the address of the initial master node is written to the `kubeconfig` file.

## Possible Solution
Add a `--cluster-api-address` to override the address written to the `kubeconfig`.

## Your Environment
* What Kubernetes distribution are you using?
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`): VMware Photon OS 4.0 VMs running on ESXi 7.0.2
* Operating System and version (e.g. Linux, Windows, MacOS): macOS 11.3.1
```
Darwin #####.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```
## "Be part of the solution"
Subject to approval, are you willing to work on a Pull Request for this issue or feature request?
No
## Are you a GitHub Sponsor (Yes/No?)
No

**Comment by alexellis** [comment]
This is already available via `--tls-san`
