### ISSUE TITLE
Support Adding HA Nodes on k3s v.1.21.3+k3s1 Token required joining server with external data store 

### ISSUE THREAD

**Issue by tamoanxx** [alexellis/k3sup#339]
## Expected Behaviour
Please reference release notes: [click here](https://github.com/k3s-io/k3s/releases/tag/v1.21.3%2Bk3s1)

⚠️ Important Upgrade Note ⚠️
If you are using K3s in a HA configuration with an external SQL datastore, and your server (control-plane) nodes were not started with the --token CLI flag, you will no longer be able to add additional K3s servers to the cluster without specifying the token. Ensure that you retain a copy of this token, as is required when restoring from backup. Previously, K3s did not enforce the use of a token when using external SQL datastores.

You may retrieve the token value from any server already joined to the cluster:

cat /var/lib/rancher/k3s/server/token

## Current Behaviour
Installation fails upon adding second node

## Are you a GitHub Sponsor (Yes/No?) 

- [X ] Yes
- [ ] No

## Possible Solution
See Above

## Steps to Reproduce
Attempt and install with latest

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [ ] Yes
- [ ] No

**Comment by alexellis** [comment]
Thanks for being a GitHub Sponsor for the note on K3s 1.12.3

FYI the link "Please reference release notes" didn't work for me, could you edit it?

Alex

**Comment by tamoanxx** [comment]
Here it is and I will update main issue section. https://github.com/k3s-io/k3s/releases/tag/v1.21.3%2Bk3s1

Thanks,
Dustin Weld
Cell:615-200-6509

**Comment by alexellis** [comment]
I'm not seeing an additional / new token mentioned at: [High Availability with an External DB](https://rancher.com/docs/k3s/latest/en/installation/ha/) despite it being mentioned in the release notes
