### ISSUE TITLE
[Feature] Different SSH options for Server and Node on Join command

### ISSUE THREAD

**Issue by OmegaSquad82** [alexellis/k3sup#34]
## Expected Behaviour
I've got systems in which the usernames of where K3S has been set up with on the Server and where it should be set up with on the node differ from each other.

## Current Behaviour
Both username and SSH port are the same for server to join and the joining node.

## Possible Solution
Implement optional flags to set up the SSH connection for the server differently. Create Flags '--server-user' and '--server-port' with empty default value and when empty set them to the same value as '--user' and '--port', respectively.

## Steps to Reproduce (for bugs)
* `k3s install --user 'pi' --ip '192.168.1.2'`
* `k3s join --user 'ubuntu' --ip '192.168.1.3' --server-user 'pi' --server-ip '192.168.1.2'`

## Context
Installing agent with k3sup locally on my laptop failed while I built a multi-architecture cluster where individual nodes either run on `armhf` or `arm64` and my laptop runs with `amd64`.

## Your Environment
* Running k3s v0.8.1 thx to k3sup on 3 devices, now.
* My TravelMate B got LinuxMint Tina with Cinnamon desktop
* Master + 2 Nodes r. Raspberry Pi 4B's w. Raspbian @ Kernel 4.19.73-v8+

**Comment by alexellis** [comment]
If you'd like to add an optional `--server-user` flag to `join` I'm fine with that 👍

**Comment by alexellis** [comment]
@OmegaSquad82

**Comment by OmegaSquad82** [comment]
Has been implemented. Thank you @simoncas for your help and @alexellis for accepting the issue. ;c)

**Comment by alexellis** [comment]
No problems. Enjoy the project!
