### ISSUE TITLE
k3sup doesn't install latest k3s version

### ISSUE THREAD

**Issue by lordigon** [alexellis/k3sup#341]
On a new Vagrant VM k3sup install a fresh new k3s cluster with version  v1.19.13+k3s1 but the latest one is v1.21.3+k3s1.

## Expected Behaviour
Creation of a k3s with latest version e.g v1.21.3+k3s1 
## Current Behaviour
k3sup install k3s with version v1.19.13+k3s1
## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [x] No

## Steps to Reproduce
1. Create vagrant machine with ubuntu 18.04
2. launched k3sup with no reference to a specific version
3. k3s version is v1.19.13+k3s1

## Your Environment

* What Kubernetes distribution are you using?

vagrant@ubuntu1804:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+k3s1", GitCommit:"99eadcc10bce2527ae1ab0964b540a4f52a53504", GitTreeState:"clean", BuildDate:"2021-07-22T20:29:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+k3s1", GitCommit:"99eadcc10bce2527ae1ab0964b540a4f52a53504", GitTreeState:"clean", BuildDate:"2021-07-22T20:29:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
A vagrant machine with Ubunut 18.04 is used as host for k3s cluster.
k3sup is used from a Docker image on my Mac.

**Comment by alexellis** [comment]
Hey please see the docs for how to run an edge or testing version, see also the channels.
