### ISSUE TITLE
Support request for installing K3s

### ISSUE THREAD

**Issue by dkirby-ms** [alexellis/k3sup#344]
Previously working deployment automation is now failing. I am running ```k3sup install``` on a fresh Ubuntu 20.04 box which results in an incomplete install without an error message. Logs below:

This was working normally until a week or so ago and now I am seeing this issue.

kubeconfig is created but is an empty file

## Expected Behaviour
Expecting install to complete or give error message as to what is failing.

## Are you a GitHub Sponsor (Yes/No?)
No

- [ ] Yes
- [X] No

## Steps to Reproduce
```
user@ranchertest:~$ sudo k3sup install --local --context arcbox-k3s --ip $publicIp --k3s-extra-args '--no-deploy traefik'
Running: k3sup install
2021/09/21 01:04:21 20.109.6.206
Executing: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --tls-san 20.109.6.206 --no-deploy traefik' INSTALL_K3S_CHANNEL='v1.19' sh -

[INFO]  Finding release for channel v1.19
[INFO]  Using v1.19.15+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.19.15+k3s1/sha256sum-amd64.txt
stdout: "[INFO]  Finding release for channel v1.19\n[INFO]  Using v1.19.15+k3s1 as release\n[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.19.15+k3s1/sha256sum-amd64.txt\n"Saving file to: /home/azureuser/kubeconfig

# Test your cluster with:
export KUBECONFIG=/home/azureuser/kubeconfig
kubectl config set-context arcbox-k3s
kubectl get node -o wide
```

## Context

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`): Azure

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04 LTS

```
uname -a
Linux ranchertest 5.8.0-1041-azure #44~20.04.1-Ubuntu SMP Fri Aug 20 20:41:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

@likamrat

**Comment by alexellis** [comment]
Hi, can you see the troubleshooting guide in the README and add the details you saw there to the issue?

K3sup is just an installer, if k3s fails to start, then that's usually a misconfiguration issue of your target system.

k3s is a daemon that starts or doesn't, the instructions will tell you why.

Alex

**Comment by alexellis** [comment]
/set title: Support request for installing K3s

**Comment by dkirby-ms** [comment]
Hi Alex, thank you for the pointers. The issue seems to have resolved itself after trying another deployment with our automation scripts this morning. Appreciate the help.
