### ISSUE TITLE
Support request for k3s-extra-args

### ISSUE THREAD

**Issue by erickbeloti** [alexellis/k3sup#350]
## Expected Behaviour

Change the default cron spec in --etcd-snapshot-schedule-cron (default: "0 */12 * * *"):
```
--k3s-extra-args '--etcd-snapshot-schedule-cron * * * * *'
```

## Current Behaviour

when I try to pass the value of the command "--etcd-snapshot-schedule-cron * * * * *" in the "--k3s-extra-args" the tool generates the command "k3s server" breaking the white spaces, making that schedule is not applied.

I also tried:
```
--k3s-extra-args '--etcd-snapshot-schedule-cron '\''* * * * *'\''
--k3s-extra-args '--etcd-snapshot-schedule-cron "* * * * *"'
```

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

I don't know how, but I know the command below works:
```
[...]
ExecStart=/usr/local/bin/k3s \
    server \
        '--cluster-init' \
        '--tls-san' \
        '192.168.0.101' \
        '--disable' \
        'local-storage' \
        '--disable' \
        'servicelb' \
        '--etcd-snapshot-schedule-cron' \
        '* * * * *' \
```

## Steps to Reproduce

1. ```k3sup install --print-command --user ubuntu --sudo --ip 192.168.0.101 --cluster --k3s-version v1.21.4+k3s1 --k3s-extra-args '--etcd-snapshot-schedule-cron * * * * *'```

print command:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --cluster-init --tls-san 192.168.0.101 --etcd-snapshot-schedule-cron * * * * *' INSTALL_K3S_VERSION='v1.21.4+k3s1' sh -
```

2. ```vim /etc/systemd/system/k3s.service```
```
[...]
ExecStart=/usr/local/bin/k3s \
    server \
        '--cluster-init' \
        '--tls-san' \
        '192.168.0.101' \
        '--disable' \
        'local-storage' \
        '--disable' \
        'servicelb' \
        '--etcd-snapshot-schedule-cron' \
        '*' \
        '*' \
        '*' \
        '*' \
        '*' \
```
3. ```k3s etcd-snapshot ls``` never shows the snapshots

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
HyperV in local cluster

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

Linux ***** 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [ ] Yes
- [x] No

**Comment by alexellis** [comment]
Hi Erick,

I noticed you deleted almost all the issue template, please edit it and fill it in properly so that we can triage your issue. The lower quality the report, the less likely it's going to get looked into, because it creates more work for myself and anyone else who might volunteer their free time to help you.

[Issue template](https://raw.githubusercontent.com/alexellis/k3sup/master/.github/ISSUE_TEMPLATE.md)

Two questions for you:

1) What does --print-command show?
2) and what are you getting in your k3s.service file?

Have a great day

Alex

**Comment by alexellis** [comment]
Thanks for giving the contents of `/etc/systemd/system/k3s.service`

What do you see in the contents of the file, if you install k3s via the command line using its helper script directly on the node instead of with k3sup?

**Comment by alexellis** [comment]
@Waterdrips are you still wanting to work on a fix for this?

**Comment by alexellis** [comment]
Closing as stale
