### ISSUE TITLE
bootstrap data already found and encrypted with different token

### ISSUE THREAD

**Issue by dragon2611** [alexellis/k3sup#351]
## Expected Behaviour
Join 2nd master

## Current Behaviour
Bootstrap error

## Are you a GitHub Sponsor (Yes/No?)

- [ ] No

## Possible Solution
Read join token data from first node to get bootstrap data (Similar to joining a worker node)

## Steps to Reproduce
Follow guide for Mysql setup - https://github.com/alexellis/k3sup/blob/master/README.md section
Create a multi-master (HA) setup with external SQL

using K3s v1.21.5+k3s2

## Context
Unable to provision secondary master via K3sup

## Your Environment
K3s v1.21.5+k3s2
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Debian / KVM VM



## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [ ] No

**Comment by Waterdrips** [comment]
Hi @dragon2611 , Thanks for the report. 

Can you add some more details, which step in that guide did you get to? What error did it give? 

This information will help in getting a quick resolution for this.

**Comment by dragon2611** [comment]
Duplicate
