### ISSUE TITLE
Kubeconfig merge error on windows

### ISSUE THREAD

**Issue by sralloza** [alexellis/k3sup#356]
## Expected Behaviour
Using `--merge` option merges the `--local-path` kubeconfig when using the `~` symbol to refer to the home directory. Using `$HOME` instead is a workaround for the first issue, but it still raises an error. More info below.

## Current Behaviour
It gives an error: `Error: Could not merge kubeconfigs: exit status 1`

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Possible Solution

1. Expand the path given by the flag `--local-path`
2. Set `KUBECONFIG `env variable to `KUBECONFIG1;KUBECONFIG2` in windows (use `;` instead of `:`). Absolute paths in windows already contains colons (like `C:/`). [StackOverflow Ref](https://stackoverflow.com/questions/59646859/merging-multiple-kubeconfig-files-on-windows)
3. Close the temporary file before removing it, otherwise it raises an error.

After applying the three changes it merges the kubeconfigs as expected.

Note: using `--local-path $HOME/.kube/config` instead of `--local-path ~/.kube/config` is a workaround for the expand path issue, but it still raises an error related to the second fix (using `;` instead of `:`)

## Steps to Reproduce

1. In Windows, lunch `k3sup --local-path ~/.kube.config`

Note: this is the command I really use:
```
k3sup install --context XXXX --host-ip XXX --merge --user XXX--ip XXX --local-path ~/.kube/config --k3s-extra-args '--write-kubeconfig-mode=644 --disable traefik' --k3s-version v1.22.2+k3s2
```

## Context

I want to get the kubeconfig after launching the cluster using my Windows machine.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s2", GitCommit:"3f5774b41eb475eb10c93bb0ce58459a6f777c5f", GitTreeState:"clean", BuildDate:"2021-10-05T20:30:06Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

Raspberry Pi 4

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```
Windows 10 Home version 21H1 (OS compilation 19043.1288)

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [x] Yes
- [ ] No

**Comment by alexellis** [comment]
@sralloza thanks for reporting this problem that you ran into. Are you using git bash as required by the README?

**Comment by sralloza** [comment]
No, I didn't see any reference to git bash in the README. I downloaded the exe from the latest release.

**Comment by sralloza** [comment]
I have tested the program with git bash. The first error (using `~`) is solved, but the second (using `;` instead of `:` to join the kubeconfig paths in the env var) is still there:

```
Merging with existing kubeconfig at C:\Users\srall\.kube\config
Error: Could not merge kubeconfigs: exit status 1
```

**Comment by sralloza** [comment]
I'd like to use the same `k3sup` command on any platform using `~`. Are you willing to implement this support as it only needs to add a call to `expandPath`?

**Comment by alexellis** [comment]
No reason why not @sralloza, however I need to prioritise GitHub Sponsors (which you are not, see the README for more) and my time on this project is in no way funded.

**Comment by alexellis** [comment]
#357 merged

**Comment by sralloza** [comment]
I totally get it, github sponsors have priority. Thanks for the merge!
