### ISSUE TITLE
How to uninstall k3sup?

### ISSUE THREAD

**Issue by diogosalazar** [alexellis/k3sup#363]
How do I remove k3sup from my system? Thanks.

**Comment by jbpratt** [comment]
linking this PR https://github.com/alexellis/k3sup/pull/285

**Comment by alexellis** [comment]
Do you mean K3sup? Just remove the binary you downloaded.

If you want to remove K3s and not K3sup (it's not clear which you mean), then see the [K3s docs](https://rancher.com/docs/k3s/latest/en/)

Closing as resolved.

**Comment by alexellis** [comment]
@jbpratt thanks for lending your time to try and help other users.

If you're a K3s supporter or user, please consider becoming a sponsor via GitHub. There's a bit red button on this repository.

**Comment by bplein** [comment]
Pardon me for reviving an old issue, but the K3s uninstall instructions at https://rancher.com/docs/k3s/latest/en/installation/uninstall/ say to run `/usr/local/bin/k3s-uninstall.sh` but that doesn't exist on the k3sup-installed nodes I run.
