### ISSUE TITLE
`get.sh` doesn't work with apple silicon

### ISSUE THREAD

**Issue by TomTucka** [alexellis/k3sup#364]
## Expected Behaviour

running the following install scripts should install the correct binary for the hardware within the laptop

```
curl -sLS https://get.k3sup.dev | sh
sudo install k3sup /usr/local/bin/

k3sup --help
```

## Current Behaviour

Running `curl -sLS https://get.k3sup.dev | sh` installs the Darwin binary 
`uname` returns darwin for both intel and m1 macs

## Are you a GitHub Sponsor (Yes/No?)

- [x] Yes
- [ ] No

## Possible Solution

Change to using `uname -m` which outputs the machine hardware name or `uname -p` which outputs the processor

## Steps to Reproduce

1. Run install script on M1 Mac

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [X] Yes
- [ ] No

**Comment by rgee0** [comment]
This will likely be an issue across most of the projects that use a `get.sh`

**Comment by TomTucka** [comment]
> This will likely be an issue across most of the projects that use a `get.sh`.
> 
> Suggest the fix will follow a similar pattern to that inside the `Linux` codeblock.

Ah didn't see the linux block... I can open a pr for this.

**Comment by TomTucka** [comment]
Fixed in #365

**Comment by alexellis** [comment]
I tend to type in `bash` then run the command on newer MacOS versions, this isn't specifically about M1s, but the choice of shell not supporting curl | sh.

**Comment by alexellis** [comment]
I guess I'm probably using Rosetta.

I originally thought you may have been having issues with `curl | sudo sh` which doesn't work on the newer shell on MacOS, but works if you type `bash` first.

**Comment by alexellis** [comment]
I worked on this to fix a couple of missed use-cases in the original PR.

Thanks for your input on it.

**Comment by alexellis** [comment]
I thought this had been done already, I'm checking.

**Comment by rgee0** [comment]
#365 refers. It’s awaiting a merge. Can’t see the equivalent in get.sh on main
