### ISSUE TITLE
--token flag no longer supported, should be --k3s-extra-args '--token'

### ISSUE THREAD

**Issue by Vashiru** [alexellis/k3sup#367]
## General description
The readme for "Create a multi-master HA setup with external SQL" states that the servers should be installed using `--token`. This flag is however no longer present in k3sup. Instead --k3s-extra-args "--token ${TOKEN}" should be used.

Side node: `tr -dc A-Za-z0-9 </dev/urandom | head -c 64` returns `tr: Illegal byte sequence` - to proceed I installed the first server without '--token', signed in with SSH to the first server, grabbed the token from the file and then passed it in the k3s-extra-args for the second server.

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution
Update the documentation to reflect current status

## Context
Attempting to install a multi-master HA setup with an external SQL server

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [X] Yes
- [ ] No

**Comment by alexellis** [comment]
Hi @Vashiru 

>  This flag is however no longer present in k3sup.

As far as I know, this was recently added by @Waterdrips 

Are you sure that you're using the latest version of k3sup?

Alex

**Comment by Waterdrips** [comment]
https://rancher.com/docs/k3s/latest/en/installation/ha/#2-launch-server-nodes 

latest docs (as of 07/01/2022) shows --token

**Comment by Vashiru** [comment]
> https://rancher.com/docs/k3s/latest/en/installation/ha/#2-launch-server-nodes
> 
> latest docs (as of 07/01/2022) shows --token

Yes that's 

> Hi @Vashiru
> 
> > This flag is however no longer present in k3sup.
> 
> As far as I know, this was recently added by @Waterdrips
> 
> Are you sure that you're using the latest version of k3sup?
> 
> Alex

My bad, that's in fact VERY recent. I'm running 0.11.1, and it was added in 0.11.2.

Interesting note though, I ran `curl -sLS https://get.k3sup.dev | sh` on the 26th of December on my M1 Macbook and it installed 0.11.1, even though 0.11.2 was released on the 16th of december (according to the Github releases).
