### ISSUE TITLE
Certificate problem after installing k3s on AWS with k3sup

### ISSUE THREAD

**Issue by gilsim** [alexellis/k3sup#37]
I'm having a problem after installing k3s on AWS using k3sup, any kubectl gets "Failed to connect to proxy error=x509: certificate signed by unknown authority". 
 The k3s on the server works fine, including the cluster with multiple nodes, as I can see by ssh to the server, but local kubectl with the kubeconfig file gets the above result.
I think that this problem is new, as I did the same procedure a while ago and there was no problem.
 I was told on the rancher slack channel to rotate the certificates using the rancher UI (don't yet know how) but as I installed it using k3sup I thought I could get other insights here.
Anyone have any idea?

* Operating System:
Ubuntu on both my laptop and AWS instance.

**Comment by gilsim** [comment]
I found the problem, I didn't change the IP address in the downloaded kubeconfig (as Alex pointed out a few times in the video) to point to my remote host instead of the 127.0.0.1 localhost and I was trying to connect to a local k3s.

**Comment by alexellis** [comment]
Hmm.. what system did you run k3sup on? The IP is changed automatically via the `--ip` flag during `k3sup install`
