### ISSUE TITLE
K3sup join multi-cloud ?

### ISSUE THREAD

**Issue by truonghdpk** [alexellis/k3sup#372]
The only question: So do I can create a cluster with join machine(node) in multi-cloud into one cluster?

**Comment by kolonuk** [comment]
I suspect this is more a k8s question that a k3sup question...

I think you are asking if kubernetes can have nodes in multiple cloud architectures, and the answer is yes, you can.

How to do that with k3sup is in the readme.

**Comment by alexellis** [comment]
If you'd like help, you'll need to fill out the whole issue template.

We have no idea what you're trying to do or why, or how to help you.

There is no reason why you couldn't use K3sup across multiple cloud vendors, but check that they are in the same region, since latency is important.
