### ISSUE TITLE
Join command fails with SSH error on macOS

### ISSUE THREAD

**Issue by adyanth** [alexellis/k3sup#374]
## Expected Behaviour
I expect the join command to work from macOS

## Current Behaviour
The command fails on macOS but succeeds on Windows.

## Are you a GitHub Sponsor (Yes/No?) 

- [ ] Yes
- [X] No

## Possible Solution
Not sure what the issue is

## Steps to Reproduce
```bash
❯ k3sup join --user root --server-user root --server-host kratos-master.k8s.adyanth.lan --host kratos-worker-2.k8s.adyanth.lan
Running: k3sup join
Server IP: kratos-master.k8s.adyanth.lan
Error: unable to connect to (server) kratos-master.k8s.adyanth.lan:22 over ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

❯ ssh root@kratos-master.k8s.adyanth.lan
Last login: Thu Feb 24 07:59:02 2022 from 10.10.10.11
 08:12:47 up 3 days, 17:39,  0 users,  load average: 0.26, 0.38, 0.44

1 Security notice(s)
Run 'tdnf updateinfo info' to see the details.
root@kratos-master [ ~ ]# exit
logout
Connection to kratos-master.k8s.adyanth.lan closed.
❯ 
```

## Context
From Windows:
```
C:\Users\adyan\Desktop>k3sup join --user root --server-user root --server-host kratos-master.k8s.adyanth.lan --host kratos-worker-2.k8s.adyanth.lan
Running: k3sup join
Server IP: kratos-master.k8s.adyanth.lan
K107ac4e85eb4d6ec6c4fdd2507a066dd741aa24e142a1cd833c14201dd208232c5::server:af9923b6d02a9a2b2254a702c2ba7695
[INFO]  Finding release for channel stable
[INFO]  Using v1.22.6+k3s1 as release
...
```

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`): Macbook Pro 2020 (Intel)

* Operating System and version (e.g. Linux, Windows, MacOS): macOS

```
uname -a
Darwin ADYAH-M-8D1L 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [X] Yes
- [ ] No

**Comment by userneeds-ahe** [comment]
@adyanth HI, did you ever get a proper solution to this? I'm able to ssh from the agent to the server, but not with k3sup.

**Comment by adyanth** [comment]
I used my windows machine to run the command, did not find a solution to this yet.

**Comment by patbos** [comment]
I had to add the following line into the sshd_config on my raspberry pi to get it to work
```
PubkeyAcceptedKeyTypes=+ssh-rsa
```

**Comment by adyanth** [comment]
But I can ssh without issues using the key. Should it matter?

**Comment by patbos** [comment]
> But I can ssh without issues using the key. Should it matter?

Saw this related issue #377 with a description. Opened a PR #378 with a fix that works for me.

**Comment by Saggiehaim** [comment]
I didn't managed to fix this issue also.
I tried everything, and eventually after 6h, I gave up...

Hopefully there will be a solution in the past

**Comment by alexellis** [comment]
This was fixed in https://github.com/alexellis/k3sup/commit/c59d67b63ec76d5d5e399808cf4b11a1e02ddbc8

**Comment by alexellis** [comment]
If you want to get support from me on k3sup, become GitHub Sponsors: https://github.com/sponsors/alexellis
