### ISSUE TITLE
[Feature Request] Allow worker to connect to server with private ip.

### ISSUE THREAD

**Issue by introom** [alexellis/k3sup#386]
## Expected Behaviour
Allow worker to connect to server with private ip.

## Current Behaviour
We have the command:
k3sup join --ip $AGENT_IP --server-ip $SERVER_IP --user $USER

This makes agent connect to the server with $SERVER_IP.

It shall be possible to specify another ip for that purpose instead of reusing the $SERVER_IP.

**Comment by alexellis** [comment]
This can be done through a local SSH tunnel or [inlets tunnel](https://docs.inlets.dev) and is on the roadmap for K3sup Pro.
