### ISSUE TITLE
Feature request: ability to provide sudo password

### ISSUE THREAD

**Issue by AyanamiAkaha** [alexellis/k3sup#387]
## Feature request

Currently if the remote server requires password for sudo k3sup fails with an error 
```
sudo: no tty present and no askpass program specified
Error: error received processing command: Process exited with status 1
```

Would it be possible to have a flag to provide password for sudo, something like `--ask-become-pass` in ansible?

## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [x] No

## My environment

* k3sup version:

```
Version: 0.12.0
Git Commit: c59d67b63ec76d5d5e399808cf4b11a1e02ddbc8
```

* What Kubernetes distribution, client and server version are you using?

local:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```

remote:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

hetzner dedicated server / debian

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux hibiki 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [ ] Yes
- [x] No

(I currently neither have enough skill in go, nor time)

**Comment by airtonix** [comment]
I imagine this makes k3sup a nonstarter on OS not deployed via couldinit

**Comment by alexellis** [comment]
See #298

**Comment by alexellis** [comment]
@airtonix of course you can use k3sup with cloudinit 

Configure passwordless sudo in your script / user configuration 

Or use the --local flag

If you want to keep asking for things, become a sponsor.
