### ISSUE TITLE
k3sup join doesn't work under Windows

### ISSUE THREAD

**Issue by paalkr** [alexellis/k3sup#392]
## Why do you need this?
Joining a server to a k83s cluster doesn't work when executing k3s on Windows.

## Expected Behaviour
The join command to succeed

## Current Behaviour
The ssh remote path / are replaced with \ in the cat command when obtaining the node-token.
```
k3sup join `
>   --server `
>   --k3s-version v1.22.15-rc1+k3s1 `
>   --server-user ubuntu `
>   --server-ip x.x.x.x `
>   --ssh-key ~/.ssh/foo `
>   --k3s-extra-args '--no-deploy traefik --no-deploy metallb --disable-cloud-controller' `
>   --user ubuntu `
>   --ip x.x.x.x --print-command
Running: k3sup join
Server IP: x.x.x.x
Enter passphrase for 'C:\Users\bar\.ssh\foo':
ssh: sudo cat \var\lib\rancher\k3s\server\node-token

cat: varlibrancherk3sservernode-token: No such file or directory
Error: unable to get join-token from server: Process exited with status 1
```

## Your Environment

* k3sup version:
* k3sup version 0.12.3

* What Kubernetes distribution, client and server version are you using?
k3s 1.22.15

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Remote: Ubuntu 20.04.3 LTS

* Operating System and version (e.g. Linux, Windows, MacOS):
 Windows 11 running latest Windows Terminal. Executing k3sup in Powershell

**Comment by alexellis** [comment]
> Are you a GitHub Sponsor?

> Only sponsors may open issues, all other issues (unless previously discussed agreed upon with a maintainer) will be closed without comment.

> Check at https://github.com/sponsors/alexellis
