### ISSUE TITLE
--no-extras implements a deprecated flag and fails install

### ISSUE THREAD

**Issue by brandtkeller** [alexellis/k3sup#396]
## Are you a GitHub Sponsor?

No - Interested in contributions

Only sponsors may open issues, all other issues (unless previously discussed agreed upon with a maintainer) will be closed without comment.

Check at [https://github.com/sponsors/alexellis](https://github.com/sponsors/alexellis)

## Why do you need this?

Inability to currently use k3sup with current stable version of k3s and the `--no-extras` flag. This will fail installation now due to deprecated flag `--no-deploy` throwing a fatal error.

## Expected Behaviour

`k3sup install --ip <ip> --user<user> --ssh-key <priv-key> --no-extras` should install against any target (local or via ssh) with the current stable version of k3s

## Current Behaviour

`k3sup install --ip <ip> --user<user> --ssh-key <priv-key> --no-extras` fails installation %100 of the time due to the deprecated flag.

## Possible Solution

Switch to utilizing `--disable` in place of `--no-deploy` with a conditional check for older versions of k3s for which specific users might still require using.

## Steps to Reproduce

1. `k3s install` without `--k3s-version` used
2. Fails install
3.
4.

## Your Environment

* k3sup version: 0.12.10

```
k3sup version
```
 kubectl version: v1.25.3
* What Kubernetes distribution, client and server version are you using? k3s default stable

```
kubectl version 
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`): ubuntu 22.04

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

```
uname -a

cat /etc/os-release
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

- [x] Yes
- [ ] No

**Comment by alexellis** [comment]
Closed in: Closed in 02c7a775b9914b9dcf3b90fa7935eb347b7979e7
