### ISSUE TITLE
Explicitly state the systemd requirement for the remote Linux host

### ISSUE THREAD

**Issue by mark-benge** [alexellis/k3sup#402]
## Why do you need this?
At the end of this paragraph
This tool uses `ssh` to install `k3s` to a remote Linux host. A requirement is that systemd must be running on the remote Linux host or the install will fail. You can also use it to join existing Linux hosts into a k3s cluster as `agents`. First, `k3s` is installed using the utility script from Rancher, along with a flag for your host's public IP so that TLS works properly. The `kubeconfig` file on the server is then fetched and updated so that you can connect from your laptop using `kubectl`.
Add the following Note:
**Note:** A requirement is that systemd must be running on the remote Linux host or the install will fail.

Avoid unnecessary dev installs unless the environment is up-to-par, Ubuntu on Windows as an example.

Readme clarification

## Expected Behaviour

Notify developers of the systemd requirement for the Linux remote host

## Current Behaviour

k3s Installs will fail if the remote Linux host is not running systemd. 

## Possible Solution

Add the Note as suggested above.

## Steps to Reproduce

1. Not and issue with k3sup ... Readme update request
2.
3.
4.

## Your Environment

* k3sup version: Latest

```
k3sup version
```

* What Kubernetes distribution, client and server version are you using?

```
kubectl version
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

## Do you want to work on this?

Subject to design approval, are you willing to work on a Pull Request for this issue or feature request?

- [X] Yes
- [ ] No

**Comment by alexellis** [comment]
Hi,

Perhaps what we will do instead is link to K3s, if we haven't already. K3sup doesn't require systemd. Kubernetes does and that's a k3s requirement. 

Thanks for your interest 

Alex
