### ISSUE TITLE
First Colon not added to `k3s-extra-args`

### ISSUE THREAD

**Issue by Sharpz7** [alexellis/k3sup#406]
Basically, a colon seems to get removed from my flag when using `k3s-extra-args`
## Why do you need this?

I am trying to add an agent to my k3s cluster. Both the agent and server will be running on contabo.com VPS servers. I have installed wireguard on both.

## Expected Behaviour
Command should work as expected.

```bash
k3sup join --ip $AGENT_IP --ssh-port $AGENT_PORT --server-ip $SERVER_IP --user $USER --ssh-key $SSH_KEY --server-ssh-port $SERVER_PORT --k3s-extra-args '--flannel-backend=wireguard-native'
```

## Current Behaviour
By checking `sudo journalctl -u k3s-agent -f`

```bash
May 01 00:33:59 k3s[484450]: time="2023-05-01T00:33:59+02:00" level=fatal msg="flag provided but not defined: -flannel-backend"
```

## Your Environment

* k3sup version

```
k3sup version: 0.12.12
```

## Do you want to work on this?

Subject to design approval, are you willing to work on a Pull Request for this issue or feature request?

- [x] Yes
- [ ] No

**Comment by alexellis** [comment]
Do you want to explain why you closed the issue? Was it a user error?
