### ISSUE TITLE
About 0.12.13 release

### ISSUE THREAD

**Issue by chenrui333** [alexellis/k3sup#409]
👋 it looks like 0.12.13 still got marked as pre-release, any particular reason about it. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/138596

**Comment by alexellis** [comment]
Hi @chenrui333 every release is marked as pre-release until the binaries are uploaded via GitHub Actions, then they get marked manually as the latest.

Alex

**Comment by alexellis** [comment]
The current release is: 0.13.0
