### ISSUE TITLE
Fetch latest k3s version as default version

### ISSUE THREAD

**Issue by bobanbojkovski** [alexellis/k3sup#41]
## Expected Behaviour
In case k3s version is not defined in k3sup install cmd, fetch latest version without manually updating the config.go content or specifying k3s-version.

## Current Behaviour
Default k3s version is defined in config.go file.
``````
// K3sVersion default version
const K3sVersion = "v0.8.1"
``````

## Possible Solution
config.go
``````
package config

import (
	"log"
	"net/http"
	"path"
)

// GetK3sVersionLatest gets lastest k3s version from https://github.com/rancher/k3s/releases/latest url
func GetK3sVersionLatest() string {

	k3sVersionURL := "https://github.com/rancher/k3s/releases/latest"

	resp, err := http.Get(k3sVersionURL)
	if err != nil {
		log.Fatal(err.Error())
	}

	K3sVersion := path.Base(resp.Request.URL.String())
	defer resp.Body.Close()

	return K3sVersion
}
``````

update install.go
``````
44:   command.Flags().String("k3s-version", config.GetK3sVersionLatest(), "Optional version to install, pinned at a default")

63:   fmt.Println("k3s version: " + k3sVersion)
``````

update join.go
``````
33:   command.Flags().String("k3s-version", config.GetK3sVersionLatest(), "Optional version to install, pinned at a default")

51:   fmt.Println("k3s version: " + k3sVersion)
``````

## Context
Using lastest k3s version as default, in case the k3s-version is not defined.

**Comment by alexellis** [comment]
Hi thank you for your suggestion.

Version pinning was introduced deliberately, I would imagine passing an empty string to the flag may do what you're requesting.

In the meantime, the version of k3s we had to hold back has been fixed upstream, so feel free to send a PR to upgrade the version to whatever is stable. Alex

**Comment by alexellis** [comment]
See also: https://github.com/alexellis/k3sup/commit/7d954414def98c52ae1f6de08ac5317e4260e673
