### ISSUE TITLE
How to access Traefik dashboard?

### ISSUE THREAD

**Issue by jhermsen** [alexellis/k3sup#413]
Not sure if this part of the installation process k3sup, but I have the following issue.
I'm a bit of a beginner in regards to kubernetes.

I used windows k3sup.exe to do a basic install "k3sup install --ip **** --user root".

The install process seems to have gone well.
I have a Traefik loadbalancer service so Traefik is present and up (I get a 404 when trying to use ports 80/443)
I also notice an IngressRoute for traefik-dashboard, but can't seem to find the right url or method to access it.

Can someone please guide me in the right direction? I guess it's something simple that I overlooked.

**Comment by alexellis** [comment]
Hi @jhermsen 

This isn't about K3sup, so I'm going to get it closed.

You will get a 404 when accessing Traefik on port 80/443, that's how ingress works.

If you wish to visit a website that you're hosting, then you need to learn about ingress and set up appropriate records.

Learn about Ingress here: https://kubernetes.io/docs/concepts/services-networking/ingress/

Alex
