### ISSUE TITLE
I need to pass password instead of key in "--ssh-key

### ISSUE THREAD

**Issue by aniruddha0583** [alexellis/k3sup#415]
k3sup install --host 1.2.3.4 --user ubuntu --ssh-key ${KEY} --merge --context admin --skip-install
Like in above command --ssh-key uses the key but I want to pass the password over there. How can I achive this.

**Comment by aniruddha0583** [comment]
k3sup install  --host 1.2.3.4 --user ubuntu --ssh-key ${KEY} --merge --context admin --skip-install
Like in above command --ssh-key uses the key but I want to pass the password over there. How can I achive this.

**Comment by alexellis** [comment]
Hi @aniruddha0583 we can't answer questions where people haven't filled out the whole issue template.

I'm not sure why you deleted it but it's unhelpful. I'm not really understanding what you are trying to do here, but it sounds like you might be using k3sup wrong. Read the documentation and see how we recommend using it.

https://raw.githubusercontent.com/alexellis/k3sup/master/.github/ISSUE_TEMPLATE.md

Alex
