### ISSUE TITLE
docs change

### ISSUE THREAD

**Issue by Roguito** [alexellis/k3sup#419]
If I was more of a developer I'd make a PR.

Current readme.md:
"k3sup plan \
  devices.json \
  --user ubuntu \
  --servers 3 \
  --server-k3s-extra-args "--disable traefik"
  --background > bootstrap.sh
  
  for copy and paste clicky keyboard warriors like myself that should be:
  --server-k3s-extra-args "--disable traefik" \

**Comment by Roguito** [comment]
I am and loving it. Just home lab stuff while I'm also learning cilium. I might even integrate your plan feature into some gitops style scripting I'm doing.

**Comment by alexellis** [comment]
Glad to hear it, [you know how to support my work if you are loving K3sup and having fun](https://github.com/sponsors/alexellis).
