### ISSUE TITLE
Add ssh-key to plan command

### ISSUE THREAD

**Issue by orcutt989** [alexellis/k3sup#428]
It doesnt seem to work unless I am doing it wrong. I see that ssh-key has been added to join, but it would be nice if this was added to plan so all of the commands in bootstrap.sh got the key path too.

**Comment by orcutt989** [comment]
Nevermind its already there!

**Comment by mattfysh** [comment]
@orcutt989 where did you find it?

**Comment by orcutt989** [comment]
> [@orcutt989](https://github.com/orcutt989) where did you find it?

Does `--ssh-key` work on plan? I can’t really remember its been a long time.

**Comment by rgee0** [comment]
https://github.com/alexellis/k3sup/issues/448

**Comment by alexellis** [comment]
Thanks for the link to the PR @rgee0

**Comment by alexellis** [comment]
@orcutt989 

Check your version?

/lock: complete. Please open your own issue if you need support. I'll be prioritising any requests from GitHub sponsors first.
