### ISSUE TITLE
k3sup install - Error: error received processing command: Process exited with status 1 - how to fix this ?

### ISSUE THREAD

**Issue by n00bsi** [alexellis/k3sup#430]
## Why do you need this?

Try to get my first k8s-cluster

I wann learn how to build k8s-HA-Cluster

## Expected Behaviour

Dont wanna get the  Error: error received processing command: Process exited with status 1

Should tell me why the Command fail not only a error Code

## Current Behaviour

got Error: error received processing command: Process exited with status 1

## Steps to Reproduce

1. Using Almalinux 9
2. Download the k3sup an make is runable and move to /usr/local/bin
3.  k3sup install --ip 192.168.122.202 --tls-san 192.168.1.210  --cluster --local-path ~/.kube/k8s-cluster.dev.dman.cloud.yaml  --context k8s-cluster-ha  --k3s-extra-args "--disable traefik --no-deploy servicelb --node-ip=192.168.122.202"  --print-command

Running: k3sup install
2024/03/08 14:47:47 192.168.122.202
Public IP: 192.168.122.202
ssh: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --cluster-init --tls-san 192.168.1.210 --disable traefik --no-deploy servicelb --node-ip=192.168.122.202' INSTALL_K3S_CHANNEL='stable' sh -

Result:  
ssh: sudo cat /etc/rancher/k3s/k3s.yaml

Error: error received processing command: Process exited with status 1

   run this as user root so no sudo needed

## Your Environment

behind a http-proxy

192.168.122.210  Virtual IP ( haproxy & keepalived )

on all Node FW rules:

# firewall-cmd list-all
usage: 'firewall-cmd --help' for usage information or see firewall-cmd(1) man page
firewall-cmd: error: unrecognized arguments: list-all
[root@k8sn10 ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp1s0
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 6443/tcp 2379-2380/tcp 10250/tcp 10251/tcp 10259/tcp 10257/tcp 179/tcp 4789/udp 30000-32767/tcp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

SELinux on all Nodes:

# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

* k3sup version: 

```
k3sup version
```
0.13.5

* What Kubernetes distribution, client and server version are you using?

```
kubectl version
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

Docker version 25.0.3, build 4debf41

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):

libvirt/qemu

* Operating System and version (e.g. Linux, Windows, MacOS):

Linux

```
uname -a
Linux k8sn10 5.14.0-362.18.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan 29 07:05:48 EST 2024 x86_64 x86_64 x86_64 GNU/Linux


cat /etc/os-release

NAME="AlmaLinux"
VERSION="9.3 (Shamrock Pampas Cat)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.3 (Shamrock Pampas Cat)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

```

## Do you want to work on this?

Subject to design approval, are you willing to work on a Pull Request for this issue or feature request?

- [ ] Yes
- [ X] No

**Comment by alexellis** [comment]
Hi,

It looks like you may be struggling with K3sup, however there are no known issues with k3sup at the moment, and we cannot debug the systems of individuals over the Internet.

Please refer to the documentation, and try a different VM or cloud provider, i.e. one of the ones that we recommend with Ubuntu 22.04. You'll be certain to have success that way.

Maybe you have too much custom stuff in your cluster?

And it's worth noting that k3sup only installs k3s and makes configuration easier, so if you're having "issues" with k3sup, you're most likely having issues with k3s itself, or haven't read a part of the README.

Alex
