### ISSUE TITLE
Q: MicroOS (openSUSE) as operating system

### ISSUE THREAD

**Issue by leonkosak** [alexellis/k3sup#434]
https://microos.opensuse.org/

Because MicroOS is immutable, it is perfect (in my opinion) for being a preferred choice for operating system (instead of Debian or Ubuntu).
Wouldn't be recommended that installation of MicroOS is mentioned (at least for production-ready HA cluster environments)?

**Comment by alexellis** [comment]
Hi Leon

Sorry I have no interest in MicroOS or SUSE. If they or you want to sponsor me to promote the project, that's another story.

If you have strong feelings about MicroOS, but no affiliation, then I'd suggest you publish some technical content on your blog.
