### ISSUE TITLE
join a local server/agent to a remote server

### ISSUE THREAD

**Issue by webcoderz** [alexellis/k3sup#439]
i am failing to understand if this is possible , i have a local gpu node i want to connect to a remote DO server , is this possible? if so, do you have a reference to an example of how its done?

**Comment by alexellis** [comment]
Hi @webcoderz this is really a question for the k3s project, not for k3sup.

You will find details about k3s networking here: https://docs.k3s.io/networking/basic-network-options

If you want to invoke a HTTP or TCP webservice hosted on the local server, the easiest way to do this would be using an inlets tunnel: https://inlets.dev/blog/2024/06/06/tunnel-k8s-via-aws-ec2.html

If you don't want to expose the service to the Internet from the local K3s cluster, then you can also do a "private tunnel" where only the control plane is public, and the data plane is accessed within the remote cluster via ClusterIP.. we have details on that if you're interested ask on the [inlets](https://inlets.dev) Discord once you sign up.

Alex

**Comment by alexellis** [comment]
I took a couple of hours to write-up how to do what you want with inlets: https://inlets.dev/blog/2024/08/09/local-ollama-tunnel-k3s.html

If you want more versatility, deploying OpenFaaS locally would make sense, then you can orchestrate and invoke the code using the GPU remotely via HTTP/REST.
