### ISSUE TITLE
是否支持离线安装？

### ISSUE THREAD

**Issue by notionev** [alexellis/k3sup#443]
hello k3s在线安装非常好，但是是否能否支持本地离线安装呢？不需要通过互联网那种

**Comment by scottstensland** [comment]
above google translate says ...  Hello k3s online installation is very good, but can it support local offline installation?

**Comment by alexellis** [comment]
Hi I also ran this through Google Translate. 

K3sup Community Edition doesn't support air gap installs but k3s does: https://docs.k3s.io/installation/airgap

There are so many free users who ask for things but don't sponsor my time. 

If that were to change, I'd consider adding these kinds of enterprise commercial features to k3sup.
