### ISSUE TITLE
Following the installation scripts fails

### ISSUE THREAD

**Issue by jonatasbaldin** [alexellis/k3sup#46]
## Expected Behaviour
Copy and paste the commands from the Installation instructions in `README.md` would work.

## Current Behaviour
The first line from the installation instructions gives me the `k3sup-$arch` binary and correct instructions:
```bash
$ curl -sLS https://get.k3sup.dev | sh
=========================================================
==    As the script was run as a non-root user the     ==
==    following commands may need to be run manually   ==
=========================================================

  sudo cp k3sup-darwin /usr/local/bin/k3sup
```

But the second command in the instructions fails, because the binary name is different:
```bash
$ sudo install k3sup /usr/local/bin/
install: k3sup: No such file or directory
```

## Possible Solution
1. Remove second line of installation, letting the user follow the instructions from the `get.sh` output
2. After downloading the binary, rename it from `k3sup-$arch` to `k3sup` and adjust the instructions in the `get.sh` output to `sudo cp k3sup /usr/local/bin/k3sup`

## Steps to Reproduce (for bugs)
1. Execute exactly the installation instructions

## Context
A quick change to yield a better experience when installing the binary. The first impression sticks 😅

## Your Environment
- MacOS.

**Comment by alexellis** [comment]
You should type in this though? `sudo cp k3sup-darwin /usr/local/bin/k3sup`

**Comment by alexellis** [comment]
Worked for me

```
space-mini:tmp alex$ curl -sLS https://get.k3sup.dev | sh

You already have the k3sup cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

Downloading package https://github.com/alexellis/k3sup/releases/download/0.4.2/k3sup-darwin as /tmp/k3sup-darwin
Download complete.

=========================================================
==    As the script was run as a non-root user the     ==
==    following commands may need to be run manually   ==
=========================================================

  sudo cp k3sup-darwin /usr/local/bin/k3sup

space-mini:tmp alex$   sudo cp k3sup-darwin /usr/local/bin/k3sup
Password:
space-mini:tmp alex$ 
```

**Comment by jonatasbaldin** [comment]
Yeah, if I follow the instructions it work, but if I just copy and paste the instructions from the README.md, it doesn't:

```bash 
# Instructions from README.md
curl -sLS https://get.k3sup.dev | sh
sudo install k3sup /usr/local/bin/

k3sup --help

# output

You already have the k3sup cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

Downloading package https://github.com/alexellis/k3sup/releases/download/0.4.2/k3sup-darwin as /Users/jonatasbaldin/scratch/test-k3s/k3sup-darwin
Download complete.

=========================================================
==    As the script was run as a non-root user the     ==
==    following commands may need to be run manually   ==
=========================================================

  sudo cp k3sup-darwin /usr/local/bin/k3sup

Password:
install: k3sup: No such file or directory
```

**Comment by alexellis** [comment]
This is the normal way to download with the suffix still in-tact, but if you want, we could change it. I'd accept a PR

**Comment by alexellis** [comment]
The point was to show one example of how to install, the example in the README is for Linux where there is no suffix, you're using Darwin, so you need to follow the output instead :-)

**Comment by jonatasbaldin** [comment]
I can make a PR, I have three ideas (in the order that I most like them):

1. Remove second line from README.md and add `sudo` before the first line, will always work
2. Remove second line from README.md, let the user read the instructions
3. Change the `get.sh` script to download the file as `k3sup` instead of `k3sup-$suffix`

What do u think?

**Comment by alexellis** [comment]
I think 3. sounds fine, if you'd like to implement it.

**Comment by jonatasbaldin** [comment]
Went with `3` :D
