### ISSUE TITLE
Add cert-manager app

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#48]
## Expected Behaviour

Add cert-manager app

```
k3sup install cert-manager
```

## Current Behaviour

Unavailable via k3sup

## Possible Solution

Copy approach from https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/scripts/install-cert-manager.sh

And codify in Golang as per `openfaas_app.go`

**Comment by utsavanand2** [comment]
I'll take this up

**Comment by alexellis** [comment]
Thanks

**Comment by alexellis** [comment]
Happy for someone to send a PR earlier if @utsavanand2 is busy

**Comment by utsavanand2** [comment]
**Need Help** with PR is [#52](https://github.com/alexellis/k3sup/pull/52)

**Comment by alexellis** [comment]
Released 🎉
