### ISSUE TITLE
[Feature request] Add app for Docker registry

### ISSUE THREAD

**Issue by jonatasbaldin** [alexellis/k3sup#49]
## Expected Behaviour
Add the docker registry by:
```
k3sup app install registry
```

In the end show information on how to port-forward your localhost to the registry port.

## Current Behaviour
Unavailable.

## Context
When developing locally for OpenFaaS, having a local registry in K8S is faster than pushing images to Docker Hub.

**Comment by alexellis** [comment]
How are you thinking about configuring TLS or not configuring it? by default docker won't push to an insecure-registry and neither will Kubernetes.

**Comment by jonatasbaldin** [comment]
Maybe using something like this? https://github.com/SeldonIO/k8s-local-docker-registry/

Used this scripts today to get running and it worked like a charrrrm

**Comment by blaise-sumo** [comment]
Wonderful!

**Comment by alexellis** [comment]
That doesn't explain how you intend to bypass the TLS issues.

Can you elaborate? Note we cannot assume access to the Docker daemon or Kubelet configuration

**Comment by jonatasbaldin** [comment]
🤔

Since I'm testing with Docker for Desktop, it worked because it probably uses my local docker daemon. Tried with GCP, couldn't make it work :(

But this would be something nice to have, working with OpenFaaS and being able to use local images would speedup a lot!

**Comment by alexellis** [comment]
I'm not aware of a good way to run a local registry "automatically" without cranking open your Docker daemon and adding nasty --insecure-registry settings or new CA bundles to your trust chain. Happy for someone to revisit this with a nice, lean and magic solution.
