### ISSUE TITLE
K3sup hung during installation on Raspberry Pi A+

### ISSUE THREAD

**Issue by verrol** [alexellis/k3sup#54]
During installation of k3s on my Raspberry Pi A+ board, k3sup seems to be hung after staring k3s.  At first it seemed to be working, as it got to the starting k3s message soon after issuing the command, but then it was hung there for about an hour before I killed it.

## Expected Behaviour
I ran the following command on my Mac:

```sh
k3sup install --ip 10.10.100.183 --merge --user pi
```

## Current Behaviour

Public IP: 10.10.100.183
ssh -i /Users/verrol/.ssh/id_rsa pi@10.10.100.183
ssh: curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server --tls-san 10.10.100.183 ' INSTALL_K3S_VERSION='v0.9.1' sh -

[INFO]  Using v0.9.1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.9.1/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.9.1/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s

## Steps to Reproduce (for bugs)

1. Install k3sup:
curl -sLS https://get.k3sup.dev | sh

2. Run k3sup to install k3s on RPi
k3sup install --ip 10.10.100.183 --merge --user pi

3.
4.

## Context

Trying to see if I can get k3s to run on Raspian to experiment with k8s on the edge.

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
Host: 
% uname -a
Darwin vee.mv.lorrev.org 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

Remote/RPi: 
% uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

* Operating System and version (e.g. Linux, Windows, MacOS):

**Comment by alexellis** [comment]
AFAIK only RPi2, 3 and 4 are supported by k3s, certainly I don't test with anything else. 

You could try the Rancher support forums perhaps?
