### ISSUE TITLE
App: Add Nginx Ingress app with two modes

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#55]
Add Nginx app with two modes

## Expected Behaviour

Adding Nginx Ingress in host mode or LB mode (default) would be great.

## Possible Solution

See: https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/scripts/install-nginx.sh

**Comment by alexellis** [comment]
For running without an LB: https://github.com/openfaas-incubator/ofc-bootstrap/blob/2b2ba7030860b6bf481f4ad5980dd08a6f27879c/main.go#L374

**Comment by Waterdrips** [comment]
Derek assign: me

**Comment by Waterdrips** [comment]
done on #85
