### ISSUE TITLE
Docs: SAN definition and purpose

### ISSUE THREAD

**Issue by geekdave** [alexellis/k3sup#6]
I'll volunteer to make this doc update, just wanted to get some clarification first to make sure I understand.

The README says that this tool:

> updates the SAN address to the public IP

Looks like this refers to the flag:

```
			cli.StringSliceFlag{
				Name:  "tls-san",
				Usage: "Add additional hostname or IP as a Subject Alternative Name in the TLS cert",
				Value: &ServerConfig.TLSSan,
			},
```

...in k3s: https://github.com/rancher/k3s/blob/99716deb08784e62ecd29f4f457fb20c73310748/pkg/cli/cmds/server.go#L122-L125

I had to google "SAN certificate" but I learned that SANs provide the ability to have multiple domain names (or IP addresses) listed on the same certificate.  So if I understand correctly, without this feature, k3s may generate a certificate that includes the k3s server's hostname but not the IP address, and that would be problematic for k3s agents or the kubectl CLI that wants to connect via the IP address?

If that is correct I can take a crack at adding an explainer for this.

**Comment by alexellis** [comment]
Where would you add it? We don't expose any flag called SAN? It's just called IP.

**Comment by geekdave** [comment]
Right - not adding a new flag, just augmenting the part of the README that says `updates the SAN address to the public IP` with some info about what a SAN is, and why this is needed (i.e. what problem is this solving, what is the problem if you don't add this), or what manual step in setting up k3s this --IP flag serves to automate.

**Comment by alexellis** [comment]
I've changed the console output to remove the text "SAN", I hope this helps.
