### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sandys** [alexellis/k3sup#64]
support in ingress for multiple domains+custom ssl certs and domain -> pod rules

Hi,
I'm bringing over this issue from the k3s repo - https://github.com/rancher/k3s/issues/868
k3sup has become our primary way to create k3s clusters and im hoping this is the right place to fix it. 
FYI, there are multiple people with similar issues - https://github.com/rancher/k3s/issues/795

Basically it boils down to a simple thing : how do we configure a domain on the ingress, add ssl certificates to it (non letsencrypt) and setup domain/url -> pod mapping. 

It might be going a little different than openfaas ... but a lot of us just want to run a nextjs + redis stack on k3s !

**Comment by alexellis** [comment]
Hi @sandys thanks for your interest in k3sup.

Please can you clearly list the requirements you have in bullets?

**Comment by sandys** [comment]
@alexellis thanks for replying.
The itemized request is straightforward, but it is super-hard to configure and setup for most people. Check this out as well -https://github.com/rancher/k3s/issues/117 and https://github.com/rancher/k3s/issues/436 

Give k3sup commandline options for
- Adding ssl certificates to the ingress ( there are some "voodoo" aspects here - https://github.com/rancher/k3s/issues/27) . Use kubernetes Secrets to hold certs.
- Adding a traefik toml file (SSL) with my configuration. Provide a well defined way to refer to the Secrets created above. Most common thing that people want to do is:
      - map domain/path to certificates  (e.g. "abc.com" : k3s-secret-abc-crt + k3s-secret-abc-key)
      - map doman/path to k3s Service 
- nice to have: k3sup creates a template yaml for a service that the user wants to create (according to what you are setting up on traefik). this is still massively confusing for users https://github.com/rancher/k3s/issues/436#issuecomment-540708852

**Comment by alexellis** [comment]
Thank you for your feedback. I'm going to close the issue now as I wasn't able to find anything that would be both easily actionable and a good fit for k3sup. Feel free to suggest improvements upstream on k3s for features you need in the base platform.
