### ISSUE TITLE
Remove sudo when installing as root

### ISSUE THREAD

**Issue by martindekov** [alexellis/k3sup#66]
If I run the k3sup with photons OS trimmed version https://github.com/vmware/photon/wiki/Downloading-Photon-OS. In the OVA with 120 mb `sudo` does not exist as command so the installation fails.

## Expected Behaviour

When the user with which you ssh is root, skip sudo.

## Current Behaviour

`sudo` is ran no matter the user name(even when `root`).

## Possible Solution

I think that you might rename your superuser to be !=`root`, but we can skip sudo if the username in the `--user` flag is root. Other solution is add additional flag` --root-user=myfunky_root_name` which will skip appending `sudo`.

## Steps to Reproduce (for bugs)

1.Deploy VM with the following OVA - http://dl.bintray.com/vmware/photon/3.0/Beta/ova/photon-hw11-3.0-5e45dc9.ova (default cred:root pass: changeme)
2. Run k3sup against it
3. See `bash: sudo: command not found`

## Context

Some operating systems might not contain sudo. I can work on the implementation in case this is approved.

## Side note

Noticed that this:
```
    server: https://127.0.0.1:6443
```
is copied to my kubeconfig. I believe we can swap the `127.0.0.1` reference with the value of `--ip`.

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
Check out steps to reproduce(PhotonOS)
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by alexellis** [comment]
You will need to say which command fails. What exactly are you running to get an error?

**Comment by martindekov** [comment]
https://github.com/alexellis/k3sup/blob/fe942b8d66155732c611c6e745fea938d0f1c8b7/pkg/cmd/install.go#L106

I fixed it for myself(removed `sudo`), but in case someone stumbles upon it I think it can be fixed in some way.

**Comment by alexellis** [comment]
OK that helps a lot, because it sounded like you were struggling with the bash script, to which I would have said, customise what you type in.

How are we going to succinctly execute commands on a remote VM which doesn't have `sudo`? Let me know what ideas you have.

**Comment by martindekov** [comment]
If we are logged in as the super user account I think we would be executing commands as if we were using sudo. 

If that is the case, then we can add flag to commands which use sudo binary like --root, pointing that the account is the superuser account.

**Comment by alexellis** [comment]
Do you use `--user root`?

**Comment by alexellis** [comment]
Do you use `--user root`?

**Comment by alexellis** [comment]
What if we added `--sudo=false` for your scenario?

**Comment by Hades32** [comment]
In my scenario the Ubuntu doesn't have `sudo` installed, so wither apt-get'ing it or as you suggest `--sudo=false` would solve that case.

**Comment by alexellis** [comment]
Happy to accept a PR for this.

**Comment by alexellis** [comment]
https://github.com/alexellis/k3sup/releases/tag/0.5.2

**Comment by alexellis** [comment]
@martindekov ☝️ 

Thanks @Hades32

**Comment by martindekov** [comment]
Thank you @Hades32 👍
