### ISSUE TITLE
[Feature Request] Knative app

### ISSUE THREAD

**Issue by beriberikix** [alexellis/k3sup#69]
I've been experimenting with [Knative](https://knative.dev/) recently and setup is a pain. It would be very convenient to have an `app` to install Istio + Knative. Details on a custom install can be found [here](https://knative.dev/docs/install/knative-custom-install/).

## Expected Behaviour
`k3sup app install knative`

**Comment by alexellis** [comment]
Closing out some older issues. Thanks for the suggestion.
