### ISSUE TITLE
Not all arguments are passed to the metrics-server

### ISSUE THREAD

**Issue by jeka** [alexellis/k3sup#71]
The snippet:
```
overrides := map[string]string{}
overrides["args"] = `{--kubelet-insecure-tls,--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname}`
```
Renders to:
```
--kubelet-insecure-tls
--kubelet-preferred-address-types=InternalIP
--ExternalIP
--Hostname
```
Which is not what do you intend I guess.

Also little off-topic but what's the point of having --namespace parameter if you don't allow anything but 'default'?

K3sup Version: 0.5.2
Git Commit: 9193ccf155653f9e3809c559f6b9d099813b8f45

**Comment by alexellis** [comment]
> Also little off-topic but what's the point of having --namespace parameter if you don't allow anything but 'default'?

See the following upstream issue: https://github.com/helm/charts/issues/17909 🤷‍♂

The chart is working anyway from what I can see.

Interesting that the ExternalIP/Hostname parameters are not being picked up. If you have a suggestion or want to send a PR, your contribution would be welcomed.

**Comment by jeka** [comment]
It's no wonder that parameters are not picked up correctly. That's how helm's --set works.

The proper way (according to https://helm.sh/docs/using_helm/#the-format-and-limitations-of-set) of passing these parameters should be:
```
overrides["args"] = `{--kubelet-insecure-tls,--kubelet-preferred-address-types=InternalIP\,ExternalIP\,Hostname}`
```
(escaping commas in **value** with backslash)

**Comment by alexellis** [comment]
PRs are welcome. Would you like to take it?

**Comment by jeka** [comment]
I have almost zero experience with Go. I am even unable to build a freshly cloned repo. I am getting some errors which mean nothing to me. For example:
```
jeka/k3sup/main.go:28:20: cannot use cmdInstall (type *"github.com/alexellis/k3sup/vendor/github.com/spf13/cobra".Command) as type *"github.com/jeka/k3sup/vendor/github.com/spf13/cobra".Command in argument to rootCmd.AddCommand
jeka/k3sup/main.go:29:20: cannot use cmdVersion (type *"github.com/alexellis/k3sup/vendor/github.com/spf13/cobra".Command) as type *"github.com/jeka/k3sup/vendor/github.com/spf13/cobra".Command in argument to rootCmd.AddCommand
jeka/k3sup/main.go:30:20: cannot use cmdJoin (type *"github.com/alexellis/k3sup/vendor/github.com/spf13/cobra".Command) as type *"github.com/jeka/k3sup/vendor/github.com/spf13/cobra".Command in argument to rootCmd.AddCommand
jeka/k3sup/main.go:31:20: cannot use cmdApps (type *"github.com/alexellis/k3sup/vendor/github.com/spf13/cobra".Command) as type *"github.com/jeka/k3sup/vendor/github.com/spf13/cobra".Command in argument to rootCmd.AddCommand
```
So if you want untested PR I can do it as it is just one line change. But usually, I like to test changes before submitting patches/PRs

**Comment by alexellis** [comment]
The errors are because you are not familiar with how to develop with Go.

You should clone into the GOPATH of the upstream project you've forked, so

```sh
export GOPATH=$HOME/go/
mkdir -p $HOME/go/src/github.com/alexellis/
cd  $HOME/go/src/github.com/alexellis/
git clone https://github.com/alexellis/k3sup
cd k3sup

make
```

**Comment by jeka** [comment]
OK, I opened #73. I hope I managed to do it right.

By the way, the way this app is installed is really broken. It does not get installed in "default" namespace. It's installed in the namespace set by the current context. And of course, it doesn't work if the current namespace is not the "default" namespace.

**Comment by alexellis** [comment]
Feel free to send a PR, if you don't agree with the way it works. I mentioned above that the upstream chart has issues and cannot be configured to install to a particular namespace.

**Comment by jeka** [comment]
Yes, I read the issue with the upstream chart but still in the current form of installation this app is almost unusable.
On the other hand, I am wondering why do you take this route of installing apps (helm charts)? It's complex, not flexible, does not scale well and does not make it easy to contribute apps.
Why don't you use k3s inbuild support of helm charts? This way all you need is one YAML file per app.
Another possibility is to use tiller-less helm2 (or even helm3) to install charts if you don't want tiller. Yes, helm3 is still in beta but k3sup (k3s for that matter) is not a production-ready piece of software anyway.
I should fill RFE I guess, but I don't have enough time in my hands for such activity atm.

**Comment by alexellis** [comment]
I believe this is fixed now. Thanks for your interest, `k3sup app install` must work on all Kubernetes clusters. The OpenFaaS app works with `--helm3` and it will be introduced to other commands as soon as kind folks like yourself volunteer time to send a PR :-)

Thanks again for your interest and for flagging this original issue.
