### ISSUE TITLE
[App request] Add Linkerd

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#72]
## Expected Behaviour

```
k3sup app install linkerd
```

## Possible Solution

Use the OpenFaaS app as an example and install via:

https://linkerd.io/2/tasks/install-helm/

https://github.com/alexellis/k3sup/blob/master/pkg/cmd/openfaas_app.go
https://github.com/alexellis/k3sup/blob/master/pkg/cmd/apps.go

**Comment by phumberdroz** [comment]
I will work on this one. :)

**Comment by grampelberg** [comment]
@cpretzer mind helping @phumberdroz with some pointers?

**Comment by cpretzer** [comment]
Yep! I chatted with @alexellis about this over the weekend. @phumberdroz we'll keep track of the progress in this issue.

Have you joined the community on https://slack.linkerd.io? We can collaborate there, as well

**Comment by alexellis** [comment]
@phumberdroz what kind of timeline do you have in mind?

**Comment by phumberdroz** [comment]
I hope that I will have it running by the end of the week. I took a brief look at it yesterday evening.

**Comment by alexellis** [comment]
I was expecting this to be 5-10 mins copy/paste and a PR. Is this still something you want to pick up @phumberdroz or should we find someone else to take it on?

**Comment by phumberdroz** [comment]
As I wrote above that I had planned to do it til the end of the week .. I have visitors from out of town til tomorrow morning and will then work on it.

**Comment by alexellis** [comment]
@phumberdroz given that we took a little over a month to get to something working, I went ahead and did a quick PR myself. It would be great if you want to revisit as your schedule permits for improvements.
