### ISSUE TITLE
Question on how to handle kubectl non-zero exit codes

### ISSUE THREAD

**Issue by Patazerty** [alexellis/k3sup#75]
`kubectlTask()` does not check exit code, causing in some scenarios failed kubectl commands to be treated as successful but silently failing. 

## Expected Behaviour
If a kubectl commands fails, kubectlTask should return an error. If the error from kubectlTask is checked, this should stop k3sup in its task.

## Current Behaviour
If a kubectl command fails with an non-zero exit code, k3sup will continue its task.

## Possible Solution
Add a simple exit code check just like the one in `kubectl()`

## Steps to Reproduce (for bugs)
Install tiller once and install it again, kubectl commands will fail but k3sup will not stop.

## Context
This is not critical but complicates the development of new features, I was once troubleshooting something and commands were silently failing, took me some time to realize what was the issue.

## Your Environment
Linux

**Comment by alexellis** [comment]
/set title: Question on how to handle kubectl non-zero exit codes

**Comment by alexellis** [comment]
Which specific app are you having problems with?

**Comment by Patazerty** [comment]
I encountered this issue while testing the tiller install, but this happens with any kubectl command that creates something: if installing apps such as openfaas twice by mistake, the `create secret` command will fail silently for example.

**Comment by Patazerty** [comment]
Beyond my own use cases, I think have a `kubectktask()` and a `kubectltaskcanfail()` or setting some sort of explicit "ignore command failure" flag would be useful. In some scenarios commands can fail without impact (e.g. re-installing an app), but if anything else goes wrong (network error, bad KUBECONFIG file, etc.) k3sup will basically tell the user 'everything is fine' or some unrelated errors will pop later on without an explicit 'the kubectl command failed and the stderr was: ' error message. That could also be useful for future apps that could require kubectl commands to not fail.

**Comment by alexellis** [comment]
This is a fair suggestion, feel free to propose a PR on one of the apps, ideally all commands should be runnable more than once, perhaps by using apply instead of create?

**Comment by alexellis** [comment]
(Closing as inactive)
