### ISSUE TITLE
k3sup doesn't work ootb in Fedora 31

### ISSUE THREAD

**Issue by e-minguez** [alexellis/k3sup#76]
## Expected Behaviour
Download k3sup and run it against a Fedora 31 box

## Current Behaviour
It requires to install `policycoreutils-python-utils` package (which is not installed by default in the cloud image) to manage selinux stuff. I've installed the package and tried again. This time:

```
Oct 30 11:18:08 f31-01 systemd[1]: Stopped Lightweight Kubernetes.
Oct 30 11:18:08 f31-01 systemd[1]: Starting Lightweight Kubernetes...
Oct 30 11:18:08 f31-01 systemd[9298]: k3s.service: Failed to execute command: Permission denied
Oct 30 11:18:08 f31-01 systemd[9298]: k3s.service: Failed at step EXEC spawning /usr/local/bin/k3s: Permission denied
Oct 30 11:18:08 f31-01 systemd[1]: k3s.service: Main process exited, code=exited, status=203/EXEC
Oct 30 11:18:08 f31-01 systemd[1]: k3s.service: Failed with result 'exit-code'.
Oct 30 11:18:08 f31-01 systemd[1]: Failed to start Lightweight Kubernetes.
Oct 30 11:18:13 f31-01 systemd[1]: k3s.service: Service RestartSec=5s expired, scheduling restart.
Oct 30 11:18:13 f31-01 systemd[1]: k3s.service: Scheduled restart job, restart coun
```

Running the k3s binary manually:

```
...
INFO[2019-10-30T11:19:21.695847768Z] Run: k3s kubectl                             
INFO[2019-10-30T11:19:21.695940194Z] k3s is up and running                        
WARN[2019-10-30T11:19:21.696013040Z] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
ERRO[2019-10-30T11:19:21.696061981Z] Failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
FATA[2019-10-30T11:19:21.696118045Z] failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi
```

## Possible Solution
I think this is probably because Fedora 31 has switched to cgroupsv2 https://fedoraproject.org/wiki/Changes/CGroupsV2 but I'm not 100% sure.

## Steps to Reproduce (for bugs)
1. Create a Fedora 31 x86_64 VM
2. Download k3sup using the script
3. Run k3sup as `k3sup install --ip 192.168.122.235 --user fedora` and observe the `semanage` issue
4. Fix the semanage requirement by ssh-ing in the VM and installing `policycoreutils-python-utils` as `sudo dnf install -y policycoreutils-python-utils`
5. Run k3sup again
6. ssh-ing again and see `journalctl -u k3s`
7. Run k3s as root to observe the cgroup stuff

## Context
I just wanted to see if I could run k3sup against a Fedora 31 VM

## Your Environment

* What OS or type or VM are you using? Where is it hosted?
Fedora 30 in my laptop, Fedora 31 VM for k3s to be installed
* Operating System and version (e.g. Linux, Windows, MacOS):

**Comment by alexellis** [comment]
Thanks for your interest in the project. I think your report would be best placed upstream on the k3s project. K3sup only wraps the script provided by Rancher.

https://github.com/rancher/k3s/issues

Let me know how you get on and I will close this issue for now
