### ISSUE TITLE
[feature]sudo on user support?

### ISSUE THREAD

**Issue by sokoow** [alexellis/k3sup#79]
Hey Alex,

Great work as usually, really impressive project :) What about adding sudoed user to bootstrap options ? Currently only root can install k3sup..

**Comment by alexellis** [comment]
Thank you that's really kind. 

Please could you go back and fill out the whole issue template along with any errors you are seeing and how we can reproduce this?

**Comment by alexellis** [comment]
Closing due to lack of information. @sokoow you can run the install bash script as a normal user, I'm not sure what you meant, feel free to come back later and enlighten us.
