### ISSUE TITLE
[Feature Request] Encrypted SSH keys

### ISSUE THREAD

**Issue by HeavyHorst** [alexellis/k3sup#8]
## Current Behaviour

k3sup install --ip $IP --user root panics with
```
Public IP: xxx.xxx.xx.xx
ssh -i /home/rkaufmann/.ssh/id_rsa root@xxx.xxx.xx.xx
panic: ssh: cannot decode encrypted private keys

goroutine 1 [running]:
github.com/alexellis/k3sup/pkg/cmd.loadPublickey(0xc4200ba1a0, 0x1b, 0xc42005bbb0, 0x3)
	/home/alex/go/src/github.com/alexellis/k3sup/pkg/cmd/install.go:132 +0x136
github.com/alexellis/k3sup/pkg/cmd.MakeInstall.func1(0xc4200dc280, 0xc4200c0240, 0x0, 0x4, 0x0, 0x0)
	/home/alex/go/src/github.com/alexellis/k3sup/pkg/cmd/install.go:54 +0x445
github.com/alexellis/k3sup/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200dc280, 0xc4200c0200, 0x4, 0x4, 0xc4200dc280, 0xc4200c0200)
	/home/alex/go/src/github.com/alexellis/k3sup/vendor/github.com/spf13/cobra/command.go:826 +0x468
github.com/alexellis/k3sup/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200dca00, 0x0, 0xc4200dc780, 0xc4200dcb50)
	/home/alex/go/src/github.com/alexellis/k3sup/vendor/github.com/spf13/cobra/command.go:914 +0x306
github.com/alexellis/k3sup/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200dca00, 0xc42005bf60, 0x1)
	/home/alex/go/src/github.com/alexellis/k3sup/vendor/github.com/spf13/cobra/command.go:864 +0x2b
main.main()
	/home/alex/go/src/github.com/alexellis/k3sup/main.go:22 +0x145

```

## Possible Solution

The Program could ask for the ssh key passphrase and use 
`signer, err := ssh.ParsePrivateKeyWithPassphrase(key, []byte("password"))` instead of 
`signer, err := ssh.ParsePrivateKey(key)`

**Comment by alexellis** [comment]
Derek set title: [Feature Request] Encrypted SSH keys

**Comment by alexellis** [comment]
Thank you for your feature request :+1:

**Comment by alexellis** [comment]
As a workaround you could generate a new key without its own password and use that with your remote host.

This is an arrow that people run into only if they have encrypted that SSH key with an additional (optional) password. 

if anybody lands here and has the same request please vote this feature up with a :+1:

**Comment by gabrielsagnard** [comment]
👍

**Comment by chrisludwig** [comment]
+1

**Comment by kaihoffman** [comment]
👍

**Comment by alexellis** [comment]
Hi everyone, please try out the latest release `0.2.3` with the changes submitted by @HeavyHorst in #9. Thank you Rene 👍

**Comment by tobru** [comment]
I just tested `0.2.3` using my encrypted SSH key: _It just works_! Thank you very much, great addition.
