### ISSUE TITLE
[Feature Request] Write config to ~/.kube/config

### ISSUE THREAD

**Issue by jwalton** [alexellis/k3sup#81]
## Expected Behaviour

k3sup should add a new context to ~/.kube/config.

## Current Behaviour

k3sup writes a brand new kubeconfig file.

## Possible Solution

Basically what I'd like to see happen is, pass a CLI option like `--save-default-config --context foo` which would get k3sup to run the equivalent of:

```
        kubectl config set-cluster foo --server=https://[ip-address]:6443 --certificate-authority=[cafile]
        kubectl config set-credentials foo-admin --username=admin --password=[password]
        kubectl config set-context foo --cluster=foo --user=foo-admin
        kubectl config use-context foo
```

(Or, just write the equivalent changes directly to ~/.kube/config.)

## Context

It's annoying to run multiple kube configs.  :P

**Comment by jwalton** [comment]
A slightly hacky workaround to get this behavior:

```
$ k3sup install ... --local-path=/tmp/config --context=foo
$ KUBECONFIG=/Users/me/.kube/config:/tmp/config kubectl config view --raw > ~/.kube/config
```

This is a little "unsafe" though, in that if you already have a cluster/context/user named "foo", you'll end up overwriting it.

**Comment by utsavanand2** [comment]
@jwalton k3sup already has an option to merge the new kubeconfig to an existing one. Do you want to add an extra option to define the context for the new kubeconfig?

**Comment by jwalton** [comment]
> k3sup already has an option to merge the new kubeconfig to an existing one.

Really?  What is this option?

I saw this in the docs:

> `--local-path` - default is `./kubeconfig` - set the path into which you want to save your VM's kubeconfig

And I assumed if I did something like:

```sh
$ k3sup install --ip XXX --user ubuntu \
          --local-path ~/.kube/config \
          --context ca-central \
          --skip-install
```

that this would merge write the config "into" ~/.kube/config (like the docs say), as opposed to "overtop of", but this doesn't work.  It overwrites my ~/.kube/config and all my old configs are gone.  None of the other options listed in the README.md seem relevant.

**Comment by utsavanand2** [comment]
If you run --local-path pointing to the existing kubeconfig with the
--merge flag it will merge the two kubeconfigs instead of overwriting it.
Run k3sup install --help to see the merge option

**Comment by jwalton** [comment]
Ah!  Thanks!  Should maybe add this to the README.  :)

**Comment by alexellis** [comment]
Whilst the README cannot be an exhaustive list of every option available, reasonable PRs are welcome and help is available with each command via `k3sup command --help`.

Thanks @utsavanand2
