### ISSUE TITLE
Convert "inlets-operator" app to use the new helm chart

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#88]
## Expected Behaviour

Convert "inlets-operator" app to use the new helm chart from https://github.com/inlets/inlets-operator/tree/master/chart/inlets-operator

It should also accept the `--provider` flag and anything else that is strictly essential to work with the various providers given.

## Current Behaviour

Hard-coded to DigitalOcean using static YAML manifest files

## Possible Solution

Mirror the approach taken with the `openfaas` app.

**Comment by utsavanand2** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thanks for doing the PR @utsavanand2

**Comment by utsavanand2** [comment]
Loved doing it!
