### ISSUE TITLE
k3s only works with iptables-legacy

### ISSUE THREAD

**Issue by e-minguez** [alexellis/k3sup#89]
## Expected Behaviour
After deploying k3s with k3sup the networking should be working

## Current Behaviour
It seems `iptables-legacy` is required in Debian Buster at least.

* https://github.com/rancher/k3s/issues/703#issuecomment-522355829
* https://github.com/kubernetes/kubernetes/issues/71305

## Possible Solution
k3sup should verify the OS and the iptables version and switch to the legacy version if required

```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy > /dev/null
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy > /dev/null
```

## Steps to Reproduce (for bugs)
1. Install k3sup
2. Deploy k3s using k3sup in latest raspbian in at least 2 raspberry pis
3.
4.

## Context
Pods cannot reach other pods or the internet

## Your Environment
RPI3 cluster (1+1) with latest raspbian

**Comment by alexellis** [comment]
I'm going to close this issue and ask you to file it upstream on the https://github.com/rancher/k3s repo.

K3sup is only a wrapper for the k3s' installer script. 

Perhaps we can add a note here in the README for RPi users?

**Comment by e-minguez** [comment]
While I agree the main issue is k3s, k3sup is supposed to make k3s installation easy hence k3sup should be able to identify the problem and provide a workaround.
I agree the first step can be a note in the README.
