### ISSUE TITLE
[Feature] Add HA masters with k3s and dqlite

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#93]
## Expected Behaviour

@ibuildthecloud is adding HA master support with dqlite over at -> https://github.com/rancher/k3s/pull/1034

## Current Behaviour

Not yet available in k3s or k3sup

## Possible Solution

We should add support for the new flags in `k3sup install/join` so that we're ready for the first rc release.

Darren gives examples on the PR ->

```
# Start one server with clustering enabled on serve1
./k3s server --cluster-init --token SECRET

# On server2 join the cluster
./k3s server -t SECRET -s https://server1:6443

# On server3 join the cluster
./k3s server -t SECRET -s https://server1:6443
```

**Comment by colek42** [comment]
Thinking an interface such as ```k3sup install --ip=192.168.0.100 --ip=192.168.0.101 --ip=192.168.0.102 --user=root``` will work.  Also need to change the generated kubeconfig, thinking that will separate this into two prs with the first only adding support at initialization.

**Comment by alexellis** [comment]
I wondered about `k3sup install` then `k3sup join` with a flag - or `k3sup install` for each server plus a flag?

**Comment by colek42** [comment]
If you assign this to me I can start working on it now.  `k3sup install` then `k3sup join` is going to be the api I use.

**Comment by alexellis** [comment]
I don't think I can assign it to you since you haven't contributed yet, but feel free to have a go at it.

**Comment by alexellis** [comment]
@colek42 how are you getting on with prototyping this?

**Comment by colek42** [comment]
@alexellis was on vacation.  Working on this tonight.

**Comment by alexellis** [comment]
I spent some time on this over the weekend. It looks like armhf doesn't work with dqlite just yet.
