### ISSUE TITLE
Running --merge after re-installing k3s gave a certificate error

### ISSUE THREAD

**Issue by orlangure** [alexellis/k3sup#95]
After reinstalling k3s in a cluster, and trying to connect to it again with k3sup (with or without `--skip-install`), there is a certificate issue, and all commands fail.

## Expected Behaviour
Reinstalling k3s using k3sup will handle updating certificates, and `kubectl` will be configured to use the cluster.

## Current Behaviour
```
k3sup install --ip my-ip --context test --merge --local-path ~/.kube/config
# or
k3sup install --skip-install --ip my-ip --context test --merge --local-path ~/.kube/config
```
The above command completes successfully, but any `kubectl` command results in the certificate related error from the title. It happens when `test` context was already defined in my config.

## Steps to Reproduce (for bugs)
```
k3sup install --ip my-ip --context test --merge --local-path ~/.kube/config
kubectl get pods # all is good

ssh my-ip
k3s-uninstall.sh
exit

kubectl config delete-context test
kubectl config delete-cluster test

k3sup install --ip my-ip --context test --merge --local-path ~/.kube/config
kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority
```

## Context
I wanted to completely reset k3s cluster I used for testing, and test my deployment from scratch. I wanted to continue using the same context/cluster names, but couldn't make it work. In the end I had to use a new cluster/context name, and it helped.

## Your Environment
client: macos 10.14.5
server: ubuntu 18.04

**Comment by alexellis** [comment]
Did you reboot after `k3s-uninstall.sh`?

What happens if you *do not merge*, but output to a separate file?

**Comment by alexellis** [comment]
Given separate discussion on Slack, I'll re-open. This does seem like an edge-case, but happy to look into it further if you can provide more information.

**Comment by colin-mccarthy** [comment]
I am having the same issue

**Comment by weberc2** [comment]
I'm running into a similar issue. It seems `--merge` doesn't update any of the cluster info, including the "server" field? k3sup version 0.9.7, k3s version v1.18.15+k3s1 (60f1e80d).

**Comment by alexellis** [comment]
Please raise your own issue and give step by step instructions for reproduction. If you skip and summarise, it'll just delay someone looking into it.
