### ISSUE TITLE
Add --ingress-class to "openfaas-ingress" - "app"

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#98]
## Expected Behaviour

Better support for Traefik

## Current Behaviour

When I use Traefik I have to edit the generated files manually after applying them.

## Possible Solution

* Add flag
* Update template to use flag
* Have default for `nginx`

**Comment by alexellis** [comment]
https://github.com/alexellis/k3sup/blob/master/pkg/cmd/openfaas_ingress_app.go

**Comment by andrewelkins** [comment]
I can take this on. I probably won't get to it until the weekend.

**Comment by alexellis** [comment]
Thank you

**Comment by alexellis** [comment]
Hi @andrewelkins I didn't hear from you and needed this feature, so I've added it. Please take a look at the PR and see what you think. Let me know if you want to take on anything else in the future.
